#!/usr/bin/env python3
"""gen_param_get.py -- the JX-3P unit parameter object's GET (its vtable +0x60, rva 0x3E8E10), as a table:
for every id the switch knows, the dword offset in the object it returns. EXECUTED (Unicorn only): the
object (0x700 bytes) is filled with markers (offset / 4 + 0x51000000), GET is called for each id
0..4095 with edx = 0 (as the assigner's read, rva 0x357E60, passes it), and the marker it returns names
the offset; an id it does not know returns 0 (not found). Then the object is restored.

The assigner reads its parameters through GET (798 the "wt" flag, 799 and 800 in the voice-count
setter); before 2026-10-10 the port answered every read from an array of zeros.

    python3 jx3p/tools/gen_param_get.py > jx3p/src/jx_param_get.h
"""
import hashlib
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(REPO, 'tools', 'verify'))

GET, SIZE, MARK = 0x3E8E10, 0x700, 0x51000000


def main():
    import jx_emu as J
    jx = J.JX()
    jx.run_static_init()
    jx.build()
    uc, proc = jx.uc, jx.proc[0]
    keep = bytes(uc.mem_read(proc, SIZE))
    marked = bytearray(keep[:8]) + b''.join(struct.pack('<I', MARK + o // 4) for o in range(8, SIZE, 4))
    uc.mem_write(proc, bytes(marked))
    out = jx.bump(16)
    table = []
    for pid in range(4096):
        uc.mem_write(out, struct.pack('<I', 0xDEADBEEF))
        found = jx.call(J.IB + GET, rcx=proc, rdx=0, r8=pid, r9=out) & 0xFF
        v = struct.unpack('<I', uc.mem_read(out, 4))[0]
        if not found:
            continue
        if v == 0xDEADBEEF or not (MARK + 2 <= v < MARK + SIZE // 4):
            raise SystemExit('id %d: found, but the value 0x%x is no marker -- not a plain read' % (pid, v))
        table.append((pid, (v - MARK) * 4))
    uc.mem_write(proc, keep)
    blob = b''.join(struct.pack('<ii', a, b) for a, b in table)
    lines = ['/* jx_param_get.h -- GENERATED by jx3p/tools/gen_param_get.py from the booted JX-3P; do not edit.',
             ' * The unit parameter object\'s GET (vtable +0x60, rva 0x3E8E10): for each id it knows, the',
             ' * offset of the dword it returns (found = 1); any other id is not found. EXECUTED on a marked',
             ' * copy of the object. */',
             '#ifndef JX_PARAM_GET_H', '#define JX_PARAM_GET_H', '#include <stdint.h>',
             '#define JX_PARAM_GET_SHA256 "%s"' % hashlib.sha256(blob).hexdigest(),
             '#define JX_PARAM_GET_N %d' % len(table),
             'static const int32_t JX_PARAM_GET[JX_PARAM_GET_N][2] = {      /* { id, offset } in id order */']
    for i in range(0, len(table), 6):
        lines.append('    ' + ' '.join('{ %d, 0x%03x },' % t for t in table[i:i + 6]))
    lines += ['};', '#endif', '']
    sys.stdout.write('\n'.join(lines))
    sys.stderr.write('%d ids found; 798 -> %s, 799 -> %s, 800 -> %s\n' % (
        len(table), *[hex(dict(table).get(i, -1)) for i in (798, 799, 800)]))


if __name__ == '__main__':
    main()
