#!/usr/bin/env python3
"""gen_recall_c.py -- emit jx3p/src/jx_recall_lut.h from the oracle-captured
per-pool LUTs. Each active pool's dispatch is a function of ONE input byte
(0..255); the table is the COMPLETE enumeration of that finite domain -- the
exact function, not an approximation. Regenerated from the binary every gate run
(recall_ref_emu -> recall_separ produce the pickle this reads). The 7 interacting
cells carry a value-pool override (proven bit-exact, all 64 factory patches)."""
import sys, os, struct, pickle, json

def main():
    refdir = sys.argv[1]
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "jx_recall_lut.h")
    D = pickle.load(open(os.path.join(refdir, "recall_lut.pkl"), "rb"))
    lut = D["lut"]; active = D["active"]; clean = D["clean"]
    OVERRIDE = {1072: 12, 1088: -1, 3056: 49, 3072: 50, 3088: -1, 3104: 52, 4000: -1, 13440: -1}  # 1088 keeps clean: see recall_model_check.py

    # gather (pool, cell) -> 256 uint32 (clean value where the pool doesn't write)
    entries = []   # (pool, cell, [256 u32])
    for pool in active:
        cs = set()
        for b in range(256):
            cs |= set(lut[pool][b].keys())
        for cell in sorted(cs):
            cval = struct.unpack('<I', clean[cell:cell+4])[0]
            arr = []
            for b in range(256):
                w = lut[pool][b].get(cell)
                arr.append(struct.unpack('<I', w)[0] if w else cval)
            entries.append((pool, cell, arr))

    L = []
    L.append("/* jx_recall_lut.h -- GENERATED by tools/gen_recall_c.py from the JX")
    L.append(" * plugin's own dispatch (0x3EBB00) under Unicorn. Complete single-byte")
    L.append(" * domain enumeration per (pool,cell) = the exact recall function. Do not")
    L.append(" * edit by hand; `make verify SYNTH=jx3p` regenerates and re-proves it. */")
    L.append("#ifndef JX_RECALL_LUT_H")
    L.append("#define JX_RECALL_LUT_H")
    L.append("#include <stdint.h>")
    L.append("#define JX_RECALL_BLOCK %d" % D.get("block", 16128))
    L.append("#define JX_RECALL_N_ENTRIES %d" % len(entries))
    # clean base cells that any entry references (for override=-1 -> clean)
    L.append("typedef struct { int pool; int cell; uint32_t v[256]; } jx_recall_entry;")
    L.append("static const jx_recall_entry JX_RECALL[JX_RECALL_N_ENTRIES] = {")
    for pool, cell, arr in entries:
        vals = ",".join("0x%08x" % x for x in arr)
        L.append("  { %d, %d, {%s} }," % (pool, cell, vals))
    L.append("};")
    # active pool order
    L.append("#define JX_RECALL_N_ACTIVE %d" % len(active))
    L.append("static const int JX_RECALL_ACTIVE[JX_RECALL_N_ACTIVE] = {%s};"
             % ",".join(str(p) for p in active))
    # overrides: cell, value_pool (-1 => force clean value)
    ov = sorted(OVERRIDE.items())
    L.append("#define JX_RECALL_N_OVERRIDE %d" % len(ov))
    L.append("typedef struct { int cell; int value_pool; uint32_t clean; } jx_recall_ov;")
    L.append("static const jx_recall_ov JX_RECALL_OVERRIDE[JX_RECALL_N_OVERRIDE] = {")
    for cell, vp in ov:
        cv = struct.unpack('<I', clean[cell:cell+4])[0]
        L.append("  { %d, %d, 0x%08x }," % (cell, vp, cv))
    L.append("};")
    L.append("#endif")
    open(out, "w").write("\n".join(L) + "\n")
    print("wrote %s (%d entries, %d active pools)" % (out, len(entries), len(active)))

if __name__ == "__main__":
    main()
