#!/usr/bin/env python3
"""jx_conv_tables.py -- the JX-3P's render-object table, read from the plugin booted as a DAW boots it
(jx3p/tools/jx_host_emu.py: DllMain, the factory, initialize, setupProcessing; Unicorn only, two-process
rule), against the JUNO-60's (src/conv_tables.h, tools/verify/gen_conv_tables.py).

  table    rva 0xC7BC30 (the JUNO's 0xC43C30): 45 entries + the terminator, 32 bytes each {engine rate,
           host rate, L, M, coefficient vector, render function}; the lookup is rva 0x343940 (= the
           JUNO's 0x343A80, jx3p/tools/fw_map.py). The render functions by rva: 0x344130 identity,
           0x343CF0 converter (= 0x343E30), 0x344140 silence (= 0x344280).
  vectors  the coefficient vectors (std::vector<float>) the static initializers fill.
  setting  the dword table at rva 0x981B58 the setting listener (rva 0x3221D0, = the JUNO's 0x3222F0)
           indexes with vm.vs.sampleRate & 0x7F (the JUNO's: rva 0x94AB80).

The plugin is booted at two host rates; table, vectors and setting table must be byte-equal between
the boots (static data) or the tool refuses. Then:
  - the table and the vectors are compared with src/conv_tables.h in the generator's own blob form
    (JUNO_CONV_SHA256 hashes table + vectors + setting table; here the table + vectors part is
    rebuilt from the header's arrays and hashed on both sides);
  - the setting table is written as jx3p/src/jx_srate.h with --emit (stdout otherwise).

    python3 jx3p/tools/jx_conv_tables.py            exit 0 = the JX table + vectors == the JUNO's
    python3 jx3p/tools/jx_conv_tables.py --emit     also write jx3p/src/jx_srate.h
    python3 jx3p/tools/jx_conv_tables.py --tooth    one coefficient bit flipped on the JX side must be
                                                    seen (exit 0 = the comparison bites)
"""
import hashlib
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
TABLE_RVA, NENT, SRATE_RVA = 0xC7BC30, 46, 0x981B58
KIND = {0x344130: 0, 0x343CF0: 1, 0x344140: 2}      # identity, converter, silence (the JUNO's numbering)
OUT = os.path.join(REPO, 'jx3p', 'src', 'jx_srate.h')


def read_all(host_rate):
    sys.path.insert(0, HERE)
    import jx_host_emu as X
    h = X.JXHost()
    h.start(host_rate, 512)
    uc, ib = h.uc, X.J.IB
    ents, vecs, order = [], {}, []
    for k in range(NENT):
        raw = bytes(uc.mem_read(ib + TABLE_RVA + 32 * k, 32))
        er, hr, L, M = struct.unpack_from('<iiii', raw, 0)
        vp, fn = struct.unpack_from('<QQ', raw, 16)
        if fn - ib not in KIND:
            raise SystemExit('entry %d: render function rva 0x%x is none of the three' % (k, fn - ib))
        vi = -1
        if vp:
            if vp not in vecs:
                b, e_ = struct.unpack('<QQ', uc.mem_read(vp, 16))
                vecs[vp] = bytes(uc.mem_read(b, e_ - b)) if e_ > b else b''
                order.append(vp)
            vi = order.index(vp)
        ents.append((er, hr, L, M, vi, KIND[fn - ib]))
    srate = bytes(uc.mem_read(ib + SRATE_RVA, 128 * 4))
    return ents, [vecs[v] for v in order], srate


def juno_side():
    """table + vectors + setting table from src/conv_tables.h, as gen_conv_tables.py packed them"""
    src = open(os.path.join(REPO, 'src', 'conv_tables.h')).read()

    def arr(name):
        m = re.search(r'\b%s\[[^\]]*\] = \{(.*?)\};' % re.escape(name), src, re.S)
        if not m:
            raise SystemExit('src/conv_tables.h: no array %s' % name)
        return [int(x.rstrip('u'), 0) for x in re.findall(r'-?0x[0-9a-f]+u?|-?\d+', m.group(1))]
    nvec = int(re.search(r'JUNO_CONV_NVEC (\d+)', src).group(1))
    vlen = arr('JUNO_CONV_VLEN')
    vecs = [struct.pack('<%dI' % n, *arr('JUNO_CONV_V%d' % i)[:n]) for i, n in enumerate(vlen)]
    flat = arr('JUNO_CONV')
    ents = [tuple(flat[i:i + 6]) for i in range(0, len(flat), 6)]
    srate = struct.pack('<128i', *arr('JUNO_SRATE'))
    sha = re.search(r'JUNO_CONV_SHA256 "([0-9a-f]+)"', src).group(1)
    blob = b''.join(struct.pack('<iiiiii', *e) for e in ents) + b''.join(vecs) + srate
    if hashlib.sha256(blob).hexdigest() != sha:
        raise SystemExit('src/conv_tables.h: its arrays do not hash to its JUNO_CONV_SHA256 -- refusing')
    return ents, vecs, srate


def part(ents, vecs):
    return b''.join(struct.pack('<iiiiii', *e) for e in ents) + b''.join(vecs)


def emit(srate):
    sr = struct.unpack('<128i', srate)
    out = ['/* jx_srate.h -- GENERATED by jx3p/tools/jx_conv_tables.py from the booted JX-3P; do not edit.',
           ' * The engine-rate setting table (rva 0x981B58): the setting listener (rva 0x3221D0) indexes it',
           ' * with vm.vs.sampleRate & 0x7F; 0..4 the engine rates, 5 the automatic setting (never read),',
           ' * 6..127 the bytes that follow it in the image (they differ from the JUNO-60\'s from index 6).',
           ' * The render-object table and its vectors are the JUNO-60\'s (src/conv_tables.h, the same',
           ' * bytes: jx3p/docs/HOST_LAYER.md). */',
           '#ifndef JX_SRATE_H', '#define JX_SRATE_H', '#include <stdint.h>',
           '#define JX_SRATE_SHA256 "%s"' % hashlib.sha256(srate).hexdigest(),
           'static const int32_t JX_SRATE[128] = {']
    for r in range(0, 128, 8):
        out.append('    ' + ', '.join('%d' % x for x in sr[r:r + 8]) + ',')
    out += ['};', '#endif', '']
    return '\n'.join(out)


def main():
    args = sys.argv[1:]
    a = read_all(48000.0)
    b = read_all(44100.0)
    if a != b:
        raise SystemExit('the JX table differs between two boots: not static data -- refusing')
    ents, vecs, srate = a
    if '--tooth' in args:
        v = bytearray(vecs[1])
        v[4 * 100] ^= 1                                   # one bit of coefficient 100 of the 44.1k/48k vector
        vecs = list(vecs)
        vecs[1] = bytes(v)
    jents, jvecs, jsrate = juno_side()
    pj, pjx = part(jents, jvecs), part(ents, vecs)
    same = pj == pjx
    print('JX table: %d entries, %d vectors (%s floats); sha256 of table + vectors %s' % (
        len(ents), len(vecs), '+'.join(str(len(v) // 4) for v in vecs), hashlib.sha256(pjx).hexdigest()))
    print('JUNO-60 (src/conv_tables.h): %d entries, %d vectors; sha256 %s' % (
        len(jents), len(jvecs), hashlib.sha256(pj).hexdigest()))
    sr, jsr = struct.unpack('<128i', srate), struct.unpack('<128i', jsrate)
    diff = [i for i in range(128) if sr[i] != jsr[i]]
    print('setting table: 0..5 %s; %d of 128 differ from the JUNO-60\'s (first index %s)' % (
        list(sr[:6]), len(diff), diff[0] if diff else '-'))
    if '--tooth' in args:
        print('jx_conv_tables --tooth: %s' % ('BITES' if not same else 'DID NOT BITE'))
        return 0 if not same else 1
    if '--emit' in args:
        with open(OUT, 'w') as fh:
            fh.write(emit(srate))
        print('wrote %s' % os.path.relpath(OUT, REPO))
    else:
        sys.stdout.write(emit(srate))
    print('jx_conv_tables: %s' % ('EQUAL -- the JX-3P uses the JUNO-60\'s table and vectors (src/juno_conv.c)'
                                  if same else 'DIFFERENT -- the JX-3P needs its own table'))
    return 0 if same else 1


if __name__ == '__main__':
    sys.exit(main())
