#!/usr/bin/env python3
"""jx_patch_records.py -- the engine-event records the JX-3P's OWN entry paths queue (EXECUTED; Unicorn
only), written to jx3p/gen/jx_patch_records.json for the engine-level oracle (tools/verify/jx_emu.py
product_boot / recall_product) and the exporters of the port's data.

The plugin booted as a DAW boots it (jx3p/tools/jx_host_emu.py):
  boot      the records IComponent::initialize leaves in the engine queue (84 at 2026-10-10: the default
            patch as 72 model values, MASTER TUNE, 10 host settings, one kind-0 all-sound-off)
  patch k   the records its patch browser's load (rva 0x335730) of factory record k queues (75: writePatch,
            MASTER TUNE, the patch tree in its order), each load on a fresh instance after the boot
            records were applied by one process() block
Each record: [kind, id, value] -- kind 2 = a parameter (the render driver hands it to the engine's host
entry, rva 0x3F9A30), kind 0 = a MIDI record. jx3p/tools/jx_recall_product_check.py proves that the
engine alone given these records through its own host entry (after the id map's populate, rva 0xAD480)
holds what the plugin holds.

    python3 -u jx3p/tools/jx_patch_records.py [--bank FILE] [--out FILE]
"""
import hashlib
import json
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(REPO, 'tools', 'verify'))
import jx_bank as B                                    # noqa: E402

OUT = os.path.join(REPO, 'jx3p', 'gen', 'jx_patch_records.json')


def recs(q):
    return [[kind, struct.unpack_from('<I', r, 12)[0], struct.unpack_from('<i', r, 20)[0]] for kind, off, r in q]


def main():
    a = sys.argv[1:]
    bank_path = a[a.index('--bank') + 1] if '--bank' in a else os.path.join(REPO, 'jx3p', 'truth', 'preset_bank_1.bin')
    out = a[a.index('--out') + 1] if '--out' in a else OUT
    bank = open(bank_path, 'rb').read()
    npatch = (len(bank) - B.BANK_HEADER) // B.BANK_STRIDE
    import jx_host_emu as X
    h = X.JXHost()
    h.start(48000.0, 512)
    boot = recs(h.queue())
    h.process(512)                                        # the boot records applied, the queue empty
    assert not h.queue(), 'the queue is not empty after the first block'
    patches = []
    for k in range(npatch):
        tail = bank[B.BANK_HEADER + k * B.BANK_STRIDE + B.BANK_BLOB_OFF:B.BANK_HEADER + (k + 1) * B.BANK_STRIDE]
        patches.append(recs(h.load_patch(tail)))
        h.process(1)                                      # applied: the next load starts from an empty queue
        assert not h.queue()
    doc = {
        'what': 'engine-event records the JX-3P queues: initialize (boot) and its patch browser load per bank '
                'record (patches), each [kind, id, value]; generated by jx3p/tools/jx_patch_records.py',
        'bank_sha256': hashlib.sha256(bank).hexdigest(),
        'boot': boot,
        'patches': patches,
    }
    body = json.dumps(doc, separators=(',', ':'), sort_keys=True)
    with open(out + '.partial', 'w') as fh:
        fh.write(body + '\n')
    os.replace(out + '.partial', out)
    print('boot %d records; %d patches, %s records each; sha256 %s -> %s' % (
        len(boot), len(patches), sorted({len(p) for p in patches}), hashlib.sha256(body.encode()).hexdigest()[:16],
        os.path.relpath(out, REPO)))


if __name__ == '__main__':
    main()
