#!/usr/bin/env python3
"""fork_authority.py -- IS THE FORK STILL THE PLUGIN, apart from what we removed?

THE PROBLEM THIS SOLVES. plugin_check.py compares SAMPLE BY SAMPLE against the
plugin binary, and that is the right gate for the TRUNK, which is bit-exact.
It is the WRONG gate for the fork: the fork deliberately changes where the
DCO's aliases land, so a sample-domain residual is dominated by a change that
was approved on purpose, and the number it prints cannot distinguish "the
approved change" from "a defect". Running it and quoting the dB would be
worse than not running it.

So this gate measures the fork against the plugin IN THE DOMAIN THE FORK
PROMISES TO PRESERVE, and reports -- without gating -- the domain it does not.

WHAT THE FORK PROMISES, each with a bound that was fixed BEFORE this gate was
written, by the exhaustive gate or the design decision that produced it:

  1. PITCH, to 0.05 cents. eb_pitch_fork's exhaustive gate over all 2^32 float
     inputs measured 0.00074 cents worst; 0.05 is the published bound, ~1000x
     below the plugin's own 18.2-cent UNISON scatter.
  2. HARMONIC LEVELS, the tone itself. Half-oversampling moves ALIASES; the
     harmonics are generated by shaping that is byte-identical in both paths.
     o8_gate2 measured 0.01 dB at high pitch and up to 3.3 dB only at bins
     65-90 dB down above 14 kHz.
  3. THE AMPLITUDE ENVELOPE. Attack, decay, sustain and release timing are
     untouched by every fork flag, so they must track the plugin closely.
     Spectra average this away, which is exactly why it is measured separately:
     the listen firmware's release defect (a 4,716-count state jump) was
     INAUDIBLE to a spectrum and obvious in an envelope.

WHAT IT ONLY REPORTS: the non-harmonic residual per band. That is the alias
content, i.e. the approved relaxation, and printing it as a number is how the
relaxation stays visible instead of becoming folklore.

THE STRUCTURAL CHECK THAT MAKES THE ABOVE MEAN SOMETHING (--decompose). With
every fork flag OFF, the build is the trunk and must be EXACTLY 0 against the
plugin -- that is plugin_check's existing 11/11 result and it is this gate's
non-vacuity proof. Then each flag is turned on ALONE. If the total difference
is accounted for by the enumerated flags, there is no unexplained residual;
an interaction that appears only when flags are combined is a defect, and it
is the one class this project has no other way to see.

TWO-PROCESS RULE: the reference is rendered by plugin_check.py's own --ref
worker (Unicorn, no ctypes); candidates by its --cand-worker (ctypes, no
Unicorn). This file compares pickles and loads nothing.
"""
import argparse
import os
import subprocess
import sys
import tempfile

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path[:0] = [HERE, os.path.join(REPO, "tools", "trackb"),
                os.path.join(REPO, "tools", "verify")]

# THE RATE IS SET FOR BOTH SIDES EXPLICITLY. plugin_check's reference worker
# reads JUNO_RENDER_SR and ABORTS if it disagrees with the gate's own SR --
# which it did on the first run here, because the environment carried 48000
# from an earlier tool. That abort is the harness refusing to compare two
# renders at different rates, and it is worth more than a passing number.
SR = float(os.environ.get("JUNO_FORK_AUTH_SR", "44100"))
os.environ["JUNO_RENDER_SR"] = "%g" % SR
# BOUNDS, all fixed by prior measurement -- see the header. None of them was
# chosen after seeing this gate's output.
CENTS_BOUND = 0.05
HARM_DB_BOUND = 0.5       # below 14 kHz, on harmonics within 60 dB of peak
ENV_DB_BOUND = 0.5        # 10 ms RMS windows above the noise floor


def run_side(args, tmp, tag):
    import pickle
    out = os.path.join(tmp, tag + ".pkl")
    r = subprocess.run([sys.executable,
                        os.path.join(HERE, "plugin_check.py")] + args + [out],
                       capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(r.stderr[-3000:])
        raise SystemExit("%s worker failed" % tag)
    with open(out, "rb") as f:
        return pickle.load(f)


def mono(stream):
    x = np.asarray(stream, dtype=float)
    return 0.5 * (x[0::2] + x[1::2])


def fundamental(x):
    """f0 by parabolic interpolation on the largest low-band peak.

    THE WINDOW IS SIZED TO THE SCENARIO, not fixed at 32768. plugin_check's
    scenarios are ~1/3 the length of null_b's because every frame costs half a
    millisecond of emulation, so a fixed 32768-sample window silently returned
    None and the pitch and harmonic rows -- the two the fork exists to
    preserve -- simply did not appear in the report. A gate whose main
    measurements quietly skip themselves is worse than one that fails. */"""
    n = 1 << 14
    while n > len(x) and n > 1024:
        n >>= 1
    if len(x) < n:
        return None
    seg = x[:n] * np.hanning(n)
    X = np.abs(np.fft.rfft(seg))
    f = np.fft.rfftfreq(n, 1.0 / SR)
    m = (f > 40) & (f < 3000)
    i = int(np.argmax(np.where(m, X, 0)))
    if i < 1 or i + 1 >= len(X):
        return None
    a, b, c = X[i - 1], X[i], X[i + 1]
    d = a - 2 * b + c
    off = 0.0 if d == 0 else 0.5 * (a - c) / d
    return (i + off) * SR / n


def spec(x, n=1 << 14):
    n = min(n, 1 << int(np.floor(np.log2(max(len(x), 2)))))
    seg = x[:n] * np.hanning(n)
    X = np.abs(np.fft.rfft(seg))
    return np.fft.rfftfreq(n, 1.0 / SR), 20 * np.log10(np.maximum(X, 1e-12))


def envelope(x, win=441):
    k = len(x) // win
    y = x[:k * win].reshape(k, win)
    return 20 * np.log10(np.maximum(np.sqrt((y ** 2).mean(axis=1)), 1e-9))


def analyse(tag, r, c):
    """Returns (rows, ok). One row per measurement, each with its own bound."""
    R, C = mono(r), mono(c)
    n = min(len(R), len(C))
    R, C = R[:n], C[:n]
    rows, ok = [], True

    # --- 1. PITCH, in cents, measured on the sustained part -----------------
    lead = int(0.15 * SR)
    f0r, f0c = fundamental(R[lead:]), fundamental(C[lead:])
    if f0r and f0c:
        cents = 1200.0 * np.log2(f0c / f0r)
        good = abs(cents) <= CENTS_BOUND
        ok &= good
        rows.append(("pitch", "%.4f cents (f0 %.2f Hz)" % (cents, f0r),
                     "<= %.2f" % CENTS_BOUND, good))

    # --- 2. HARMONIC LEVELS --------------------------------------------------
    if f0r:
        f, A = spec(R[lead:])
        _, B = spec(C[lead:])
        band = (f > 40) & (f < 14000)
        pk = A[band].max()
        worst, wf = 0.0, 0.0
        k = 1
        while k * f0r < 14000:
            fh = k * f0r
            m = (np.abs(f - fh) < max(0.004 * f0r, 12.0)) & (A > pk - 60.0)
            if m.any():
                d = float(np.max(np.abs(A[m] - B[m])))
                if d > worst:
                    worst, wf = d, fh
            k += 1
        good = worst <= HARM_DB_BOUND
        ok &= good
        rows.append(("harmonics", "worst %.3f dB at %.0f Hz" % (worst, wf),
                     "<= %.2f dB" % HARM_DB_BOUND, good))

        # --- REPORTED ONLY: the non-harmonic residual = the approved change --
        harm = np.zeros(len(f), bool)
        k = 1
        while k * f0r < SR / 2:
            harm |= np.abs(f - k * f0r) < max(0.004 * f0r, 12.0)
            k += 1
        for lo, hi in ((200, 3000), (3000, 7000), (7000, 14000), (14000, 20000)):
            m = (f >= lo) & (f < hi) & ~harm
            if m.any():
                rows.append(("  alias %d-%d Hz" % (lo, hi),
                             "plugin %.1f dB -> fork %.1f dB"
                             % (A[m].max(), B[m].max()), "reported", None))

    # --- 3. AMPLITUDE ENVELOPE ----------------------------------------------
    er, ec = envelope(R), envelope(C)
    live = er > er.max() - 60.0
    if live.any():
        diff = np.abs(er - ec)
        i = int(np.argmax(np.where(live, diff, -1)))
        d = float(diff[i])
        good = d <= ENV_DB_BOUND
        ok &= good
        rows.append(("envelope", "worst %.3f dB at t=%.3f s (%.1f dB below "
                     "peak)" % (d, i * 441.0 / SR, er[i] - er.max()),
                     "<= %.2f dB" % ENV_DB_BOUND, good))
    return rows, ok


def build_fork(tmp, flags, name):
    """One candidate .so with the given fork flags, via null_b's builder."""
    import null_b
    so = os.path.join(tmp, "%s.so" % name)
    env = dict(os.environ)
    for k in ("JUNO_EB_FORK", "JUNO_EB_LFO_SHARED", "JUNO_EB_HALF_OS"):
        env.pop(k, None)
    env.update(flags)
    r = subprocess.run([sys.executable, "-c",
                        "import sys; sys.path.insert(0, %r); import null_b; "
                        "null_b.build(%r, ['standalone'])" % (HERE, so)],
                       env=env, capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(r.stdout[-2000:] + r.stderr[-3000:])
        raise SystemExit("build failed for %s" % name)
    return so


# THE FLAG LADDER. Each row is one enumerated relaxation, alone, so an
# unexplained residual has nowhere to hide.
LADDER = [
    ("trunk (no flags)", {}),
    ("+ fork pitch",     {"JUNO_EB_FORK": "pitch"}),
    ("+ fork exp",       {"JUNO_EB_FORK": "exp"}),
    ("+ shared LFO",     {"JUNO_EB_LFO_SHARED": "1"}),
    ("+ half-OS DCO",    {"JUNO_EB_HALF_OS": "1"}),
    ("THE FORK (all)",   {"JUNO_EB_FORK": "both", "JUNO_EB_LFO_SHARED": "1",
                          "JUNO_EB_HALF_OS": "1"}),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scen", nargs="*",
                    default=["pluck POLY", "DCO noise"])
    ap.add_argument("--decompose", action="store_true",
                    help="run the whole flag ladder, not just the fork")
    a = ap.parse_args()

    tmp = tempfile.mkdtemp(prefix="forkauth_")
    print("=== FORK vs THE PLUGIN BINARY ===")
    print("  AUTHORITY : JUNO60.vst3 under Unicorn (its own recall + render)")
    print("  MEASURED  : pitch (cents), harmonic levels (dB), envelope (dB)")
    print("  REPORTED  : non-harmonic content per band -- the approved change")
    print("  rate      : %g Hz\n" % SR)

    ref = run_side(["--ref", "--scen"] + a.scen + ["--out"], tmp, "ref")
    ladder = LADDER if a.decompose else [LADDER[0], LADDER[-1]]

    allok = True
    for name, flags in ladder:
        so = build_fork(tmp, flags, name.replace(" ", "_").replace("+", "p")
                        .replace("(", "").replace(")", ""))
        cand = run_side(["--cand-worker", so, "--scen"] + a.scen + ["--out"],
                        tmp, "cand")
        print("--- %s ---" % name)
        for tag in a.scen:
            r = ref["streams"].get(tag)
            c = cand["streams"].get(tag)
            if r is None or c is None:
                print("  %s: MISSING -> FAIL" % tag); allok = False; continue
            rows, ok = analyse(tag, r, c)
            allok &= ok
            print("  %s:" % tag)
            for what, got, bound, good in rows:
                print("    %-18s %-34s %-14s %s"
                      % (what, got, bound,
                         "" if good is None else ("ok" if good else "FAIL")))
        print()
    print("VERDICT: %s" % ("PASS -- the fork is the plugin apart from the "
                           "enumerated relaxations" if allok else "FAIL"))
    return 0 if allok else 1


if __name__ == "__main__":
    sys.exit(main())
