#!/usr/bin/env python3
"""gen_s3_vectors.py — generate the firmware's evaluator test vectors.

Compiles the two fork evaluators ON THE HOST (where the exhaustive gates
certified them), evaluates a small input set that touches every branch —
clamp ends, a NaN, row boundaries, negative and positive interior, the exp
tails — and emits the (input, expected) pairs as hex-float C initializers.
The firmware refuses to print cycle numbers if the target's results differ:
a cycle count for a function that computes something else is worse than no
number.
"""
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

PITCH_IN = ["-25.0f", "-20.0f", "-19.999999f", "-11.25f", "-0.5f", "0.0f",
            "0.5f", "3.75f", "8.0f", "8.9f", "100.0f", "(0.0f/0.0f)"]
EXP_IN = ["-100.0f", "-87.5f", "-20.0f", "-1.0f", "0.0f", "0.5f", "2.92142f",
          "10.0f", "87.9f", "95.0f"]


def main():
    tmp = tempfile.mkdtemp(prefix="s3vec_")
    src = os.path.join(tmp, "gen.c")
    with open(src, "w") as f:
        f.write('#include <stdio.h>\n#include "eb_pitch_fork.h"\n'
                '#include "eb_exp_fork.h"\nint main(void){\n')
        for v in PITCH_IN:
            f.write('  { float i=%s, o=eb_pitch_fork_eval(i); '
                    'printf("P { %%af, %%af },\\n", (double)i, (double)o); }\n' % v)
        for v in EXP_IN:
            f.write('  { float i=%s, o=eb_exp_fork(i); '
                    'printf("E { %%af, %%af },\\n", (double)i, (double)o); }\n' % v)
        f.write("  return 0;\n}\n")
    exe = os.path.join(tmp, "gen")
    subprocess.run(["cc", "-std=c99", "-O2", "-ffp-contract=off",
                    "-I" + os.path.join(REPO, "engine_b"), "-o", exe, src,
                    os.path.join(REPO, "engine_b", "eb_pitch_fork.c"),
                    os.path.join(REPO, "engine_b", "eb_exp_fork.c"), "-lm"],
                   check=True)
    out = subprocess.run([exe], capture_output=True, text=True,
                         check=True).stdout
    pit, exp = [], []
    for line in out.splitlines():
        row = line[2:]
        # a NaN INPUT prints as nan/-nanf, which is not a C literal; restore
        # the arithmetic form. (NaN never appears as an EXPECTED value -- both
        # evaluators map NaN inputs to numbers, which is the point of testing
        # them.)
        if "nanf" in row.split(",")[0]:
            row = "{ (0.0f/0.0f), " + row.split(",", 1)[1].lstrip()
        # infinity prints as inf/inff -- also not a literal. It appears as an
        # EXPECTED value (the exp tail at x=95 overflows, exactly as libm
        # does, which is the point of that vector). inf == inf compares true,
        # so the check still bites.
        row = row.replace(" inff ", " (1.0f/0.0f) ").replace(" -inff ", " (-1.0f/0.0f) ")
        (pit if line[0] == "P" else exp).append(row)
    hdr = ("/* GENERATED by tools/engineb/gen_s3_vectors.py -- DO NOT EDIT.\n"
           " * Host-evaluated expected values for the fork evaluators; the\n"
           " * firmware halts on any mismatch. NaN inputs are written as\n"
           " * (0.0f/0.0f) upstream; the NaN row's expected value is what\n"
           " * the host produced for it. */\n")
    d = os.path.join(REPO, "esp32s3", "main")
    open(os.path.join(d, "s3_pitch_vectors.h"), "w").write(hdr + "\n".join(pit) + "\n")
    open(os.path.join(d, "s3_exp_vectors.h"), "w").write(hdr + "\n".join(exp) + "\n")
    print("wrote %d pitch + %d exp vectors" % (len(pit), len(exp)))


if __name__ == "__main__":
    sys.exit(main())
