#!/usr/bin/env python3
"""gen_c6_halfband.py — design the 2x decimator and MEASURE the half-OS cost.

Two jobs:
  (default)   design a 31-tap half-band FIR for 88.2k->44.1k decimation
              (remez, passband to 18 kHz, stopband from 26.1 kHz) and emit
              docs/engineb/data/c6_halfband.h.
  --measure   build c6_halfos_probe.c, render 4x vs 2x across an increment
              sweep, FFT both, and print the table F5's decision needs:
              in-band spectral difference and each path's alias floor.
"""
import os
import subprocess
import sys
import tempfile

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DATA = os.path.join(REPO, "docs", "engineb", "data")
TAPS = 31


def design():
    from scipy import signal as ss
    h = ss.remez(TAPS, [0, 18000, 26100, 44100], [1, 0], fs=88200)
    return h


def design_fallback():
    # windowed-sinc half-band if scipy is absent; measured, not assumed:
    # --measure reports whatever this delivers.
    n = np.arange(TAPS) - (TAPS - 1) / 2
    fc = 22050.0 / 88200.0
    h = 2 * fc * np.sinc(2 * fc * n) * np.kaiser(TAPS, 9.0)
    return h / h.sum()


def emit(h):
    L = ["/* c6_halfband.h -- GENERATED by tools/engineb/gen_c6_halfband.py.",
         " * 2x anti-alias decimator for the half-oversampling probe (F5).",
         " * %d taps at 88.2 kHz; design goal: match the port cascade's" % TAPS,
         " * in-band response to 18 kHz, stopband over the fold sources.",
         " * The MEASURED consequence of using it is the probe's table, not",
         " * this comment. */",
         "#define C6_HB_TAPS %d" % TAPS,
         "static const float c6_halfband[C6_HB_TAPS] = {"]
    for v in h:
        L.append("    %sf," % float(np.float32(v)).hex())
    L.append("};")
    open(os.path.join(DATA, "c6_halfband.h"), "w").write("\n".join(L) + "\n")
    print("wrote c6_halfband.h (%d taps)" % TAPS)


def spectrum(x, fs):
    w = np.hanning(len(x))
    X = np.abs(np.fft.rfft(x * w)) / (len(x) / 4)
    f = np.fft.rfftfreq(len(x), 1.0 / fs)
    return f, 20 * np.log10(np.maximum(X, 1e-12))


def measure():
    tmp = tempfile.mkdtemp(prefix="c6_")
    exe = os.path.join(tmp, "probe")
    subprocess.run(
        ["cc", "-std=c99", "-O2", "-ffp-contract=off",
         "-I" + os.path.join(REPO, "engine_b"), "-I" + DATA, "-o", exe,
         os.path.join(DATA, "c6_halfos_probe.c"),
         os.path.join(REPO, "engine_b", "eb_dco.c"),
         os.path.join(REPO, "engine_b", "eb_decim.c"), "-lm"], check=True)
    fs = 44100.0
    print("%8s %10s | %9s %9s | %9s %9s | %8s"
          % ("inc", "~f0 Hz", "alias4dB", "alias2dB", "sig4dB", "sig2dB",
             "inband diff dB"))
    worst = -999.0
    for inc in (0.005, 0.01, 0.02, 0.04, 0.08, 0.12):
        out = {}
        for mode in (4, 2):
            r = subprocess.run([exe, str(mode), repr(inc), "131072"],
                               capture_output=True, check=True)
            x = np.frombuffer(r.stdout, dtype=np.float32)[2048:131072]
            out[mode] = x
        n = min(len(out[4]), len(out[2]))
        a, b = out[4][:n], out[2][:n]
        f, A = spectrum(a, fs)
        _, B = spectrum(b, fs)
        # f0 of the saw at 4x internal rate: inc is phase/substep over [-1,1)
        # span 2 -> f0 = inc/2 * 4*fs
        f0 = inc / 2.0 * 4 * fs
        # harmonic bins: within 0.5% of k*f0 (folded); everything else in
        # 200 Hz..18 kHz that is not a harmonic is alias+noise floor.
        # TRUE harmonics only: k*f0 below output Nyquist, UNFOLDED. The
        # second revision of this classifier marked the FOLDED positions of
        # every partial as 'harmonic', which excluded precisely the aliases
        # from the alias measure -- a measure of everything except its
        # subject. Folded content now lands in the alias columns, for BOTH
        # paths: alias4 is the plugin's OWN alias floor, alias2 the fork's.
        harm = np.zeros(len(f), bool)
        k = 1
        while k * f0 < fs / 2:
            harm |= np.abs(f - k * f0) < max(0.002 * f0, 15.0)
            k += 1
        band = (f > 200) & (f < 18000)
        alias4 = A[band & ~harm].max()
        alias2 = B[band & ~harm].max()
        sig4 = A[band].max()
        sig2 = B[band].max()
        # harmonic-level match: the tone itself must survive the redesigned
        # decimator; worst level difference on true harmonic bins.
        hb = band & harm
        d = np.max(np.abs(A[hb] - B[hb])) if hb.any() else 0.0
        worst = max(worst, alias2 - alias4)
        print("%8.3f %10.0f | %9.1f %9.1f | %9.1f %9.1f | %8.2f"
              % (inc, f0, alias4, alias2, sig4, sig2, d))
    print("\nworst alias-floor RISE (2x vs the plugin's own 4x): %.1f dB"
          % worst)


if __name__ == "__main__":
    try:
        h = design()
        print("remez design")
    except Exception as e:
        print("scipy unavailable (%s); Kaiser fallback" % e)
        h = design_fallback()
    emit(h)
    if "--measure" in sys.argv:
        measure()
