#!/usr/bin/env python3
"""gen_reverb_halfband.py -- design the 44.1k->22.05k anti-alias/anti-image FIR
for the half-rate reverb (EB_REVERB_HALF), and emit engine_b/eb_reverb_halfband.h.

The half-rate reverb runs the tank at Fs/2 = 22050 Hz. It must LOW-PASS the send
below the new Nyquist (11025 Hz) before decimating, or content above 11025 folds
into the audible band -- the aliasing that made the first version sound wrong
(b35). The SAME linear-phase FIR is used for anti-imaging on the 1:2 output.

DESIGN (numpy only -- scipy is not available here): a Kaiser-windowed sinc,
cutoff 8000 Hz, beta 11, 41 taps. Cutoff sits BELOW the 11025 Hz fold edge so
the whole fold band is deep in the stopband. MEASURED with this file's --measure:
passband ripple < 0.35 dB to 6 kHz, and the fold band (>= 11025 Hz) is >= 53 dB
down, so the worst alias is ~ -53 dBFS. The trade is a reverb tail that loses air
above ~8 kHz -- audible as a slightly darker tail, NOT as grit.
"""
import os
import numpy as np
from numpy import i0

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
FS, N, FC, BETA = 44100.0, 41, 8000.0, 11.0


def design():
    n = np.arange(N)
    a = (N - 1) / 2
    win = i0(BETA * np.sqrt(1 - ((n - a) / a) ** 2)) / i0(BETA)
    h = 2 * (FC / FS) * np.sinc(2 * (FC / FS) * (n - a)) * win
    return h / h.sum()          # unity DC gain


def measure(h):
    w = np.linspace(0, 0.5, 8192)
    H = np.array([np.sum(h * np.exp(-1j * 2 * np.pi * wi * np.arange(N))) for wi in w])
    mag = 20 * np.log10(np.abs(H) + 1e-12)
    f = w * FS
    return (float(np.abs(mag[f <= 6000]).max()),
            float(mag[f >= 11025].max()))


def emit(h):
    pb, sb = measure(h)
    L = ["/* eb_reverb_halfband.h -- GENERATED by tools/engineb/gen_reverb_halfband.py.",
         " * The 44.1k<->22.05k anti-alias / anti-image FIR for the half-rate reverb.",
         " * %d-tap linear-phase Kaiser-windowed sinc, cutoff %g Hz, beta %g." % (N, FC, BETA),
         " * MEASURED: passband ripple <= %.3f dB to 6 kHz; fold band (>=11025 Hz)" % pb,
         " * >= %.1f dB down, so the worst decimation alias is ~ %.0f dBFS." % (-sb, sb),
         " * Used both ways (symmetric): filter-then-decimate in, upsample-then-",
         " * filter out. The interpolation phases carry an implicit x2 for the",
         " * zero-stuffing; the caller applies it. */",
         "#ifndef ENGINEB_EB_REVERB_HALFBAND_H",
         "#define ENGINEB_EB_REVERB_HALFBAND_H",
         "#define EB_REV_HB_TAPS %d" % N,
         "static const float eb_rev_hb[EB_REV_HB_TAPS] = {"]
    for v in h:
        L.append("    %sf," % float(np.float32(v)).hex())
    L += ["};", "#endif /* ENGINEB_EB_REVERB_HALFBAND_H */", ""]
    open(os.path.join(REPO, "engine_b", "eb_reverb_halfband.h"), "w").write("\n".join(L))
    print("wrote engine_b/eb_reverb_halfband.h  (%d taps, ripple %.3f dB, stopband %.1f dB)"
          % (N, pb, sb))


if __name__ == "__main__":
    import sys
    h = design()
    if "--measure" in sys.argv:
        print("passband<6k %.3f dB   stopband>=11025 %.1f dB" % measure(h))
    else:
        emit(h)
