/* gen_wt_tables.c — build eb_dco_wt.c's residual tables from the SHIPPING DCO.
 *
 * WHAT A RESIDUAL IS HERE. eb_dco_wt.c computes each arm's flat value directly
 * -- away from an edge every arm is exactly +/- sat_hi, measured at 98.85 % of
 * sub-steps -- and adds a correction over the few samples an edge spans. The
 * correction is
 *
 *     residual(t) = lowpass(E)(t) - S(t)
 *
 * where E is the PORT'S OWN edge and S is the flat step it replaces. It is
 * generated by RUNNING eb_dco_step, not by modelling the edge, so it cannot
 * drift from the oscillator it corrects.
 *
 * THE TABLE HAS NO PITCH DIMENSION. The edge's width in SAMPLES is
 * |pw-1|/(8*amp) -- inc cancels -- and that was MEASURED at 2.4290 output
 * samples across five octaves (edge_width.c). So one table serves every note,
 * and with the per-voice coefficient spread measured at exactly 0 it serves
 * every voice too.
 *
 * WHAT IT DOES NOT DO. It does not window the residual to zero at its ends.
 * A band-limited step's tail decays as 1/n, so truncating at 32 samples leaves
 * a step of about -30 dB at the join. Whether that matters is a MEASUREMENT
 * the gate makes, not a judgement made here; if it does, the fix is a longer
 * window or a taper, and both are one constant away.
 *
 * Emits a C header on stdout.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "eb_fork_config.h"
#include "eb_dco.h"
#include "eb_dco_wt.h"
#include "c6_realcoefs.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define OS        64          /* fine steps per OUTPUT sample when building */
#define HALF      (EB_WT_RES_LEN / 2)
/* THE BUILD PITCH must make the period MUCH longer than the residual window,
 * or a second edge falls inside it. At 0.01 the period is 50 output samples
 * and the 64-sample window always contained two edges -- the pulse residuals
 * came out with a full-height 1.70 spike at one end, which was the OTHER
 * edge's own step. At 0.0005 the period is 1,000 samples and each edge is
 * alone in its window.
 *
 * Choosing the pitch freely is legitimate BECAUSE the residual is
 * pitch-independent, measured at 2.4290 samples across five octaves. */
#define BUILD_INC 0.0005f

/* ARM SELECTOR, same convention as the row-6 probe. */
enum { ARM_SAW = 1, ARM_PULSE = 2, ARM_SUB = 3 };

static void fill(eb_dco_coef *c, float inc4, float pw, int arm)
{
    memset(c, 0, sizeof *c);
    c->inc = inc4;
    c->g = 0.00390625f / inc4;
    c->pw = pw; c->pwm1 = pw - 1.0f; c->pwp1 = pw + 1.0f;
#if EB_DCO_RECIP
    c->rm1 = 1.0f / c->pwm1; c->rp1 = 1.0f / c->pwp1;
#endif
    /* LEVEL 1, NOT THE PATCH'S. The residual is a SHAPE; the tick multiplies
     * by the recalled level itself. Using the patch's level here made the saw
     * and sub tables come out ALL ZERO, because patch 32 has DCO SUB LEVEL
     * exactly 0.0f -- a table generator that silently emits zeros because its
     * source patch happens not to use that arm is the kind of vacuous output
     * this project has been caught by before. */
    c->lvl_saw   = (arm == ARM_SAW)   ? 1.0f : 0.0f;
    c->lvl_pulse = (arm == ARM_PULSE) ? 1.0f : 0.0f;
    c->lvl_sub   = (arm == ARM_SUB)   ? 1.0f : 0.0f;
    c->gn_saw = RC_gn_saw;   c->gn_pulse = RC_gn_pulse;   c->gn_sub = RC_gn_sub;
    c->amp_saw = RC_amp_saw; c->amp_pulse = RC_amp_pulse; c->amp_sub = RC_amp_sub;
    c->sat_in = RC_sat_in;   c->subthr = RC_subthr;
    c->k3=RC_k3; c->k5=RC_k5; c->k7=RC_k7; c->k9=RC_k9; c->k11=RC_k11;
    { float x=c->sat_in,x2=x*x,x3=x*x2,x5=x3*x2,x7=x5*x2,x9=x7*x2,x11=x9*x2;
      c->sat_hi = x + x3*c->k3 + x5*c->k5 + x7*c->k7 + x9*c->k9 + x11*c->k11; }
    { float x=-c->sat_in,x2=x*x,x3=x*x2,x5=x3*x2,x7=x5*x2,x9=x7*x2,x11=x9*x2;
      c->sat_lo = x + x3*c->k3 + x5*c->k5 + x7*c->k7 + x9*c->k9 + x11*c->k11; }
#if EB_DCO_PULSEFAST
    eb_dco_set_edge_thresholds(c);
#endif
}

/* Run one full period at OS x the output rate and return the fine trace plus
 * the fine index of the requested edge. `which` picks WHICH crossing: 0 = the
 * phase wrap (saw, and the pulse's fixed edge), 1 = t crossing zero (the
 * pulse's moving edge), 2 = the sub's own crossing. */
static float *trace(float pw, int arm, int which, long *n_out, long *edge_out,
                    float **naive_out, double *height_out,
                    eb_dco_coef *coef_out, double *sub_out, float *phedge,
                    float *uedge)
{
    eb_dco_coef c; eb_dco_state s;
    double sub = (double)BUILD_INC * 4.0 / OS;
    /* THE TRACE MUST OUTLAST THE WINDOW ON BOTH SIDES. The residual spans
     * EB_WT_RES_LEN output samples and the reconstruction filter reaches 16
     * more, so an edge needs about 48 output samples of trace either side of
     * it. The first version ran ONE period -- 54 output samples in total --
     * so most of the window fell off the end of the array, the low-pass
     * returned its midpoint, and every residual came out at a flat 0.5
     * instead of decaying to zero. A residual that does not go to zero at its
     * ends is the one thing this table cannot be. */
    long span = (long)((EB_WT_RES_LEN / 2 + 24) * OS);
    long period = (long)(2.0 / sub);
    long n = period * 3 + 2 * span, i, edge = -1, want = n / 2;
    float *v = (float *)malloc(sizeof(float) * (size_t)n);
    /* THE NAIVE TRACE, which is the reference the residual is measured
     * against -- and getting this wrong was the whole of the first two
     * failures. The residual is
     *
     *     lowpass(E)(t) - NAIVE(t)
     *
     * where NAIVE is exactly what eb_dco_wt_tick computes: the arm's flat
     * value with no band-limiting. Subtracting a flat +/-1 STEP instead is
     * only right for a square; the SAW is a RAMP, so its residual came out at
     * a constant 0.5 because the ramp it should have followed was missing. */
    float *nv = (float *)malloc(sizeof(float) * (size_t)n);
    float *phtrace = (float *)malloc(sizeof(float) * (size_t)n);
    /* THE SUB'S OWN RAMP, recorded rather than recomputed. Its argument u
     * depends on the divide-by-two COUNTER, which toggles at the very edge
     * being tabulated, so reconstructing it from the phase alone gets the
     * wrong side of the toggle for half the window. */
    float *utrace = (float *)malloc(sizeof(float) * (size_t)n);
    float pprev;
    memset(&s, 0, sizeof s);
    fill(&c, BUILD_INC, pw, arm);
    c.inc = (float)sub;
    /* start well before the edge so the window has room on both sides */
    pprev = s.phase;
    for (i = 0; i < n; ++i) {
        float pnow, t, u;
        float uprev = (i > 0) ? utrace[i - 1] : 0.0f;
        v[i] = eb_dco_step(&s, &c);
        pnow = s.phase;
        t = c.pw + pnow;
        u = (((s.subcnt + pnow) + 1.0f) * 0.5f) - 1.0f;
        phtrace[i] = pnow; utrace[i] = u;
        nv[i] = (arm == ARM_SAW)
              ? (pnow * c.gn_saw) * c.sat_hi * c.lvl_saw
              : (arm == ARM_PULSE)
              ? (t < 0.0f ? -c.gn_pulse : c.gn_pulse)
                * c.sat_hi * c.lvl_pulse
              : (u < 0.0f ? -c.gn_sub : c.gn_sub) * c.sat_hi * c.lvl_sub;
        /* the edge nearest the MIDDLE of the trace, so the window has room
         * on both sides whatever the period turns out to be */
        if (edge < 0 && i > want) {
            if (which == 0 && pnow < pprev) edge = i;
            if (which == 1 && ((pw + pprev) < 0.0f) != ((pw + pnow) < 0.0f))
                edge = i;
            /* THE SUB'S EDGE IS WHERE ITS OWN RAMP CROSSES ZERO, not where
             * the counter is non-zero. The first version tested the counter,
             * which is non-zero for a whole half-period, so it picked an
             * arbitrary flat point and the residual came out all zeros --
             * indistinguishable from a table that simply was not built. */
            if (which == 2 && (uprev < 0.0f) != (u < 0.0f)) edge = i;
        }
        pprev = pnow;
    }
    *n_out = n; *edge_out = edge; *naive_out = nv;
    *coef_out = c; *sub_out = sub;
    *phedge = (edge > 0 && edge < n) ? phtrace[edge] : 0.0f;
    *uedge  = (edge > 0 && edge < n) ? utrace[edge]  : 0.0f;
    free(phtrace); free(utrace);
    /* THE STEP HEIGHT the tick will multiply the residual by. Measured from
     * the naive trace across the edge rather than assembled from constants,
     * so a sign convention cannot drift between here and eb_dco_wt.c. */
    *height_out = (edge > 0 && edge + 1 < n)
                ? (double)nv[edge + 1] - (double)nv[edge - 1] : 1.0;
    return v;
}

/* The ideal reconstruction low-pass at the OUTPUT Nyquist, applied in the fine
 * domain. Cutoff 1/(2*OS) of the fine rate; Blackman window, which trades a
 * wider transition for a much lower first sidelobe -- the sidelobe is what
 * would show up as ringing on every edge in the instrument. */
static double lp(const float *v, long n, double at)
{
    const int NT = 16 * OS;
    double acc = 0.0, wsum = 0.0;
    int k;
    for (k = -NT; k <= NT; ++k) {
        long idx = (long)floor(at) + k;
        double x = (double)k - (at - floor(at));
        double w, h;
        if (idx < 0 || idx >= n) continue;
        w = 0.42 - 0.5 * cos(2.0 * M_PI * (k + NT) / (2.0 * NT))
          + 0.08 * cos(4.0 * M_PI * (k + NT) / (2.0 * NT));
        h = (fabs(x) < 1e-12) ? 1.0 / OS
                              : sin(M_PI * x / OS) / (M_PI * x);
        acc += v[idx] * h * w; wsum += h * w;
    }
    return wsum > 1e-12 ? acc / wsum : 0.0;
}

/* THE NAIVE VALUE AT A FRACTIONAL TIME, computed rather than indexed.
 * Indexing the recorded trace at the nearest integer is wrong by a WHOLE STEP
 * whenever the target lands on the far side of an edge -- which it does for
 * exactly the samples that matter -- and that showed up as a 1.7 spike at one
 * end of every pulse residual. The phase is exactly linear between wraps, so
 * it can be reconstructed from the phase AT the edge and the fine increment. */
static double naive_at(const eb_dco_coef *c, int arm, double phe, double dsub,
                       double dt, double ue)
{
    double p = phe + dt * dsub, t, u;
    p = fmod(p + 1.0, 2.0); if (p < 0.0) p += 2.0; p -= 1.0;
    t = (double)c->pw + p;
    /* THE SUB'S SIGN, not its value. Its ramp is
     * u = ((cnt + p + 1)/2) - 1, which is zero exactly when cnt + p = 1 --
     * and with cnt in {0,2} that means p = +/-1, i.e. THE SUB'S CROSSING
     * COINCIDES WITH A PHASE WRAP. So a linear reconstruction of u is wrong on
     * one side of the very edge being tabulated, and it showed up as a
     * full-height step at one end of the residual.
     *
     * Only the SIGN of u reaches the output, and the build pitch is chosen so
     * that the period is far longer than the window -- so within the window
     * the sign flips exactly once, at dt = 0. */
    /* THE DIRECTION IS TAKEN FROM THE TRACE, not assumed. `ue` is u just
     * AFTER the crossing, so its sign says which way this edge goes. Assuming
     * a rising edge put the residual at a flat +/-1 on BOTH sides -- lp and
     * the reference simply had opposite signs everywhere. */
    u = ((dt < 0.0) ? -1.0 : 1.0) * ((ue < 0.0f) ? -1.0 : 1.0);
    if (arm == ARM_SAW)
        return (p * (double)c->gn_saw) * (double)c->sat_hi;
    if (arm == ARM_PULSE)
        return (t < 0.0 ? -(double)c->gn_pulse : (double)c->gn_pulse)
             * (double)c->sat_hi;
    return (u < 0.0 ? -(double)c->gn_sub : (double)c->gn_sub)
         * (double)c->sat_hi;
}

static void emit(const char *name, float pw, int arm, int which,
                 int slices, float lo, float hi)
{
    int sl, o, i;
    printf("static const float %s[%d][%d][%d] = {\n", name,
           slices ? slices : 1, EB_WT_RES_OVER, EB_WT_RES_LEN);
    for (sl = 0; sl < (slices ? slices : 1); ++sl) {
        float w = slices ? lo + (hi - lo) * (sl + 0.5f) / slices : pw;
        long n, e;
        float *nv;
        double height, dsub;
        eb_dco_coef cc;
        float phe, ue;
        float *v = trace(w, arm, which, &n, &e, &nv, &height, &cc, &dsub,
                         &phe, &ue);
        if (fabs(height) < 1e-12) height = 1.0;
        printf("  { /* pw %.4f */\n", w);
        for (o = 0; o < EB_WT_RES_OVER; ++o) {
            double frac = (double)o / EB_WT_RES_OVER;
            printf("    {");
            for (i = 0; i < EB_WT_RES_LEN; ++i) {
                double t = (double)e + ((double)(i - HALF) + frac) * OS;
                double nvi = naive_at(&cc, arm, (double)phe, dsub,
                                      t - (double)e, (double)ue);
                printf("%s%.9gf", i ? "," : "",
                       (lp(v, n, t) - nvi) / height);
            }
            printf("},\n");
        }
        printf("  },\n");
        free(v); free(nv);
    }
    printf("};\n\n");
}

int main(void)
{
    printf("/* GENERATED by tools/engineb/gen_wt_tables.c -- do not edit.\n"
           " * Residuals for eb_dco_wt.c, built by RUNNING eb_dco_step so they\n"
           " * cannot drift from the oscillator they correct. No pitch\n"
           " * dimension: the edge width in samples is |pw-1|/(8*amp) and inc\n"
           " * cancels, MEASURED at 2.4290 samples across five octaves. */\n");
    printf("#ifndef ENGINEB_EB_WT_TABLES_H\n#define ENGINEB_EB_WT_TABLES_H\n\n");
    emit("eb_wt_res_saw",     RC_pw, ARM_SAW,   0, 0, 0, 0);
    emit("eb_wt_res_sub",     RC_pw, ARM_SUB,   2, 0, 0, 0);
    emit("eb_wt_res_pulse_a", 0.0f,  ARM_PULSE, 1, EB_WT_PW_SLICES,
         EB_WT_PW_LO, EB_WT_PW_LO + EB_WT_PW_STEP * EB_WT_PW_SLICES);
    emit("eb_wt_res_pulse_b", 0.0f,  ARM_PULSE, 0, EB_WT_PWB_SLICES,
         EB_WT_PW_LO, EB_WT_PW_LO + EB_WT_PW_STEP * EB_WT_PW_SLICES);
    printf("#endif\n");
    return 0;
}
