# Recentered pitch table generator (F3). EXACT arithmetic end to end:
# the plugin's doubles -> Fractions -> binomial recentering -> one float
# rounding at the very end. No decimal round-trip anywhere.
import struct, sys
from fractions import Fraction
from math import comb

rows = [[None]*13 for _ in range(29)]
for line in open(sys.argv[1]):
    r, k, h = line.split()
    d = struct.unpack('>d', bytes.fromhex(h))[0]
    rows[int(r)][int(k)] = Fraction(d)   # exact: doubles are dyadic rationals

out = []
for r in range(29):
    a = rows[r]
    c = Fraction(2*r - 39, 2)           # center r - 19.5, exact
    # b_j = sum_{k>=j} C(k,j) a_k c^(k-j)
    b = []
    for j in range(13):
        s = Fraction(0)
        for k in range(j, 13):
            s += comb(k, j) * a[k] * c ** (k - j)
        b.append(s)
    out.append((c, b))

# SELF-CHECK 1 (exact identity): recentered poly == original poly as
# rationals at 11 rational sample points per row. This validates the
# transform itself, before any float enters.
for r in range(29):
    a = rows[r]; c, b = out[r]
    for num in range(-5, 6):
        x = c + Fraction(num, 10)
        pa = sum(a[k] * x**k for k in range(13))
        pb = sum(b[j] * (x - c)**j for j in range(13))
        assert pa == pb, (r, num)
print("SELF-CHECK: recentered == original, EXACT, 29 rows x 11 points")

def f32hex(fr):
    f = struct.unpack('>f', struct.pack('>f', float(fr)))[0]
    return f

L = ["/* eb_pitch_fork_tab.h -- GENERATED by gen_fork_tab.py. DO NOT EDIT.",
     " * Recentered per-row float coefficients for the S3 FORK pitch",
     " * evaluator. Derived EXACTLY (rational arithmetic) from the plugin's",
     " * own juno_pitch_table; the ONLY rounding is the final float cast,",
     " * emitted as C99 hex literals so there is no decimal round-trip.",
     " * Row r covers x in [r-20, r-19] (row 28 up to the 8.9 clamp);",
     " * evaluate at t = x - (r - 19.5), so |t| <= 0.5. */",
     "static const float eb_pitch_fork_tab[29][13] = {"]
for r in range(29):
    c, b = out[r]
    vals = ", ".join(float(f32hex(x)).hex() + "f" for x in b)
    L.append("    { %s }," % vals)
L.append("};")
open("engine_b/eb_pitch_fork_tab.h","w").write("\n".join(L) + "\n")
print("wrote engine_b/eb_pitch_fork_tab.h")
