#!/usr/bin/env python3
"""merge_shims.py — GENERATE the composite shims, so a whole-engine test exists.

WHY THIS FILE EXISTS (docs/engineb/HARNESS_AUDIT.md F1)
    A module shim replaces ONE port translation unit by file name. Six modules
    ship their own `voice_render.c` and three ship their own `master_render.c`,
    so `null_b.build()` used to overwrite one with the next and link only the
    last -- a composite build reported ten modules and contained two. That is
    now a hard build error, which stopped the lie but also removed the ability
    to test engine B AS A WHOLE ENGINE at all.

    This script restores it, by construction rather than by hand: it takes each
    individual shim's edit region and applies them all to one copy of the port
    file. The composite is GENERATED and is regenerated by `make engineb`, so it
    cannot drift away from the shims it is built from -- a hand-merged composite
    would drift the first time one module was touched, and nobody would notice
    until a gate went quietly green on stale code.

HOW IT DECIDES THE MERGE IS LEGITIMATE
    Each shim differs from the port in a small number of contiguous regions
    (MEASURED: env 964-1075, pwm_cv 1076-1128, vcf_cv 1150-1229, vcf_ladder
    1298-1514, vca_hpf 1516-1640, dco 1718-2136; chorus 2753-2937, delay
    1055-1264, reverb 2078-2337). They are disjoint, which is what makes a
    mechanical merge sound.

    That is CHECKED, not assumed. Two shims whose regions overlap cannot be
    merged this way and the script stops and names both. It does not attempt a
    resolution -- an automatic resolution of two edits to the same code is
    exactly the kind of quiet wrongness this audit exists to remove.

WHAT A GREEN COMPOSITE DOES AND DOES NOT PROVE
    It proves the modules work TOGETHER, which no per-module run can: a module
    that is only correct inside the port's surrounding code passes its own gate
    and fails here. It does NOT retire anything on its own -- `src/` is a proxy,
    and the authority is tools/engineb/plugin_check.py.

USAGE
    merge_shims.py            regenerate every composite, report what changed
    merge_shims.py --check    exit non-zero if a composite is stale (for CI)
"""
import sys, os, glob, difflib, argparse

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SHIM = os.path.join(REPO, "engine_b", "shim")

# ONE composite module, engine_b/shim/engine_all/, holding every shim file.
# Files that several modules provide are MERGED (below); files only one module
# provides are copied verbatim, so `--module engine_all` really is every module
# at once and not merely the colliding ones.
COMPOSITE = "engine_all"
MERGED = ("voice_render.c", "master_render.c")


def members(base):
    """Every module directory that ships a shim for this port file, except the
    generated composites themselves."""
    out = []
    for d in sorted(os.listdir(SHIM)):
        if d == COMPOSITE or not os.path.isdir(os.path.join(SHIM, d)):
            continue
        if os.path.exists(os.path.join(SHIM, d, base)):
            out.append(d)
    return out


def regions(port_lines, shim_lines):
    """Contiguous edit regions as (i1, i2, replacement_lines), port-line indexed.

    A shim's leading insert (its #include block, which difflib reports at line
    0) is returned separately so the composites can concatenate them instead of
    fighting over the same insertion point."""
    sm = difflib.SequenceMatcher(None, port_lines, shim_lines, autojunk=False)
    head, body = [], []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        if tag == "insert" and i1 == 0:
            head.extend(shim_lines[j1:j2])
            continue
        body.append((i1, i2, shim_lines[j1:j2]))
    return head, body


def build_one(name, base, verbose=True):
    port = open(os.path.join(REPO, "src", base)).read().split("\n")
    mods = members(base)
    if not mods:
        raise SystemExit("no member shims found for %s" % base)

    heads, edits, owner = [], [], {}
    for m in mods:
        h, b = regions(port, open(os.path.join(SHIM, m, base)).read().split("\n"))
        heads.append((m, h))
        for i1, i2, rep in b:
            # OVERLAP CHECK. Two modules editing the same port lines cannot be
            # merged mechanically and must not be merged by guesswork.
            for om, (oi1, oi2) in owner.items():
                if i1 < oi2 and oi1 < i2:
                    raise SystemExit(
                        "OVERLAPPING SHIMS: '%s' edits %s lines %d-%d and '%s' "
                        "edits %d-%d.\n  These regions overlap, so a mechanical "
                        "merge would have to choose between two edits to the "
                        "same code.\n  WHAT TO DO: rework one shim so the two "
                        "regions are disjoint, or write the composite by hand "
                        "AND gate it.\n  Do not resolve this automatically."
                        % (om, base, oi1 + 1, oi2, m, i1 + 1, i2))
            owner[m] = (i1, i2)
            edits.append((i1, i2, rep, m))

    out = list(port)
    for i1, i2, rep, m in sorted(edits, key=lambda e: -e[0]):   # bottom-up
        out[i1:i2] = rep

    banner = [
        "/* GENERATED FILE -- DO NOT EDIT.",
        " * tools/engineb/merge_shims.py built this from the individual shims:",
        " *     " + ", ".join(mods),
        " * Edit those, then re-run the generator (make engineb does it).",
        " * Its purpose: engine B cannot be tested as a WHOLE ENGINE while each",
        " * module shadows the same port file -- see docs/engineb/HARNESS_AUDIT.md",
        " * finding F1, where a composite build silently linked 2 modules of 10.",
        " */",
    ]
    for m, h in heads:
        if h:
            banner.append("/* ---- from shim '%s' ---- */" % m)
            banner.extend(h)

    dst_dir = os.path.join(SHIM, COMPOSITE)
    os.makedirs(dst_dir, exist_ok=True)
    text = "\n".join(banner + out)
    dst = os.path.join(dst_dir, base)
    old = open(dst).read() if os.path.exists(dst) else None
    if verbose:
        print("  %-12s <- %s  (%d edit regions, %d lines)"
              % (name, ",".join(mods), len(edits), len(out)))
    return dst, text, old


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="do not write; fail if any composite is stale")
    a = ap.parse_args()
    import shutil
    stale = []
    print("regenerating engine_b/shim/%s from its members:" % COMPOSITE)
    for base in MERGED:
        dst, text, old = build_one(COMPOSITE, base)
        if old != text:
            stale.append(base)
            if not a.check:
                open(dst, "w").write(text)
    # Files only one module provides are not merged, only carried across --
    # otherwise `--module engine_all` would silently omit them.
    seen = {}
    for d in sorted(os.listdir(SHIM)):
        if d == COMPOSITE or not os.path.isdir(os.path.join(SHIM, d)):
            continue
        for f in sorted(glob.glob(os.path.join(SHIM, d, "*.c"))):
            b = os.path.basename(f)
            if b in MERGED:
                continue
            if b in seen:
                raise SystemExit(
                    "UNMERGED COLLISION: '%s' and '%s' both provide %s, which "
                    "is not in MERGED.\n  WHAT TO DO: add %s to MERGED so the "
                    "generator merges it, or rename one shim."
                    % (seen[b], d, b, b))
            seen[b] = d
            dst = os.path.join(SHIM, COMPOSITE, b)
            text = open(f).read()
            old = open(dst).read() if os.path.exists(dst) else None
            print("  %-16s <- %s (carried verbatim)" % (b, d))
            if old != text:
                stale.append(b)
                if not a.check:
                    open(dst, "w").write(text)
    if a.check and stale:
        raise SystemExit(
            "STALE COMPOSITE SHIM(S): %s\n"
            "  A member shim changed and the composite was not regenerated, so "
            "a whole-engine run would be testing OLD code.\n"
            "  WHAT TO DO: run tools/engineb/merge_shims.py and commit the "
            "result." % ", ".join(sorted(set(stale))))
    print("  %s" % ("up to date" if not stale else
                    "rewrote: " + ", ".join(sorted(set(stale)))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
