/* c6_halfband.h -- GENERATED by tools/engineb/gen_c6_halfband.py.
 * 2x anti-alias decimator for the half-oversampling probe (F5).
 * 31 taps at 88.2 kHz; design goal: match the port cascade's
 * in-band response to 18 kHz, stopband over the fold sources.
 * The MEASURED consequence of using it is the probe's table, not
 * this comment. */
#define C6_HB_TAPS 31
static const float c6_halfband[C6_HB_TAPS] = {
    -0x1.458cfc0000000p-16f,
    0x1.f047920000000p-64f,
    0x1.96cf0a0000000p-12f,
    -0x1.9a655c0000000p-61f,
    -0x1.03e9a80000000p-9f,
    0x1.52a58e0000000p-59f,
    0x1.ae15fa0000000p-8f,
    -0x1.87d6e20000000p-58f,
    -0x1.188fd60000000p-6f,
    0x1.62d48a0000000p-57f,
    0x1.41508a0000000p-5f,
    -0x1.0887b40000000p-56f,
    -0x1.6e2c260000000p-4f,
    0x1.4d50920000000p-56f,
    0x1.3fd9c40000000p-2f,
    0x1.fffe200000000p-2f,
    0x1.3fd9c40000000p-2f,
    0x1.4d50920000000p-56f,
    -0x1.6e2c260000000p-4f,
    -0x1.0887b40000000p-56f,
    0x1.41508a0000000p-5f,
    0x1.62d48a0000000p-57f,
    -0x1.188fd60000000p-6f,
    -0x1.87d6e20000000p-58f,
    0x1.ae15fa0000000p-8f,
    0x1.52a58e0000000p-59f,
    -0x1.03e9a80000000p-9f,
    -0x1.9a655c0000000p-61f,
    0x1.96cf0a0000000p-12f,
    0x1.f047920000000p-64f,
    -0x1.458cfc0000000p-16f,
};
