/* eb_delay_ref.c -- LITERAL transcription of the DELAY TYPE 0/1 block of
 * src/master_render.c (lines 1055-1261), extracted verbatim so it can be
 * null-tested against the sealed engine. Generated by scratchpad/engineb.  */
#include <math.h>
#include <stdint.h>
typedef int32_t _DWORD;
void eb_delay_ref(unsigned char *a1, float v36, float v38)
{
  float v5 = *(float *)(a1 + 84496);
  int v323,v324,v332,v334,v336,v340,v344,v378,v379,v416,v417;
  float v325,v326,v327,v328,v329,v330,v331,v333,v335,v337,v338,v339,v341,v342,v343,
        v345,v346,v347,v348,v349,v350,v351,v352,v353,v354,v355,v356,v357,v358,v359,
        v360,v361,v362,v363,v364,v365,v366,v367,v368,v369,v370,v371,v372,v373,v374,
        v375,v376,v377,v380,v381,v382,v383,v384,v385,v386,v387,v388,v389,v390,v391,
        v392,v393,v394,v395,v396,v397,v398,v399,v400,v401,v402,v403,v404,v405,v406,
        v407,v408,v409,v410,v411,v412,v413,v414,v415;
if ( *(_DWORD *)(a1 + 11022348) )
{
  v323 = 0;
  v324 = 0;
}
else
{
  v323 = *(_DWORD *)(a1 + 102288);
  v324 = *(_DWORD *)(a1 + 102272);
}
v325 = *(float *)(a1 + 101792);
v326 = *(float *)(a1 + 102080);
v327 = *(float *)(a1 + 102096);
v328 = *(float *)(a1 + 101808);
v329 = *(float *)(a1 + 102048);
v330 = *(float *)(a1 + 102064) * *(float *)(a1 + 102400);
v331 = *(float *)(a1 + 101872);
*(_DWORD *)(a1 + 101904) = *(_DWORD *)(a1 + 101888);
*(_DWORD *)(a1 + 101872) = *(_DWORD *)(a1 + 101856);
*(_DWORD *)(a1 + 101856) = *(_DWORD *)(a1 + 101840);
*(_DWORD *)(a1 + 101840) = *(_DWORD *)(a1 + 101824);
*(_DWORD *)(a1 + 102032) = *(_DWORD *)(a1 + 102016);
*(_DWORD *)(a1 + 102016) = *(_DWORD *)(a1 + 102000);
*(_DWORD *)(a1 + 102000) = *(_DWORD *)(a1 + 101984);
*(_DWORD *)(a1 + 101984) = *(_DWORD *)(a1 + 101968);
*(_DWORD *)(a1 + 101968) = *(_DWORD *)(a1 + 101952);
*(_DWORD *)(a1 + 101952) = *(_DWORD *)(a1 + 101936);
*(_DWORD *)(a1 + 101936) = *(_DWORD *)(a1 + 101920);
*(_DWORD *)(a1 + 102192) = *(_DWORD *)(a1 + 102176);
v332 = *(_DWORD *)(a1 + 102160);
*(_DWORD *)(a1 + 102304) = v323;
v333 = v36 * *(float *)(a1 + 102368);
*(_DWORD *)(a1 + 102176) = v332;
v334 = *(_DWORD *)(a1 + 102144);
*(float *)(a1 + 102064) = v329;
v335 = v329 * *(float *)(a1 + 102384);
*(_DWORD *)(a1 + 102160) = v334;
v336 = *(_DWORD *)(a1 + 102128);
*(float *)(a1 + 102112) = v327;
v337 = v327 * *(float *)(a1 + 102432);
v338 = v335 + v333;
*(_DWORD *)(a1 + 102144) = v336;
v339 = v325 * *(float *)(a1 + 102480);
*(_DWORD *)(a1 + 102256) = *(_DWORD *)(a1 + 102240);
v340 = *(_DWORD *)(a1 + 102224);
v341 = v338 + v330;
*(float *)(a1 + 102096) = v326;
v342 = v326 * *(float *)(a1 + 102416);
v343 = v36 - v339;
*(_DWORD *)(a1 + 102240) = v340;
v344 = *(_DWORD *)(a1 + 102208);
v345 = *(float *)(a1 + 102448);
*(float *)(a1 + 101888) = v331;
*(float *)(a1 + 101824) = v328;
*(_DWORD *)(a1 + 102288) = v324;
*(float *)(a1 + 101760) = v36;
*(float *)(a1 + 101776) = v38;
v346 = (float)(v341 + v342) + v337;
*(float *)(a1 + 102048) = v36;
v347 = *(float *)(a1 + 102464);
v348 = (float)(v343 - v328) * v347;
*(_DWORD *)(a1 + 11022348) = 0;
*(_DWORD *)(a1 + 102224) = v344;
*(float *)(a1 + 102080) = v346;
v349 = (float)(v347 * v325) + v328;
*(float *)(a1 + 101792) = v348 + v325;
v350 = *(float *)(a1 + 102496);
*(float *)(a1 + 101808) = v349;
*(float *)(a1 + 4297136) = (float)((float)((float)((float)((float)((float)((float)(1.0 - v345) * v349)
                                                                 + (float)(v345 * v346))
                                                         * v350)
                                                 + (float)((float)(1.0 - v350) * v36))
                                         * *(float *)(a1 + 102576))
                                 + (float)(v331 * *(float *)(a1 + 102560)))
                         * *(float *)(a1 + 102592);
v351 = *(float *)(a1 + 101936);
v352 = *(float *)(a1 + 101776);
v353 = *(float *)(a1 + 102160) * *(float *)(a1 + 102400);
v354 = *(float *)(a1 + 101952);
v355 = *(float *)(a1 + 102464);
v356 = (float)(*(float *)(a1 + 102144) * *(float *)(a1 + 102384)) + (float)(v352 * *(float *)(a1 + 102368));
*(float *)(a1 + 102128) = v352;
v357 = (float)((float)(v356 + v353) + (float)(*(float *)(a1 + 102416) * *(float *)(a1 + 102176)))
     + (float)(*(float *)(a1 + 102432) * *(float *)(a1 + 102192));
v358 = v352 - (float)(v351 * *(float *)(a1 + 102480));
v359 = *(float *)(a1 + 102448);
*(float *)(a1 + 102160) = v357;
v360 = (float)(v358 - v354) * v355;
v361 = (float)(v355 * v351) + v354;
*(float *)(a1 + 101920) = v360 + v351;
v362 = *(float *)(a1 + 102496);
*(float *)(a1 + 101936) = v361;
*(float *)(a1 + 4297168) = (float)((float)((float)((float)((float)((float)((float)(1.0 - v359) * v361)
                                                                 + (float)(v359 * v357))
                                                         * v362)
                                                 + (float)((float)(1.0 - v362) * v352))
                                         * *(float *)(a1 + 102576))
                                 + (float)(*(float *)(a1 + 102560) * *(float *)(a1 + 102016)))
                         * *(float *)(a1 + 102592);
v363 = *(float *)(a1 + 102256);
v364 = *(float *)(a1 + 102304);
v365 = (float)(*(float *)(a1 + 102720) + *(float *)(a1 + 102288)) * v5;
*(float *)(a1 + 102272) = v365;
if ( (float)(v365 - v363) >= 0.0 )
  v366 = *(float *)(a1 + 102752);
else
  v366 = *(float *)(a1 + 102768);
v367 = *(float *)(a1 + 102352);
v368 = v364 + v366;
v369 = *(float *)(a1 + 102240);
v370 = v367 - *(float *)(a1 + 102224);
*(float *)(a1 + 102208) = v367;
v371 = v367 - v363;
if ( v370 != 0.0 )
  v369 = v367 - v363;
*(float *)(a1 + 102224) = v369;
v372 = fabs(v369) * *(float *)(a1 + 102784);
v373 = v363 + v372;
v374 = fmaxf(v363 - v372, v367);
if ( v371 > 0.0 )
  v374 = fminf(v373, v367);
*(float *)(a1 + 102240) = v374;
if ( v368 <= 0.0 )
  v375 = 0.0;
else
  v375 = v368;
v376 = v375;
if ( v376 >= -1.0 )
  v377 = fminf(v376, 1.0);
else
  v377 = -1.0;
v378 = *(_DWORD *)(a1 + 2199952);
*(float *)(a1 + 102288) = v377 * *(float *)(a1 + 102592);
v379 = (int)(float)(v374 * -16384.0);
*(_DWORD *)(a1 + 4297152) = *(_DWORD *)(a1 + 4 * ((*(int *)(a1 + 2199956) - 1LL) & (v378 - v379 + 1LL)) + 102800);
*(_DWORD *)(a1 + 4297156) = *(_DWORD *)(a1
                                      + 4
                                      * ((*(int *)(a1 + 2199956) - 1LL) & (*(_DWORD *)(a1 + 2199952) - v379 + 2LL))
                                      + 102800);
v380 = (float)(v374 * 16384.0) - (double)(int)(float)(v374 * 16384.0);
*(float *)(a1 + 4297160) = v380;
v381 = *(float *)(a1 + 4297152);
*(_DWORD *)(a1 + 4297184) = *(_DWORD *)(a1
                                      + 4
                                      * ((*(int *)(a1 + 4297124) - 1LL) & (*(_DWORD *)(a1 + 4297120) - v379 + 1LL))
                                      + 2199968);
*(_DWORD *)(a1 + 4297188) = *(_DWORD *)(a1
                                      + 4
                                      * ((*(int *)(a1 + 4297124) - 1LL) & (*(_DWORD *)(a1 + 4297120) - v379 + 2LL))
                                      + 2199968);
*(float *)(a1 + 4297192) = v380;
v382 = *(float *)(a1 + 101872);
v383 = *(float *)(a1 + 101904);
v384 = *(float *)(a1 + 101856);
v385 = (float)((float)((float)(v380 * *(float *)(a1 + 4297156)) - (float)(v380 * v381)) + v381)
     * *(float *)(a1 + 102304);
*(float *)(a1 + 101824) = v385;
v386 = *(float *)(a1 + 4297184);
v387 = *(float *)(a1 + 102624) * (float)(v385 - v384);
v388 = (float)((float)(v385 - v384) * *(float *)(a1 + 102608)) + v384;
v389 = *(float *)(a1 + 102640) * v388;
*(float *)(a1 + 101840) = v388;
v390 = *(float *)(a1 + 102688);
v391 = v387 - v389;
v392 = *(float *)(a1 + 102672);
v393 = v391 - v382;
v394 = (float)(v393 * *(float *)(a1 + 102656)) + v382;
v395 = *(float *)(a1 + 102000);
v396 = *(float *)(a1 + 101776);
*(float *)(a1 + 101856) = v394;
v397 = (float)(v390 * v394) - (float)(v392 * v393);
v398 = *(float *)(a1 + 101984);
v399 = v397 - v383;
*(float *)(a1 + 101872) = v399;
v400 = (float)(v399 * *(float *)(a1 + 102704)) + v383;
v401 = *(float *)(a1 + 102032);
*(float *)(a1 + 101888) = v400;
v402 = (float)((float)((float)(v380 * *(float *)(a1 + 4297188)) - (float)(v380 * v386)) + v386)
     * *(float *)(a1 + 102304);
*(float *)(a1 + 101952) = v402;
v403 = *(float *)(a1 + 102624) * (float)(v402 - v398);
v404 = (float)((float)(v402 - v398) * *(float *)(a1 + 102608)) + v398;
v405 = *(float *)(a1 + 102640);
*(float *)(a1 + 101968) = v404;
v406 = *(float *)(a1 + 102688);
v407 = (float)(v403 - (float)(v405 * v404)) - v395;
v408 = *(float *)(a1 + 102672) * v407;
v409 = v407 * *(float *)(a1 + 102656);
v410 = *(float *)(a1 + 102576);
v411 = v409 + v395;
*(float *)(a1 + 101984) = v411;
v412 = (float)((float)(v406 * v411) - v408) - v401;
*(float *)(a1 + 102000) = v412;
v413 = *(float *)(a1 + 102528);
*(float *)(a1 + 102016) = (float)(v412 * *(float *)(a1 + 102704)) + v401;
v414 = (float)((float)(v410 * (float)(*(float *)(a1 + 102512) * *(float *)(a1 + 101760)))
             + (float)((float)(1.0 - v410) * *(float *)(a1 + 101760)))
     + (float)(v385 * v413);
v415 = (float)((float)(v410 * (float)(*(float *)(a1 + 102512) * v396)) + (float)((float)(1.0 - v410) * v396))
     + (float)(v402 * v413);
*(float *)(a1 + 102320) = v414;
*(float *)(a1 + 102336) = v415;
v416 = (*(_DWORD *)(a1 + 2199952) - 1) & (*(_DWORD *)(a1 + 2199956) - 1);
*(_DWORD *)(a1 + 2199952) = v416;
*(_DWORD *)(a1 + 4LL * v416 + 102800) = *(_DWORD *)(a1 + 4297136);
v417 = (*(_DWORD *)(a1 + 4297120) - 1) & (*(_DWORD *)(a1 + 4297124) - 1);
*(_DWORD *)(a1 + 4297120) = v417;
*(_DWORD *)(a1 + 4LL * v417 + 2199968) = *(_DWORD *)(a1 + 4297168);
}
