/* generated by tools/build_sqarpg_apply.py — SQ Dynamic ARPG faithful apply set.
 * {engine_offset, tableId, step} from Script.xml binding + bank decode. */
static const struct { int off; int tid; int step; } SQARPG_APPLY[] = {
  {  1920,  44,   0},  /* DB751 LFO DELAY TIME */
  {  1088,  22,  63},  /* DB752 LFO RATE */
  {  4032,   0, 128},  /* DB753 DCO LFO MOD */
  {  4144,  45,   0},  /* DB758 DCO PWM DEPTH */
  {  3840,   5,   3},  /* DB760 DCO RANGE */
  {  4192,  54, 255},  /* DB771 DCO SAW LEVEL */
  {  4224,  54, 159},  /* DB772 DCO SUB LEVEL */
  {  6528,  12,   0},  /* DB773 DCO NOISE LEVEL */
  {  6736,  22,  90},  /* DB779 VCF CUTOFF FREQ */
  {  6832,  22,   0},  /* DB781 VCF RESONANCE */
  { 10240,  41,   0},  /* DB782 HPF CUTOFF FREQ */
  {  7392,  46, 190},  /* DB783 VCF ENV MOD */
  {  2784,  35,   0},  /* DB784 ENV1 ATTACK */
  {  2816,  38,  64},  /* DB785 ENV1 DECAY */
  {  2800,  50, 194},  /* DB786 ENV1 SUSTAIN */
  {  2832,  38,  94},  /* DB787 ENV1 RELEASE */
  {  7408,  24, 255},  /* DB788 VCF KEY FOLLOW */
  {  3264,  35,   0},  /* DB789 ENV2 ATTACK */
  {  3296,  38, 178},  /* DB790 ENV2 DECAY */
  {  3280,  50,   0},  /* DB791 ENV2 SUSTAIN */
  {  3312,  38,  48},  /* DB792 ENV2 RELEASE */
  {  4128,  21,  11},  /* DB801 BEND RANGE */
};
#define SQARPG_APPLY_N 22
