/* test_teensy_golden.c — replay the standalone 44.1 kHz golden corpus and verify
 * each scenario's output hash. Runs on the host (proving the golden matches the
 * current build — a regression guard) and compiles for the Teensy 4.1 (proving
 * the ARM build reproduces the x86 reference, hence the plugin, bit-for-bit).
 *
 * The corpus (tests/teensy_golden.h, generated by tools/verify/gen_teensy_golden.py)
 * embeds each patch blob + note events + the expected FNV-1a-64 hash of the port's
 * stereo float output. This driver reconstructs a minimal 1-patch bank from the
 * embedded blob, applies it, replays the events at their sample offsets, hashes the
 * rendered bytes, and compares. Self-contained: no bank file needed on the target.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "teensy_golden.h"

/* Public engine API (gui/juno_bridge.c). Opaque context. */
typedef struct juno_ctx juno_ctx;
juno_ctx *juno_gui_create(float sample_rate, int chorus_mode);
int  juno_gui_apply_bank(juno_ctx *c, const unsigned char *bank, int len, int idx);
void juno_gui_note_on(juno_ctx *c, int midi_note, int velocity);
void juno_gui_note_off(juno_ctx *c, int midi_note);
int  juno_gui_render(juno_ctx *c, float *out, int nframes);

/* Bank layout (tools/verify/e2e_emu.py: HEADER=23, STRIDE=20223, BLOB_OFF=16). */
#define BK_HEADER 23
#define BK_STRIDE 20223
#define BK_BLOB   16

static uint64_t fnv_init(void) { return 0xcbf29ce484222325ULL; }
static uint64_t fnv_bytes(uint64_t h, const unsigned char *p, int n)
{
    int i;
    for (i = 0; i < n; ++i) { h ^= p[i]; h *= 0x100000001b3ULL; }
    return h;
}

/* Render `n` frames and fold their raw bytes into the running hash. */
static uint64_t render_hash(juno_ctx *c, uint64_t h, int n)
{
    float *buf = (float *)malloc(sizeof(float) * 2 * n);
    if (!buf) { fprintf(stderr, "OOM\n"); exit(2); }
    juno_gui_render(c, buf, n);
    h = fnv_bytes(h, (const unsigned char *)buf, (int)(sizeof(float) * 2 * n));
    free(buf);
    return h;
}

static int run_scenario(const tg_scenario *s)
{
    /* minimal 1-patch bank: sentinel 'K' + the embedded TG_BLOB_LEN-byte record
     * prefix. Must copy the FULL embedded blob: the per-patch DELAY FEEDBACK /
     * DIRECT LEVEL bytes live at record 3057/3060, and the old hardcoded 704-byte
     * copy silently zeroed them (invisible while feedback was a constant; exposed
     * the moment the per-patch law landed). */
    unsigned char *bank = (unsigned char *)calloc(1, BK_HEADER + BK_STRIDE);
    if (!bank) return 2;
    bank[0] = 'K';
    memcpy(bank + BK_HEADER + BK_BLOB, s->blob, TG_BLOB_LEN);

    juno_ctx *c = juno_gui_create(TG_RATE, 0);
    juno_gui_apply_bank(c, bank, BK_HEADER + BK_STRIDE, 0);

    uint64_t h = fnv_init();
    int cur = 0, i;
    for (i = 0; i < s->nev; ++i) {
        const tg_event *e = &s->ev[i];
        if (e->at > cur) { h = render_hash(c, h, e->at - cur); cur = e->at; }
        if (e->kind == 1) juno_gui_note_on(c, e->note, e->vel);
        else              juno_gui_note_off(c, e->note);
    }
    if (s->nframes > cur) h = render_hash(c, h, s->nframes - cur);

    free(bank);
    if (h != s->hash) {
        printf("FAIL: %-14s patch %2d  got %016llx  want %016llx\n",
               s->name, s->patch, (unsigned long long)h, (unsigned long long)s->hash);
        return 1;
    }
    printf("OK:   %-14s patch %2d  hash %016llx\n",
           s->name, s->patch, (unsigned long long)h);
    return 0;
}

int main(void)
{
    int i, bad = 0;
    for (i = 0; i < TG_NSCEN; ++i) bad += run_scenario(&tg_scenarios[i]);
    if (bad) { printf("FAIL: %d/%d golden scenarios diverged\n", bad, TG_NSCEN); return 1; }
    printf("ALL OK: %d/%d Teensy golden scenarios bit-exact\n", TG_NSCEN, TG_NSCEN);
    return 0;
}
