/* test_arp_pattern.c — guard for the arp SCATTER STEP×SLOT pattern-grid engine
 * (carp_set_scatter + the per-slot step loop in carp_tick). The golden event
 * vectors are emitted by scratchpad/oracle/gen_arp_golden.py from the reference
 * model that was verified 330/330 bit-exact against the plugin's OWN code under
 * Unicorn (scratchpad/oracle/{verify_grid,sweep_all}.py,
 * scratchpad/oracle/arp_pattern_grid_spec.md). This checks the C port reproduces
 * the exact note-on/off stream (pitch, final velocity, order) for a spread of
 * patterns: the default 1-note path, a 4-slot chord (voice steal/skip), a pattern
 * with a <127 grid velocity, a dense 10-slot pattern with octave range, and a DOWN
 * selector across octaves. No PE / emulator needed at test time.
 */
#include <stdio.h>
#include "../src/carp.h"

typedef struct { int note, vel; } arp_held;
typedef struct { int kind, note, vel; } arp_ev;

/* GENERATED by scratchpad/oracle/gen_arp_golden.py from the verified 330/330
 * reference model (StepEngine/build_runtime). Each row: {kind,note,vel}. */

/* default_1note: selType=0 slab=0 sub=7 depth=0 rate=4 range=0 held=[(60, 100)] nticks=40 -> 13 events */
static const int G_default_1note_sel=0, G_default_1note_type=0, G_default_1note_depth=0, G_default_1note_range=0;
static const arp_held G_default_1note_held[] = { {60,100} };
static const int G_default_1note_nheld = 1;
static const arp_ev G_default_1note_ev[] = {
  {1,60,100},{0,60,64},{1,60,100},{0,60,64},{1,60,100},{0,60,64},{1,60,100},{0,60,64},
  {1,60,100},{0,60,64},{1,60,100},{0,60,64},{1,60,100},
};
static const int G_default_1note_nev = 13;

/* chord4_slab7sub10: selType=0 slab=7 sub=10 depth=3 rate=4 range=0 held=[(60, 100), (64, 110), (67, 120), (72, 90)] nticks=60 -> 31 events */
static const int G_chord4_slab7sub10_sel=0, G_chord4_slab7sub10_type=7, G_chord4_slab7sub10_depth=3, G_chord4_slab7sub10_range=0;
static const arp_held G_chord4_slab7sub10_held[] = { {60,100},{64,110},{67,120},{72,90} };
static const int G_chord4_slab7sub10_nheld = 4;
static const arp_ev G_chord4_slab7sub10_ev[] = {
  {1,60,100},{0,60,64},{1,64,110},{1,67,120},{1,72,90},{0,64,64},{0,67,64},{0,72,64},
  {1,60,76},{0,60,64},{1,64,110},{1,67,120},{1,72,90},{0,64,64},{0,67,64},{0,72,64},
  {1,60,100},{0,60,64},{1,64,110},{1,67,120},{1,72,89},{0,64,64},{0,67,64},{0,72,64},
  {1,60,88},{0,60,64},{1,64,110},{0,64,64},{1,67,120},{1,72,90},{1,60,100},
};
static const int G_chord4_slab7sub10_nev = 31;

/* vel71_slab1sub3: selType=0 slab=1 sub=3 depth=-4 rate=4 range=0 held=[(60, 100), (67, 120)] nticks=60 -> 13 events */
static const int G_vel71_slab1sub3_sel=0, G_vel71_slab1sub3_type=1, G_vel71_slab1sub3_depth=-4, G_vel71_slab1sub3_range=0;
static const arp_held G_vel71_slab1sub3_held[] = { {60,100},{67,120} };
static const int G_vel71_slab1sub3_nheld = 2;
static const arp_ev G_vel71_slab1sub3_ev[] = {
  {1,60,100},{0,60,64},{1,67,120},{0,67,64},{1,60,100},{0,60,64},{1,67,67},{0,67,64},
  {1,60,100},{0,60,64},{1,67,120},{0,67,64},{1,60,100},
};
static const int G_vel71_slab1sub3_nev = 13;

/* dense_slab6sub2_r1: selType=0 slab=6 sub=2 depth=-5 rate=4 range=1 held=[(48, 90), (52, 100), (55, 110), (60, 120)] nticks=60 -> 30 events */
static const int G_dense_slab6sub2_r1_sel=0, G_dense_slab6sub2_r1_type=6, G_dense_slab6sub2_r1_depth=-5, G_dense_slab6sub2_r1_range=1;
static const arp_held G_dense_slab6sub2_r1_held[] = { {48,90},{52,100},{55,110},{60,120} };
static const int G_dense_slab6sub2_r1_nheld = 4;
static const arp_ev G_dense_slab6sub2_r1_ev[] = {
  {1,48,70},{1,52,78},{1,55,86},{1,60,94},{0,48,64},{0,52,64},{0,55,64},{0,60,64},{1,67,69},
  {1,72,75},{1,48,56},{1,52,62},{0,67,64},{0,72,64},{0,48,64},{0,52,64},{1,60,70},{1,64,78},
  {1,67,86},{1,72,94},{0,60,64},{0,64,64},{0,67,64},{0,72,64},{1,55,103},{0,55,64},
  {1,60,94},{1,60,70},{1,64,78},{1,67,86},
};
static const int G_dense_slab6sub2_r1_nev = 30;

/* down_slab7sub10_r1: selType=2 slab=7 sub=10 depth=3 rate=4 range=1 held=[(60, 100), (64, 110), (67, 120), (72, 90)] nticks=60 -> 31 events */
static const int G_down_slab7sub10_r1_sel=2, G_down_slab7sub10_r1_type=7, G_down_slab7sub10_r1_depth=3, G_down_slab7sub10_r1_range=1;
static const arp_held G_down_slab7sub10_r1_held[] = { {60,100},{64,110},{67,120},{72,90} };
static const int G_down_slab7sub10_r1_nheld = 4;
static const arp_ev G_down_slab7sub10_r1_ev[] = {
  {1,84,90},{0,84,64},{1,79,120},{1,76,110},{1,72,100},{0,79,64},{0,76,64},{0,72,64},
  {1,72,68},{0,72,64},{1,67,120},{1,64,110},{1,60,100},{0,67,64},{0,64,64},{0,60,64},
  {1,84,90},{0,84,64},{1,79,120},{1,76,110},{1,72,99},{0,79,64},{0,76,64},{0,72,64},
  {1,72,80},{0,72,64},{1,67,120},{0,67,64},{1,64,110},{1,60,100},{1,84,90},
};
static const int G_down_slab7sub10_r1_nev = 31;

/* selType 0=UP,1=UP&DOWN,2=DOWN maps directly to CArpeggio TYPE 0/1/2. */
static int run_cfg(const char *name, int selType, int stype, int depth, int range,
                   const arp_held *held, int nheld, const arp_ev *gold, int ngold)
{
    carp e;
    carp_init(&e);
    carp_set_bpm(&e, 120.0);
    carp_set_scatter(&e, stype, depth);
    carp_set_mode(&e, selType);
    carp_set_range(&e, range);
    for (int i = 0; i < nheld; ++i) carp_add_key(&e, held[i].note, held[i].vel);

    arp_ev got[512];
    int ng = 0, s, j;
    carp_event ev[64];
    for (s = 0; s < 400000 && ng < ngold + 8; ++s) {
        int n = carp_tick(&e, 96000.0, ev, 64);
        for (j = 0; j < n; ++j) {
            if (ng < 512) { got[ng].kind = ev[j].kind; got[ng].note = ev[j].note; got[ng].vel = ev[j].velocity; }
            ++ng;
        }
    }
    if (ng < ngold) { printf("  FAIL %s: only %d events, expected >= %d\n", name, ng, ngold); return 1; }
    int fails = 0;
    for (int i = 0; i < ngold; ++i) {
        if (got[i].kind != gold[i].kind || got[i].note != gold[i].note || got[i].vel != gold[i].vel) {
            printf("  FAIL %s: event %d {%d,%d,%d} != golden {%d,%d,%d}\n", name, i,
                   got[i].kind, got[i].note, got[i].vel, gold[i].kind, gold[i].note, gold[i].vel);
            if (++fails >= 4) break;
        }
    }
    if (!fails) printf("  %s: %d events bit-exact vs 330/330 reference\n", name, ngold);
    return fails ? 1 : 0;
}

#define RUN(nm) run_cfg(#nm, G_##nm##_sel, G_##nm##_type, G_##nm##_depth, G_##nm##_range, \
                        G_##nm##_held, G_##nm##_nheld, G_##nm##_ev, G_##nm##_nev)

int main(void)
{
    int fails = 0;
    fails += RUN(default_1note);
    fails += RUN(chord4_slab7sub10);
    fails += RUN(vel71_slab1sub3);
    fails += RUN(dense_slab6sub2_r1);
    fails += RUN(down_slab7sub10_r1);
    if (fails) { printf("FAIL: %d arp pattern-grid config(s) diverged\n", fails); return 1; }
    printf("OK: arp SCATTER pattern-grid engine bit-exact vs reference (5 configs, incl. steal/skip, octave, <127 vel)\n");
    return 0;
}
