/* test_arp_pattern.c -- the arp SCATTER pattern grid through the port's PRODUCT path, against the
 * PLUGIN's own arp (tests/arp_pattern_golden.h, generated by tools/verify/arp_sched_ab.py from
 * JUNO60.vst3 under Unicorn and regenerated by tools/repro/regen_check.py). Five cases: the default
 * one-note path, a 4-key chord over a 4-slot pattern (steal / skip), a pattern with grid velocities
 * below 127, a dense pattern over two octaves, DOWN over two octaves. Each case is patch 1 of the
 * factory bank with ARPEGGIO SW / TYPE / STEP and SCATTER TYPE / DEPTH set, recalled by
 * juno_gui_apply_bank (the controller setters, as the plugin's host parameter entry calls them),
 * the keys pressed, 96 arp ticks rendered: every event the arp sends -- its tick, on / off, note and
 * velocity -- must be the plugin's. No emulator at test time; the factory bank is read from truth/.
 *
 * Until 2026-10-09 (task #62) this test drove carp_set_scatter directly against goldens from a
 * lost Python model; the plugin plays 4 of those 5 cases differently (velocities, one note): the
 * model was not the plugin's controller path (playbook 185). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "arp_pattern_golden.h"

void *juno_gui_create(float sample_rate, int chorus_mode);
void  juno_gui_destroy(void *c);
int   juno_gui_apply_bank(void *c, const unsigned char *bank, int len, int idx);
void  juno_gui_note_on(void *c, int midi_note, int velocity);
int   juno_gui_render(void *c, float *out, int nframes);
void  juno_gui_arp_trace(void *c, int *buf, int cap);
int   juno_gui_arp_trace_count(void *c);

#define HEADER 23
#define STRIDE 20223
#define PATCH  1
/* the low bytes of the record's int8x4 fields (src/juno_apply.c: juno_bank_arp_raw, juno_bank_scatter) */
enum { ARP_SW = 298, ARP_TYPE = 306, ARP_STEP = 314, SCAT_TYPE = 322, SCAT_DEPTH = 330 };

static void field(unsigned char *bank, int lo, int v)    /* 8 nibbles, two's complement */
{
    unsigned u = (unsigned)v;
    int k;
    for (k = 0; k < 8; ++k)
        bank[HEADER + PATCH * STRIDE + lo - 6 + k] = (unsigned char)((u >> (4 * (7 - k))) & 0xF);
}

static int run_case(const arp_gold_case *g, const unsigned char *bank0, long len)
{
    enum { CAP = 4096 };
    static int buf[4 * CAP];
    unsigned char *bank = malloc((size_t)len);
    int nrender = ARP_GOLD_NTICKS * ARP_GOLD_TICK + ARP_GOLD_TICK, i, n, k = 0, bad = 0;
    float *out = malloc(sizeof(float) * 2 * (size_t)nrender);
    void *c;
    memcpy(bank, bank0, (size_t)len);
    field(bank, ARP_SW, 1);
    field(bank, ARP_TYPE, g->type);
    field(bank, ARP_STEP, g->step);
    field(bank, SCAT_TYPE, g->slab);
    field(bank, SCAT_DEPTH, g->depth);
    c = juno_gui_create((float)ARP_GOLD_SR, 0);
    juno_gui_apply_bank(c, bank, (int)len, PATCH);
    juno_gui_arp_trace(c, buf, CAP);
    for (i = 0; i < g->nheld; ++i) juno_gui_note_on(c, g->held[i][0], g->held[i][1]);
    juno_gui_render(c, out, nrender);
    n = juno_gui_arp_trace_count(c);
    for (i = 0; i < n && !bad; ++i) {
        int tick = buf[4 * i] / ARP_GOLD_TICK + 1;
        if (tick > ARP_GOLD_NTICKS) break;
        if (k >= g->nev || tick != g->ev[k].tick || buf[4 * i + 1] != g->ev[k].kind ||
            buf[4 * i + 2] != g->ev[k].note || buf[4 * i + 3] != g->ev[k].vel) {
            if (k < g->nev)
                printf("  FAIL %s: event %d {tick %d, %d, %d, %d} != the plugin's {%d, %d, %d, %d}\n", g->name, k,
                       tick, buf[4 * i + 1], buf[4 * i + 2], buf[4 * i + 3],
                       g->ev[k].tick, g->ev[k].kind, g->ev[k].note, g->ev[k].vel);
            else
                printf("  FAIL %s: an event past the plugin's %d\n", g->name, g->nev);
            bad = 1;
        }
        ++k;
    }
    if (!bad && k != g->nev) { printf("  FAIL %s: %d events, the plugin's %d\n", g->name, k, g->nev); bad = 1; }
    if (!bad) printf("  %-20s %2d events == the plugin's own arp\n", g->name, g->nev);
    juno_gui_destroy(c);
    free(out);
    free(bank);
    return bad;
}

int main(void)
{
    const char *dir = getenv("JUNO_TRUTH");
    char path[1024];
    FILE *f;
    long len;
    unsigned char *bank;
    int i, fails = 0;
    snprintf(path, sizeof path, "%s/presetbankog1.bin", dir && *dir ? dir : "truth");
    f = fopen(path, "rb");
    if (!f) { printf("FAIL: cannot open %s (run from the repository root)\n", path); return 1; }
    fseek(f, 0, SEEK_END); len = ftell(f); fseek(f, 0, SEEK_SET);
    bank = malloc((size_t)len);
    if (fread(bank, 1, (size_t)len, f) != (size_t)len) { printf("FAIL: short read %s\n", path); return 1; }
    fclose(f);
    if (len < HEADER + (PATCH + 1) * STRIDE) { printf("FAIL: %s is not a bank\n", path); return 1; }
    for (i = 0; i < ARP_GOLD_N; ++i) fails += run_case(&ARP_GOLD[i], bank, len);
    free(bank);
    if (fails) { printf("FAIL: %d arp pattern case(s) differ from the plugin\n", fails); return 1; }
    printf("OK: arp SCATTER patterns through the product path == the plugin's own arp (%d cases, every event)\n", ARP_GOLD_N);
    return 0;
}
