/* host_ref.c — x86 reference generator. Emits a C header (juno_ref.h) that the
 * bare-metal probe bakes in and must reproduce exactly. The x86 engine nulls
 * EXACTLY 0 vs the plugin (make verify), so these hashes ARE the plugin.
 *
 * Three scenario families, "all scenarios covered":
 *   PATCH_REF[64]  — every factory patch, one sustained note.
 *   STORM_REF[]    — deterministic seeded note-on/off + patch-change sequences,
 *                    hashed at CONTINUOUS chunk (what the plugin does).
 * The metal renders the storms at the I2S DMA chunk instead; matching the
 * continuous hash proves BOTH metal==plugin AND chunk-invariance (no
 * block-boundary tick — the S3 failure class) in one comparison.
 *
 * usage: host_ref <bank.bin>            writes juno_ref.h to stdout
 * A human summary + a host-side chunk-invariance self-check go to stderr. */
#include <stdio.h>
#include <stdlib.h>
#include "juno_probe_core.h"

#define SR        48000.0f
#define NOTE      60
#define VEL       105
#define PATCH_NFR 2500        /* per-patch sustained render */
#define STORM_NFR 24000       /* ~0.5 s seeded sequence      */
#define DMA_CHUNK 256         /* I2S DMA block (frames) the metal renders in */

static const unsigned SEEDS[] = {
    0x0badc0deu, 0x00005eedu, 0x00c0ffeeu, 0x0a11ce99u, 0xdeadbeefu
};
#define NSEED ((int)(sizeof SEEDS / sizeof SEEDS[0]))

int main(int argc, char **argv)
{
    if (argc < 2) { fprintf(stderr, "need bank path\n"); return 2; }
    FILE *f = fopen(argv[1], "rb");
    if (!f) { fprintf(stderr, "open %s failed\n", argv[1]); return 2; }
    fseek(f, 0, SEEK_END); long len = ftell(f); fseek(f, 0, SEEK_SET);
    unsigned char *bank = (unsigned char *)malloc((size_t)len);
    if (fread(bank, 1, (size_t)len, f) != (size_t)len) return 2;
    fclose(f);

    int cap = STORM_NFR > PATCH_NFR ? STORM_NFR : PATCH_NFR;
    float *buf  = (float *)malloc(sizeof(float) * 2 * (size_t)cap);
    float *buf2 = (float *)malloc(sizeof(float) * 2 * (size_t)STORM_NFR);

    printf("/* generated by pi/probe/host_ref.c — DO NOT EDIT. The x86 engine\n");
    printf(" * nulls EXACTLY 0 vs the plugin, so these hashes ARE the plugin. */\n");
    printf("#ifndef JUNO_REF_H\n#define JUNO_REF_H\n");
    printf("#define JUNO_SR        %.1ff\n", SR);
    printf("#define JUNO_NOTE      %d\n", NOTE);
    printf("#define JUNO_VEL       %d\n", VEL);
    printf("#define JUNO_PATCH_NFR %d\n", PATCH_NFR);
    printf("#define JUNO_STORM_NFR %d\n", STORM_NFR);
    printf("#define JUNO_DMA_CHUNK %d\n", DMA_CHUNK);

    /* 64 patches */
    printf("static const struct { int patch; unsigned long long hash; } "
           "PATCH_REF[] = {\n");
    for (int p = 0; p < 64; ++p) {
        float pk;
        unsigned long long h = juno_probe_render_hash(bank, (int)len, p, SR,
                                                      NOTE, VEL, PATCH_NFR, buf, &pk);
        printf("  { %2d, 0x%016llxULL },\n", p, h);
    }
    printf("};\n");

    /* seeded storms — reference at CONTINUOUS chunk, plus a host-side proof
     * that DMA-chunked rendering already matches it on x86. */
    printf("static const struct { unsigned seed; int frames; "
           "unsigned long long hash; } STORM_REF[] = {\n");
    int host_inv_ok = 1;
    for (int i = 0; i < NSEED; ++i) {
        float pk;
        unsigned long long hc = juno_probe_timeline_hash(bank, (int)len, SR,
                                    SEEDS[i], STORM_NFR, STORM_NFR, buf, &pk);
        unsigned long long hd = juno_probe_timeline_hash(bank, (int)len, SR,
                                    SEEDS[i], STORM_NFR, DMA_CHUNK, buf2, &pk);
        if (hc != hd) host_inv_ok = 0;
        fprintf(stderr, "seed %08x  continuous %016llx  dma256 %016llx  %s  pk %.4f\n",
                SEEDS[i], hc, hd, hc == hd ? "INVARIANT" : "!! CHUNK-DEP", pk);
        printf("  { 0x%08xu, %d, 0x%016llxULL },\n", SEEDS[i], STORM_NFR, hc);
    }
    printf("};\n#endif\n");

    fprintf(stderr, "HOST chunk-invariance (continuous vs DMA %d): %s\n",
            DMA_CHUNK, host_inv_ok ? "OK (all seeds)" : "FAILED");
    return host_inv_ok ? 0 : 1;
}
