/* patchbank.c -- THE 133-BYTE COMPACT BANK, THE 4,096-BYTE TEMPLATE, AND THE
 * ROUND-TRIP PROOF.
 *
 * The device cannot carry 64 x 20,223-byte plugin records. It carries 64 x 133
 * compact bytes and ONE record template, and at recall time it installs the 133
 * bytes into the template and runs the port's own juno_bank_apply on it.
 *
 * THE CLAIM THIS FILE PROVES, and it is the whole reason the file exists:
 *
 *   for every factory patch, at every host rate,
 *      compact(133) -> template -> juno_bank_apply -> eb_render_coefs
 *                                                     eb_master_coef
 *   is BIT-IDENTICAL to the full-record path.
 *
 * THE BOUND ON THE TEMPLATE is measured here rather than asserted. The record
 * is 20,223 bytes; the template is 4,096. The proof that 4,096 is enough is
 * that the candidate record is ZERO from 4,096 to 20,223 and the coefficients
 * still match. The proof that the template's CONTENT outside the 133 carried
 * positions does not matter is that the same run is repeated with four
 * different templates -- patch 0's prefix, patch 63's prefix, an all-zero
 * template and a randomised one -- and all four must agree.
 *
 * Both of those are stronger than eb_patch.c's EB_RECALL_POS[] list, which is
 * a SINGLE-position perturbation scan: a scan like that cannot see a position
 * that only matters in combination with another. A random template moves every
 * non-carried position at once.
 *
 * usage: patchbank <bank.bin> <outdir>
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "juno_engine.h"
#include "juno_apply.h"
#include "juno_driver.h"
#include "eb_coefs.h"
#include "eb_master_coefs.h"
#include "eb_patch.h"

#define BANK_HEADER 23
#define BANK_STRIDE 20223
#define TEMPLATE_BYTES 4096

static unsigned char *ST;
static eb_render_coefs RC_ref, RC_cand;
static eb_master_coef  MC_ref, MC_cand;

static const int RATES[3] = { 44100, 48000, 96000 };

static void boot(int rate)
{
    memset(ST, 0, JUNO_STATE_BYTES);
    juno_chorus_init(ST);
    JF(ST, 16) = (float)rate;
    juno_engine_init(ST);
    juno_engine_prepare(ST);
}

/* the recall the device performs, byte-for-byte the shim order the device
 * gate uses (tools/engineb/devrecall/gate.c recall()) */
static void recall_build(const unsigned char *bank, int idx,
                         eb_render_coefs *rc, eb_master_coef *mc)
{
    juno_bank_apply(ST, bank, idx);
    juno_driver_seed_voices(ST);
    juno_apply_unison_spread(ST, juno_bank_assign(bank, idx));
    juno_apply_condition(ST, juno_bank_condition(bank, idx));
    juno_apply_lfo_tempo(ST, juno_bank_lfo_rate_byte(bank, idx), 128.0f);
    eb_render_coefs_build(ST, rc);
    eb_master_coefs_build(ST, mc);
}

static int firstdiff(const void *a, const void *b, size_t n)
{
    const unsigned char *x = a, *y = b; size_t i;
    for (i = 0; i < n; ++i) if (x[i] != y[i]) return (int)i;
    return -1;
}

static void wr(const char *dir, const char *name, const void *p, size_t n)
{
    char path[512]; FILE *f;
    snprintf(path, sizeof path, "%s/%s", dir, name);
    f = fopen(path, "wb");
    if (!f) { perror(path); exit(2); }
    fwrite(p, 1, n, f); fclose(f);
    printf("  wrote %s  %u B\n", path, (unsigned)n);
}

static void wrh(const char *dir, const char *name, const char *sym,
                const unsigned char *p, size_t n, const char *note)
{
    char path[512]; FILE *f; size_t i;
    snprintf(path, sizeof path, "%s/%s", dir, name);
    f = fopen(path, "w");
    if (!f) { perror(path); exit(2); }
    fprintf(f, "/* GENERATED by tools/engineb/devboot/patchbank.c -- DO NOT EDIT.\n"
               " * %s */\n", note);
    fprintf(f, "static const unsigned char %s[%u] = {\n", sym, (unsigned)n);
    for (i = 0; i < n; ++i) fprintf(f, "%s%u", (i % 20) ? "," : (i ? ",\n" : ""), p[i]);
    fprintf(f, "};\n");
    fclose(f);
    printf("  wrote %s  (symbol %s)\n", path, sym);
}

int main(int argc, char **argv)
{
    static unsigned char PB[EB_BANK_COUNT][EB_PATCH_BYTES];
    static unsigned char TPL[4][TEMPLATE_BYTES];
    static const char *TPLNAME[4] = { "patch 0 prefix", "patch 63 prefix",
                                      "all zero", "randomised" };
    unsigned char *bank, *fake;
    long bl;
    FILE *f;
    int p, r, t, bad = 0, i, miss[64], nm;
    unsigned s = 12345u;

    if (argc < 3) { fprintf(stderr, "usage: %s <bank.bin> <outdir>\n", argv[0]); return 2; }
    f = fopen(argv[1], "rb");
    if (!f) { perror(argv[1]); return 2; }
    fseek(f, 0, SEEK_END); bl = ftell(f); fseek(f, 0, SEEK_SET);
    bank = (unsigned char *)malloc((size_t)bl);
    if (fread(bank, 1, (size_t)bl, f) != (size_t)bl) return 2;
    fclose(f);
    ST = (unsigned char *)malloc(JUNO_STATE_BYTES);
    fake = (unsigned char *)malloc(BANK_HEADER + BANK_STRIDE);

    /* ---------------------------------------------------- 3a: the format */
    printf("=== THE COMPACT FORMAT ===\n");
    printf("EB_PATCH_BYTES        = %d %s\n", EB_PATCH_BYTES,
           EB_PATCH_BYTES == 133 ? "(133, as claimed)" : "*** NOT 133 ***");
    if (EB_PATCH_BYTES != 133) bad = 1;
    printf("eb_patch_selftest()   = %d %s\n", eb_patch_selftest(),
           eb_patch_selftest() == 0 ? "(pass)" : "*** FAIL ***");
    if (eb_patch_selftest()) bad = 1;
    nm = eb_patch_record_coverage(miss, 64);
    printf("record coverage: %d recall-affecting position(s) NOT carried%s\n", nm,
           nm ? " ***" : "  (pass)");
    for (i = 0; i < nm && i < 64; ++i) printf("   MISSING record %d\n", miss[i]);
    if (nm) bad = 1;
    nm = eb_patch_coverage(miss, 64);
    printf("parameter coverage: %d located parameter(s) not carried\n", nm);
    for (i = 0; i < nm && i < 64; ++i)
        printf("   MISSING %d (%s)\n", miss[i], eb_patch_name_of(miss[i]));
    if (nm) bad = 1;
    {   const char *names[64];
        int nu = eb_patch_unresolved(names, 64);
        printf("UNRESOLVED (position never derived, NOT a format defect): %d\n", nu);
        for (i = 0; i < nu && i < 64; ++i) printf("   %s\n", names[i]);
    }
    printf("highest carried blob offset = %u -> record %u\n",
           eb_patch_offsets[EB_PATCH_BYTES - 1],
           eb_patch_offsets[EB_PATCH_BYTES - 1] + EB_BANK_BLOB_OFF);

    /* ------------------------------------------------- 3b: the flash blob */
    printf("\n=== THE 64-PATCH BANK ===\n");
    for (p = 0; p < EB_BANK_COUNT; ++p) {
        eb_patch q;
        if (eb_patch_extract(bank, (size_t)bl, p, &q)) { printf("extract %d FAILED\n", p); return 1; }
        memcpy(PB[p], q.b, EB_PATCH_BYTES);
    }
    printf("64 x %d = %u B\n", EB_PATCH_BYTES,
           (unsigned)(EB_BANK_COUNT * EB_PATCH_BYTES));
    wr(argv[2], "eb_bank64.bin", PB, sizeof PB);
    wrh(argv[2], "eb_bank64.h", "eb_bank64", (const unsigned char *)PB, sizeof PB,
        "the 64 factory patches in the 133-byte compact format,\n"
        " * extracted from truth/presetbankog1.bin by eb_patch_extract().");

    /* --------------------------------------------------- 4: the templates */
    memcpy(TPL[0], bank + BANK_HEADER + 0L * BANK_STRIDE, TEMPLATE_BYTES);
    memcpy(TPL[1], bank + BANK_HEADER + 63L * BANK_STRIDE, TEMPLATE_BYTES);
    memset(TPL[2], 0, TEMPLATE_BYTES);
    for (i = 0; i < TEMPLATE_BYTES; ++i) {
        s = s * 1103515245u + 12345u;
        TPL[3][i] = (unsigned char)((s >> 16) & 0xFF);
    }

    /* ------------------------------------------------- the round trip */
    printf("\n=== ROUND TRIP: 133 bytes -> template -> recall -> coefficients ===\n");
    printf("candidate record is ZERO from %d to %d, so a match PROVES the "
           "template needs\nno byte past %d.\n",
           TEMPLATE_BYTES, BANK_STRIDE, TEMPLATE_BYTES);
    for (r = 0; r < 3; ++r) {
        for (t = 0; t < 4; ++t) {
            int nfail = 0, firstp = -1, firstb = -1, which = 0;
            for (p = 0; p < EB_BANK_COUNT; ++p) {
                int d;
                boot(RATES[r]);
                recall_build(bank, p, &RC_ref, &MC_ref);
                memset(fake, 0, BANK_HEADER + BANK_STRIDE);
                memcpy(fake + BANK_HEADER, TPL[t], TEMPLATE_BYTES);
                {   eb_patch q; memcpy(q.b, PB[p], EB_PATCH_BYTES);
                    eb_patch_install(fake + BANK_HEADER, &q); }
                boot(RATES[r]);
                recall_build(fake, 0, &RC_cand, &MC_cand);
                d = firstdiff(&RC_ref, &RC_cand, sizeof RC_ref);
                if (d >= 0) {
                    ++nfail;
                    if (firstp < 0) { firstp = p; firstb = d; which = 1; }
                    continue;
                }
                d = firstdiff(&MC_ref, &MC_cand, sizeof MC_ref);
                if (d >= 0) {
                    ++nfail;
                    if (firstp < 0) { firstp = p; firstb = d; which = 2; }
                }
            }
            printf("rate %6d  template=%-16s  %2d/64 %s",
                   RATES[r], TPLNAME[t], 64 - nfail,
                   nfail ? "*** DIVERGE ***" : "BIT-IDENTICAL");
            if (nfail)
                printf("   first: patch %d, %s byte %d",
                       firstp, which == 1 ? "eb_render_coefs" : "eb_master_coef", firstb);
            printf("\n");
            if (nfail) bad = 1;
        }
    }

    /* ------------------------------------------------ LOCATE a divergence
     *
     * If the randomised template moves a patch, some record position OUTSIDE
     * the 133 carried bytes reaches the coefficients -- which is exactly what
     * a single-position scan is structurally unable to report. Bisect the
     * randomised template against the all-zero one to name the position.
     */
    {
        int fails[EB_BANK_COUNT], nf = 0;
        for (p = 0; p < EB_BANK_COUNT; ++p) {
            boot(RATES[0]);
            recall_build(bank, p, &RC_ref, &MC_ref);
            memset(fake, 0, BANK_HEADER + BANK_STRIDE);
            memcpy(fake + BANK_HEADER, TPL[3], TEMPLATE_BYTES);
            {   eb_patch q; memcpy(q.b, PB[p], EB_PATCH_BYTES);
                eb_patch_install(fake + BANK_HEADER, &q); }
            boot(RATES[0]);
            recall_build(fake, 0, &RC_cand, &MC_cand);
            if (firstdiff(&RC_ref, &RC_cand, sizeof RC_ref) >= 0 ||
                firstdiff(&MC_ref, &MC_cand, sizeof MC_ref) >= 0)
                fails[nf++] = p;
        }
        if (nf) {
            printf("\n=== LOCATING: %d patch(es) move under a randomised "
                   "template ===\npatches:", nf);
            for (i = 0; i < nf; ++i) printf(" %d", fails[i]);
            printf("\n");
        }
        for (i = 0; i < nf; ++i) {
            /* per-position sweep over the NON-carried positions in [0,4096):
             * zero template, one randomised byte at a time. 4,096 recalls per
             * failing patch -- small, and it names every contributing byte
             * rather than just the first. */
            int off, nhit = 0;
            p = fails[i];
            boot(RATES[0]);
            recall_build(bank, p, &RC_ref, &MC_ref);
            for (off = 0; off < TEMPLATE_BYTES; ++off) {
                if (TPL[3][off] == 0) continue;
                memset(fake, 0, BANK_HEADER + BANK_STRIDE);
                fake[BANK_HEADER + off] = TPL[3][off];
                {   eb_patch q; memcpy(q.b, PB[p], EB_PATCH_BYTES);
                    eb_patch_install(fake + BANK_HEADER, &q); }
                boot(RATES[0]);
                recall_build(fake, 0, &RC_cand, &MC_cand);
                if (firstdiff(&RC_ref, &RC_cand, sizeof RC_ref) >= 0 ||
                    firstdiff(&MC_ref, &MC_cand, sizeof MC_ref) >= 0) {
                    printf("  patch %2d: record position %4d (blob %4d) = 0x%02X "
                           "moves the coefficients [%s]\n", p, off,
                           off - EB_BANK_BLOB_OFF, TPL[3][off],
                           eb_patch_name_of(off));
                    ++nhit;
                }
            }
            if (!nhit)
                printf("  patch %2d: NO single position reproduces it -- the "
                       "divergence is a COMBINATION\n", p);
        }
    }

    /* ------------------------------------ IS THE FORMAT SHORT BY MORE?
     *
     * One random template is one sample. Repeat it: PB_RANDT templates x 64
     * patches, and collect every position that a per-position sweep then names.
     * This perturbs every non-carried position AT ONCE, which is the thing a
     * single-position scan structurally cannot do.
     *
     * AND THE BOUND ABOVE 4,096: a second sweep randomises the record from
     * 4,096 to 20,223 while keeping [0,4096) real. If those never move a
     * coefficient, the 4,096-byte template is proven sufficient by execution
     * and not by reading juno_bank_apply's offsets.
     */
    {
        int nt = 64, ti, hitpos[4096], nhp = 0, tot = 0;
        const char *e = getenv("PB_RANDT");
        unsigned rs = 0xC0FFEEu;
        if (e) nt = atoi(e);
        memset(hitpos, 0, sizeof hitpos);
        printf("\n=== IS THE FORMAT SHORT BY MORE THAN ONE BYTE? "
               "(%d random templates x 64 patches) ===\n", nt);
        for (ti = 0; ti < nt; ++ti) {
            unsigned char T[TEMPLATE_BYTES];
            for (i = 0; i < TEMPLATE_BYTES; ++i) {
                rs = rs * 1103515245u + 12345u;
                T[i] = (unsigned char)((rs >> 16) & 0xFF);
            }
            for (p = 0; p < EB_BANK_COUNT; ++p) {
                boot(RATES[0]);
                recall_build(bank, p, &RC_ref, &MC_ref);
                memset(fake, 0, BANK_HEADER + BANK_STRIDE);
                memcpy(fake + BANK_HEADER, T, TEMPLATE_BYTES);
                {   eb_patch q; memcpy(q.b, PB[p], EB_PATCH_BYTES);
                    eb_patch_install(fake + BANK_HEADER, &q); }
                boot(RATES[0]);
                recall_build(fake, 0, &RC_cand, &MC_cand);
                if (firstdiff(&RC_ref, &RC_cand, sizeof RC_ref) < 0 &&
                    firstdiff(&MC_ref, &MC_cand, sizeof MC_ref) < 0) continue;
                ++tot;
                /* name the byte(s): bisect by restoring the real record one
                 * position at a time until it matches again */
                for (i = 0; i < TEMPLATE_BYTES; ++i) {
                    if (T[i] == bank[BANK_HEADER + (long)p * BANK_STRIDE + i]) continue;
                    fake[BANK_HEADER + i] = bank[BANK_HEADER + (long)p * BANK_STRIDE + i];
                    boot(RATES[0]);
                    recall_build(fake, 0, &RC_cand, &MC_cand);
                    if (firstdiff(&RC_ref, &RC_cand, sizeof RC_ref) < 0 &&
                        firstdiff(&MC_ref, &MC_cand, sizeof MC_ref) < 0) {
                        if (!hitpos[i]) ++nhp;
                        ++hitpos[i];
                        break;
                    }
                }
            }
        }
        printf("%d of %d (template,patch) pairs diverged; %d distinct record "
               "position(s) implicated:\n", tot, nt * EB_BANK_COUNT, nhp);
        for (i = 0; i < TEMPLATE_BYTES; ++i)
            if (hitpos[i])
                printf("   record %4d (blob %4d)  %d hit(s)  [%s]%s\n", i,
                       i - EB_BANK_BLOB_OFF, hitpos[i], eb_patch_name_of(i),
                       i == 126 ? "  <- LEGATO high nibble, src/juno_apply.c:652" : "");
        if (tot) bad = 1;
    }
    {   /* THE BOUND: randomise record [4096, 20223) and keep [0,4096) real */
        int nfail = 0;
        unsigned rs = 0xABCD01u;
        printf("\n=== THE 4,096 BOUND: randomise record [4096,%d) ===\n", BANK_STRIDE);
        for (p = 0; p < EB_BANK_COUNT; ++p) {
            boot(RATES[0]);
            recall_build(bank, p, &RC_ref, &MC_ref);
            memcpy(fake, bank, BANK_HEADER);
            memcpy(fake + BANK_HEADER,
                   bank + BANK_HEADER + (long)p * BANK_STRIDE, BANK_STRIDE);
            for (i = TEMPLATE_BYTES; i < BANK_STRIDE; ++i) {
                rs = rs * 1103515245u + 12345u;
                fake[BANK_HEADER + i] = (unsigned char)((rs >> 16) & 0xFF);
            }
            boot(RATES[0]);
            recall_build(fake, 0, &RC_cand, &MC_cand);
            if (firstdiff(&RC_ref, &RC_cand, sizeof RC_ref) >= 0 ||
                firstdiff(&MC_ref, &MC_cand, sizeof MC_ref) >= 0) ++nfail;
        }
        printf("%2d/64 %s -- the template needs no byte at or past %d\n",
               64 - nfail, nfail ? "*** DIVERGE ***" : "BIT-IDENTICAL", TEMPLATE_BYTES);
        if (nfail) bad = 1;

        /* and the TRUE bound, so 4,096 is a measured round-up and not a
         * round number: the smallest B for which randomising [B,20223)
         * changes nothing on any patch. */
        {   int lo2 = 0, hi2 = TEMPLATE_BYTES, mid;
            while (lo2 < hi2) {
                int f2 = 0;
                mid = (lo2 + hi2) / 2;
                for (p = 0; p < EB_BANK_COUNT && !f2; ++p) {
                    boot(RATES[0]);
                    recall_build(bank, p, &RC_ref, &MC_ref);
                    memcpy(fake, bank, BANK_HEADER);
                    memcpy(fake + BANK_HEADER,
                           bank + BANK_HEADER + (long)p * BANK_STRIDE, BANK_STRIDE);
                    for (i = mid; i < BANK_STRIDE; ++i) {
                        rs = rs * 1103515245u + 12345u;
                        fake[BANK_HEADER + i] = (unsigned char)((rs >> 16) & 0xFF);
                    }
                    boot(RATES[0]);
                    recall_build(fake, 0, &RC_cand, &MC_cand);
                    if (firstdiff(&RC_ref, &RC_cand, sizeof RC_ref) >= 0 ||
                        firstdiff(&MC_ref, &MC_cand, sizeof MC_ref) >= 0) f2 = 1;
                }
                if (f2) lo2 = mid + 1; else hi2 = mid;
            }
            printf("MEASURED highest record position that reaches a coefficient: "
                   "%d (template needs %d bytes; %d is that rounded up)\n",
                   lo2 - 1, lo2, TEMPLATE_BYTES);
        }
    }

    /* ------------------------------------------- WHY THE SCAN MISSED IT
     *
     * eb_patch.c's EB_RECALL_POS[] is a single-position scan with the probe
     * values {0x00,0x03,0x0C,0x7F} over six base patches. Record 126/127 is
     * LEGATO (src/juno_apply.c:652) and it reaches the coefficients only
     * through `lg == 1 && as == 1` -> JF(state,608). TWO independent reasons
     * that scan cannot see it, and each is demonstrated by execution here:
     *
     *   (a) no base patch satisfies the gate. Only patches 5 and 47 do.
     *   (b) the four probe values have LOW NIBBLES 0, 3, 12, 15. LEGATO's only
     *       live value is 1. A probe set that cannot emit the nibble the
     *       equality tests for can never move an equality-gated parameter --
     *       and the same holds for 11 of the 16 nibble values.
     */
    {
        static const unsigned char SCANVAL[4] = { 0x00u, 0x03u, 0x0Cu, 0x7Fu };
        int base = 14;                   /* ASSIGN MODE == 1, LEGATO == 0 */
        int k, moved;
        printf("\n=== WHY THE SINGLE-POSITION SCAN MISSED RECORD 126/127 ===\n");
        printf("base patch %d has ASSIGN MODE == 1, so the LEGATO gate is one "
               "nibble away.\n", base);
        for (k = 0; k < 5; ++k) {
            unsigned char v = (k < 4) ? SCANVAL[k] : 0x01u;
            unsigned char *rec = bank + BANK_HEADER + (long)base * BANK_STRIDE;
            unsigned char orig = rec[127];
            boot(RATES[0]);
            recall_build(bank, base, &RC_ref, &MC_ref);
            rec[127] = v;
            boot(RATES[0]);
            recall_build(bank, base, &RC_cand, &MC_cand);
            rec[127] = orig;
            moved = firstdiff(&RC_ref, &RC_cand, sizeof RC_ref) >= 0 ||
                    firstdiff(&MC_ref, &MC_cand, sizeof MC_ref) >= 0;
            printf("   record[127] = 0x%02X (nibble %2d)%s -> coefficients %s\n",
                   v, v & 0xF, k < 4 ? "  [a scan probe value]" : "  [NOT a probe value]",
                   moved ? "MOVE" : "do not move");
        }
    }

    /* ------------------------------- THE FIX, DEMONSTRATED NOT ASSERTED
     * Carry blob 110 as well -- EB_PATCH_BYTES 133 -> 134 -- and the
     * randomised template stops mattering. Simulated here by installing the
     * one extra byte on top of eb_patch_install(); the format itself is NOT
     * edited by this tool. */
    {
        int nfail = 0;
        printf("\n=== THE FIX: carry blob 110 too (EB_PATCH_BYTES 133 -> 134) ===\n");
        for (p = 0; p < EB_BANK_COUNT; ++p) {
            boot(RATES[0]);
            recall_build(bank, p, &RC_ref, &MC_ref);
            memset(fake, 0, BANK_HEADER + BANK_STRIDE);
            memcpy(fake + BANK_HEADER, TPL[3], TEMPLATE_BYTES);   /* randomised */
            {   eb_patch q; memcpy(q.b, PB[p], EB_PATCH_BYTES);
                eb_patch_install(fake + BANK_HEADER, &q); }
            /* the 134th byte: blob 110 = record 126, LEGATO's high nibble */
            fake[BANK_HEADER + 126] =
                bank[BANK_HEADER + (long)p * BANK_STRIDE + 126];
            boot(RATES[0]);
            recall_build(fake, 0, &RC_cand, &MC_cand);
            if (firstdiff(&RC_ref, &RC_cand, sizeof RC_ref) >= 0 ||
                firstdiff(&MC_ref, &MC_cand, sizeof MC_ref) >= 0) ++nfail;
        }
        printf("rate  44100  template=randomised    %2d/64 %s\n", 64 - nfail,
               nfail ? "*** STILL DIVERGES ***" : "BIT-IDENTICAL");
    }

    /* the template that ships: patch 0's prefix, real plugin data */
    printf("\n=== THE SHIPPED TEMPLATE ===\n");
    wr(argv[2], "eb_template.bin", TPL[0], TEMPLATE_BYTES);
    wrh(argv[2], "eb_template.h", "eb_template", TPL[0], TEMPLATE_BYTES,
        "the first 4,096 bytes of factory record 0 from\n"
        " * truth/presetbankog1.bin. Its content outside the 133 carried\n"
        " * positions is PROVEN irrelevant to the recalled coefficients (this\n"
        " * generator repeats the whole round trip with an all-zero and a\n"
        " * randomised template and gets bit-identical results); it is real\n"
        " * plugin data so that a dump of it is readable rather than noise.");

    printf("\nTOTAL FLASH for the patch path: bank %u + template %u = %u B\n",
           (unsigned)(EB_BANK_COUNT * EB_PATCH_BYTES), TEMPLATE_BYTES,
           (unsigned)(EB_BANK_COUNT * EB_PATCH_BYTES + TEMPLATE_BYTES));
    printf("%s\n", bad ? "*** FAILED ***" : "ALL CHECKS PASS");
    return bad;
}
