/* fx_crc.c -- host (32-bit) twin of the S3 boot check: prints fx_render_crc()
 * and writes main/gen/msq_fx_check.h. */
#include <stdio.h>
#include <stdlib.h>
#include "fx.h"
int main(int argc, char **argv)
{
    void *mem = malloc(msq_fx_state_bytes);
    fx_init(mem);
    unsigned c = fx_render_crc();
    printf("host fx_render_crc = %08x\n", c);
    if (argc > 1) {
        FILE *f = fopen(argv[1], "w"); if (!f) return 2;
        fprintf(f, "/* GENERATED by tools/fx_crc.c (host, 32-bit) -- DO NOT EDIT */\n#define MSQ_FX_RENDER_CRC 0x%08xu\n", c);
        fclose(f);
    }
    return 0;
}
