#!/usr/bin/env python3
"""gen_host_ramps.py -- generate src/ramp_cells.h and src/host_ramp_table.h from
the plugin's own executed census (CLAIMS B7). Two-process rule: the inputs are
oracle pickles written by the Unicorn-only probes; this script never loads the
oracle or libjuno.

INPUTS (regenerate them from the .vst3 first; both are Unicorn-only):
  scratchpad/ramp_records_units.pkl  python3 probes/host/ramp_records_units.py
      every ramp record of every unit after build + setSampleRate + snap, mapped
      onto the port's one state: the 798 ramped cells, and the 86 whose stored
      target the build left at 0 (never armed after their last immediate write).
  scratchpad/host_census_v2.pkl      python3 probes/host/host_census_v2.py
      the HOST entry's (rva 0x3C7AE0, flag 0) set list for every host
      parameter over 11282 edits (contexts, values, seeded records).

OUTPUTS
  src/ramp_cells.h        JUNO_RAMP_CELL[798] (ascending) + JUNO_RAMP_BUILD0[]
  src/host_ramp_table.h   the host-edit programs (see src/host_edit.c)

USAGE
    python3 tools/verify/gen_host_ramps.py           write both headers
    python3 tools/verify/gen_host_ramps.py --check   exit 1 if a header differs
"""
import os
import sys
import pickle

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SCRATCH = os.path.join(REPO, 'scratchpad')
REC_PKL = os.path.join(SCRATCH, 'ramp_records_units.pkl')
CEN_PKL = os.path.join(SCRATCH, 'host_census_v2.pkl')
CEN3_PKL = os.path.join(SCRATCH, 'host_census_v3.pkl')
CENH_PKL = os.path.join(SCRATCH, 'host_census_h.pkl')
FLG_PKL = os.path.join(SCRATCH, 'host_census_flags.pkl')
CELLS_H = os.path.join(REPO, 'src', 'ramp_cells.h')
TABLE_H = os.path.join(REPO, 'src', 'host_ramp_table.h')

# value sources (src/host_edit.c)
S_REC, S_ZERO, S_ONE, S_OFF, S_TAP2, S_HOSTV = 0, 1, 2, 3, 4, 5
SRC_NAME = {S_REC: 'JH_REC', S_ZERO: 'JH_ZERO', S_ONE: 'JH_ONE', S_OFF: 'JH_OFF', S_TAP2: 'JH_TAP2', S_HOSTV: 'JH_HOSTV'}
CONST = {0x00000000: S_ZERO, 0x3f800000: S_ONE, 0x3fa754b5: S_OFF}   # OFF: juno_lfx1_value(44100, 0)
OFF_CELLS = {91248, 96384, 102544, 4297776, 6396400, 6430736, 6497360, 10693280}
TAP2_CELL = 4297792
KIND = {'R': 0, 'I': 1, 'W': 2}
# key features, in mixed-radix order (src/host_edit.c juno_host_key)
FEATS = ['ET', 'DT', 'FROM', 'TO', 'DON1', 'RON0', 'RON1', 'PL', 'ARPON', 'ETC']
FBIT = {f: 1 << k for k, f in enumerate(FEATS)}
CANDIDATES = [(), ('ET',), ('DT',), ('ETC',), ('TO',), ('PL',), ('ET', 'DT'), ('DT', 'TO'), ('ET', 'TO'),
              ('FROM', 'TO'), ('DT', 'DON1'), ('RON0', 'RON1'), ('PL', 'ETC'), ('TO', 'PL', 'ETC'),
              ('TO', 'PL', 'ARPON', 'ETC'), ('FROM', 'TO', 'PL', 'ARPON', 'ETC'),
              ('DT', 'FROM', 'TO'), ('ET', 'FROM', 'TO'), ('ET', 'DT', 'TO'), ('ET', 'DT', 'FROM', 'TO')]
ETC_OF = {0: 0, 1: 1, 2: 2, 3: 2, 4: 2, 5: 3}
CUTOFF_CELLS = set(6736 + 10512 * v for v in range(8))
HEADER, STRIDE = 23, 20223


def cutoff_time(frm, to):
    d = min(abs(to - frm), 5)
    return max(5, 3 * (5 - d))


def nib(rec, off):
    return ((rec[off] & 0xF) << 4) | (rec[off + 1] & 0xF)


def ramp_cells_h():
    r = pickle.load(open(REC_PKL, 'rb'))
    rates = sorted(r)
    cells = sorted(r[rates[0]]['comp'])
    for sr in rates:
        if sorted(r[sr]['comp']) != cells:
            raise SystemExit('the ramped cell set differs between rates')
    # never armed at build: stored target 0 at every rate (a cell whose value is
    # also 0 at some rate shows target == cell there, so take the union and
    # check the target is 0 everywhere)
    build0 = set()
    for sr in rates:
        build0 |= set(r[sr]['diff'])
    for sr in rates:
        for c in build0:
            if r[sr]['comp'][c][0] != 0:
                raise SystemExit('cell %d: build target not 0 at %g' % (c, sr))
    out = ['/* ramp_cells.h -- GENERATED by tools/verify/gen_host_ramps.py; do not edit.',
           ' *',
           ' * The plugin\'s ramped cells (descriptor type 1, setter rva 0x3C10D0 ->',
           ' * 0x3C2920), mapped onto the port\'s one state as the gates compare it',
           ' * (voice v\'s cells from unit v, the master from unit 8): %d cells,' % len(cells),
           ' * ascending. JUNO_RAMP_BUILD0[i] = 1 where the build + setSampleRate +',
           ' * snap leaves the record\'s stored target at 0.0 while the cell holds',
           ' * another value (%d cells, the same at %s Hz). Every other record\'s' % (
               len(build0), '/'.join('%g' % s for s in rates)),
           ' * stored target equals its cell. EXECUTED: probes/host/ramp_records_units.py.',
           ' */',
           '#ifndef JUNO_RAMP_CELLS_H',
           '#define JUNO_RAMP_CELLS_H',
           '#include <stdint.h>',
           '#define JUNO_RAMP_N %d' % len(cells),
           'static const uint32_t JUNO_RAMP_CELL[JUNO_RAMP_N] = {']
    for k in range(0, len(cells), 8):
        out.append('    ' + ' '.join('%uu,' % c for c in cells[k:k + 8]))
    out.append('};')
    out.append('static const unsigned char JUNO_RAMP_BUILD0[JUNO_RAMP_N] = {')
    flags = [1 if c in build0 else 0 for c in cells]
    for k in range(0, len(flags), 32):
        out.append('    ' + ''.join('%d,' % f for f in flags[k:k + 32]))
    out.append('};')
    out.append('#endif /* JUNO_RAMP_CELLS_H */')
    return '\n'.join(out) + '\n'


def job_ops(r, name=None):
    """[(kind, cell, t, val, rec)] of one census job; 'N' (a ramped set on a
    non-ramp descriptor: the wrapper returns, READ) dropped. VCF CUTOFF FREQ's
    own ramp time follows the step (rva 0x3597F0): coded 0x80 where it does."""
    out = []
    for a, c, t, val in r['ev']:
        if a == 'N':
            continue
        if a == 'W':
            if t != 4:
                raise SystemExit('a %d-byte direct write at %d' % (t, c))
            t = 0
        if name == 'VCF CUTOFF FREQ' and a == 'R' and c in CUTOFF_CELLS and t == cutoff_time(r['frm'], r['to']):
            t = 0x80
        out.append((KIND[a], c, t or 0, val & 0xFFFFFFFF, r['rec'].get(c) if r.get('rec') else None, r['to']))
    return dedupe(out) if name in DEDUPE else out


DEDUPE = ('ARPEGGIO SW', 'ARPEGGIO TYPE', 'ARPEGGIO STEP')   # every set the recall's value
# GATES on processor state the census cannot key (src/host_edit.c JH_G_*):
# the arpeggiator's refresh runs only while the processor's arp is on, and the
# switch runs it only when it turns the arp on (EXECUTED, scratchpad/probe_arp3.py:
# a recall leaves the processor's arp state alone; only a host ARPEGGIO SW edit
# moves it). Every census job of these three ran with the processor arp on.
GATE = {'ARPEGGIO TYPE': 1, 'ARPEGGIO STEP': 1, 'ARPEGGIO SW': 2}


def dedupe(ops):
    """Drop a set that repeats the previous set of the same cell (same kind,
    same value): a ramped set whose target equals the stored target the
    previous one left early-outs (rva 0x3C2E86), and a repeated store stores
    the same bits; no ramp steps inside one edit. EXACT, and it makes the
    arpeggiator's 1/3/4 refresh passes one list."""
    last = {}
    out = []
    for op in ops:
        k, c, t, v, rc = op[:5]
        prev = last.get(c)
        if prev is not None and prev[0] == k and prev[3] == v:
            continue
        last[c] = op
        out.append(op)
    return out


def feats_of(r, name, lo, hi):
    f = {'ET': r['ctx'][0], 'DT': r['ctx'][1], 'FROM': r['frm'] - lo, 'TO': r['to'] - lo,
         'RON0': int(r['frm'] >= 3), 'RON1': int(r['to'] >= 3), 'DON1': None,
         'ETC': ETC_OF.get(r['ctx'][0]), 'PL': r.get('pl'), 'ARPON': r.get('arpon')}
    if name == 'DELAY LEVEL':
        f['DON1'] = r.get('f1', 1 if r['to'] >= 2 else (0 if r['to'] == 0 else None))
    return f


def card(f, lo, hi):
    return {'ET': 6, 'DT': 6, 'FROM': hi - lo + 1, 'TO': hi - lo + 1, 'ETC': 4}.get(f, 2)


def merge_src(rows):
    """one op position over every job of a key: [(val, rec, host value)] -> a source"""
    vals = set(v for v, rc, to in rows)
    rec_ok = all(rc is not None and v == rc for v, rc, to in rows)
    if rec_ok:
        return S_REC
    if all(v == (to & 0xFFFFFFFF) for v, rc, to in rows) and len(vals) > 1:
        return S_HOSTV
    if len(vals) == 1:
        v = vals.pop()
        if v in CONST:
            return CONST[v]
    return None


def programs():
    cen = pickle.load(open(CEN_PKL, 'rb'))
    flg = pickle.load(open(FLG_PKL, 'rb'))
    host = cen['host']
    P = {p[0]: p for p in cen['plist']}
    sys.path.insert(0, HERE)
    import truth
    bank = open(truth.BANK, 'rb').read()
    p0 = bank[HEADER:HEADER + STRIDE]
    jobs = {}
    srcs = [cen]
    for extra in (CEN3_PKL, CENH_PKL):
        if os.path.exists(extra):
            srcs.append(pickle.load(open(extra, 'rb')))
    for cs in srcs[1:]:
        for p in cs['plist']:
            P.setdefault(p[0], p)
    for cs in srcs:
        for j, r in cs['res'].items():
            if r['ok'] is not True:
                raise SystemExit('census job %d failed: %s' % (j, r['ok']))
            rec = r.get('base') or p0       # families A-D: patch 0 (types forced only)
            r = dict(r, pl=int(nib(rec, 128) == 0 and nib(rec, 126) == 1), arpon=int(nib(rec, 298) != 0))
            jobs.setdefault(r['i'], []).append(r)
    # DELAY LEVEL: the shape census with the on-flag read (no recall values);
    # its value sources come from the main census (on-flag known for to != 1)
    for r in flg:
        if r['name'] == 'DELAY LEVEL':
            rr = dict(r, ctx=(r['et'], r['dt']), rec=None, flagjob=True, pl=0, arpon=0)
            jobs.setdefault(r['k'], []).append(rr)
    params = {}
    report = []
    for i in sorted(jobs):
        _, name, d, pid, lo, hi = P[i][:6]
        rs = jobs[i]
        chosen = None
        for cand in CANDIDATES:
            if any(card(f, lo, hi) > 64 for f in cand if f in ('FROM', 'TO')):
                continue
            groups = {}
            ok = True
            for r in rs:
                f = feats_of(r, name, lo, hi)
                if any(f[x] is None for x in cand):
                    continue
                key = tuple(f[x] for x in cand)
                ops = job_ops(r, name)
                shp = tuple((k, c, t) for k, c, t, v, rc, to in ops)
                g = groups.setdefault(key, [shp, []])
                if g[0] != shp:
                    ok = False
                    break
                if not r.get('flagjob'):
                    g[1].append(ops)
            if not ok or not groups:
                continue
            progs, why = {}, None
            for key, (shp, opsl) in groups.items():
                srcs = []
                for pos, (k, c, t) in enumerate(shp):
                    rows = [(ops[pos][3], ops[pos][4], ops[pos][5]) for ops in opsl]
                    src = merge_src(rows) if rows else None
                    if src is None and c == TAP2_CELL and name == 'DELAY TYPE':
                        src = S_TAP2
                    if src == S_OFF and c not in OFF_CELLS:
                        src = None
                    if src is None:
                        why = 'key %s op %d (cell %d): no one source for %s' % (
                            key, pos, c, sorted(set('%08x/%s' % (v, '%08x' % rc if rc is not None else '-')
                                                    for v, rc, to in rows))[:4] if rows else 'no recall values')
                        break
                    srcs.append(src)
                if why:
                    break
                progs[key] = tuple((k, c, t, sr) for (k, c, t), sr in zip(shp, srcs))
            if why:
                report.append('%d %s: candidate %s rejected: %s' % (i, name, cand, why))
                continue
            space = 1
            for x in cand:
                space *= card(x, lo, hi)
            # the first consistent key with full coverage; else the best covered
            c2 = (cand, progs, space - len(groups))
            if chosen is None or c2[2] < chosen[2]:
                chosen = c2
            if c2[2] == 0:
                break
        if chosen is None:
            report.append('%d %s: NO KEY among the candidates' % (i, name))
            continue
        cand, progs, missing = chosen
        if missing:
            report.append('%d %s: key %s covers %d of %d' % (i, name, cand, len(progs), len(progs) + missing))
        params[i] = (name, cand, lo, hi, progs)
    return host, params, report


def table_h(host, params):
    ops, prog_rows, par_rows = [], [], []
    seen = {}
    for i in range(len(host)):
        if i not in params:
            par_rows.append('    { 0xFFFFu, 0u, 0u, 0, 0, 0u },   /* %2d %s: no host program */' % (i, host[i][0]))
            continue
        name, cand, lo, hi, progs = params[i]
        feat = sum(FBIT[f] for f in cand)
        space = 1
        for x in cand:
            space *= card(x, lo, hi)
        first_prog = len(prog_rows)
        for idx in range(space):
            key, rem = [], idx
            for x in reversed(cand):
                key.append(rem % card(x, lo, hi))
                rem //= card(x, lo, hi)
            key = tuple(reversed(key))
            p = progs.get(key)
            if p is None:
                prog_rows.append((0, 0xFFFF))
                continue
            if p not in seen:
                seen[p] = (len(ops), len(p))
                ops.extend(p)
            prog_rows.append(seen[p])
        par_rows.append('    { 0x%02Xu, %du, %du, %d, %d, %du },   /* %2d %s: key %s%s */'
                        % (feat, space, first_prog, lo, hi, GATE.get(name, 0), i, name, ' x '.join(cand) or 'none',
                           ', gated' if name in GATE else ''))
    out = ['/* host_ramp_table.h -- GENERATED by tools/verify/gen_host_ramps.py; do not edit.',
           ' *',
           ' * The plugin\'s HOST-ROLE set lists (CLAIMS B7): for every panel parameter',
           ' * the sets the host parameter entry (rva 0x3C7AE0, flag 0) makes on a unit',
           ' * -- ramped sets (cell, time index), immediate sets, direct writes -- in',
           ' * the plugin\'s order, per key (the context the list depends on), and where',
           ' * each set\'s value comes from. EXECUTED: probes/host/host_census_v2.py',
           ' * (11282 edits), host_census_v3.py (2632), host_census_flags.py (1800)',
           ' * and host_census_h.py (72); %d ops, %d programs.' % (len(ops), len(prog_rows)),
           ' */',
           '#ifndef JUNO_HOST_RAMP_TABLE_H',
           '#define JUNO_HOST_RAMP_TABLE_H',
           '#include <stdint.h>',
           'typedef struct { uint32_t cell; uint8_t kind, t, src, pad; } jh_op;',
           'typedef struct { uint32_t first; uint32_t count; } jh_prog;',
           'typedef struct { uint32_t feat, nprog, prog0; int32_t lo, hi; uint32_t gate; } jh_param;',
           'enum { JH_G_NONE = 0, JH_G_ARP_ON = 1, JH_G_ARP_TURN_ON = 2 };',
           'enum { JH_RAMP = 0, JH_IMM = 1, JH_WRITE = 2 };',
           'enum { JH_REC = 0, JH_ZERO = 1, JH_ONE = 2, JH_OFF = 3, JH_TAP2 = 4, JH_HOSTV = 5 };',
           'enum { %s };' % ', '.join('JH_F_%s = 0x%02X' % (f, FBIT[f]) for f in FEATS),
           '#define JH_NONE 0xFFFFFFFFu',
           'static const jh_op JH_OPS[%d] = {' % max(len(ops), 1)]
    for k in range(0, len(ops), 4):
        out.append('    ' + ' '.join('{%uu,%d,%d,%d,0},' % (c, kd, t, sr) for kd, c, t, sr in ops[k:k + 4]))
    out.append('};')
    out.append('static const jh_prog JH_PROGS[%d] = {' % max(len(prog_rows), 1))
    for k in range(0, len(prog_rows), 6):
        out.append('    ' + ' '.join('{%du,%s},' % (a, ('JH_NONE' if b == 0xFFFF else '%du' % b))
                                     for a, b in prog_rows[k:k + 6]))
    out.append('};')
    out.append('static const jh_param JH_PARAMS[%d] = {' % len(host))
    out.extend(par_rows)
    out.append('};')
    out.append('#endif /* JUNO_HOST_RAMP_TABLE_H */')
    return '\n'.join(out) + '\n'


def main():
    check = '--check' in sys.argv[1:]
    host, params, report = programs()
    for ln in report:
        print('REPORT: ' + ln)
    outs = [(CELLS_H, ramp_cells_h()), (TABLE_H, table_h(host, params))]
    bad = 0
    for path, text in outs:
        if check:
            old = open(path).read() if os.path.exists(path) else None
            if old != text:
                print('DIFFERS: %s' % os.path.relpath(path, REPO))
                bad = 1
            else:
                print('same: %s' % os.path.relpath(path, REPO))
        else:
            open(path, 'w').write(text)
            print('wrote %s' % os.path.relpath(path, REPO))
    return bad


if __name__ == '__main__':
    sys.exit(main())
