#!/usr/bin/env python3
"""gen_conv_tables.py -- generate src/conv_tables.h: the plugin's render-object table (CLAIMS B13,
docs/HOST_RENDER_LAYER.md), READ FROM THE BOOTED PLUGIN (Unicorn only; two-process rule).

  JUNO_CONV[46]     the table at rva 0xC43C30 the filter lookup (rva 0x343A80) searches: 45 entries
                    {engine rate, host rate, L, M, coefficient vector, render function} and the
                    terminator the lookup leaves the object on when no entry matches. The render
                    function, by rva: 0x344270 identity, 0x343E30 converter, 0x344280 silence.
  JUNO_CONV_V*      the coefficient vectors (global std::vector<float> objects the plugin's static
                    initializers fill before any of its entry points runs), as float bit patterns.
  JUNO_SRATE[128]   the dword table at rva 0x94AB80 the setting listener (rva 0x3222F0) indexes
                    with vm.vs.sampleRate & 0x7F: 0..4 the engine rates, 5 never read (the
                    automatic setting), 6..127 the bytes that follow (EXECUTED: 6 -> 0, 127 ->
                    1634624882).

The plugin is booted at two host rates; the table, every vector and the setting table must be
byte-equal between them (they are static data), or the generator refuses.

    python3 tools/verify/gen_conv_tables.py > src/conv_tables.h"""
import hashlib
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

TABLE_RVA, NENT = 0xC43C30, 46
SRATE_RVA = 0x94AB80
KIND = {0x344270: 0, 0x343E30: 1, 0x344280: 2}      # identity, converter, silence


def read_all(host_rate):
    import host_process_emu as H
    import e2e_emu as E
    h = H.HostProcess()
    h.start(host_rate, 4096, setting=None)
    uc = h.uc
    ents, vecs, order = [], {}, []
    for k in range(NENT):
        raw = bytes(uc.mem_read(E.IB + TABLE_RVA + 32 * k, 32))
        er, hr, L, M = struct.unpack_from('<iiii', raw, 0)
        vp, fn = struct.unpack_from('<QQ', raw, 16)
        if fn - E.IB not in KIND:
            raise SystemExit('entry %d: render function rva 0x%x is none of the three' % (k, fn - E.IB))
        vi = -1
        if vp:
            if vp not in vecs:
                b, e_ = struct.unpack('<QQ', uc.mem_read(vp, 16))
                vecs[vp] = bytes(uc.mem_read(b, e_ - b)) if e_ > b else b''
                order.append(vp)
            vi = order.index(vp)
        ents.append((er, hr, L, M, vi, KIND[fn - E.IB]))
    srate = bytes(uc.mem_read(E.IB + SRATE_RVA, 128 * 4))
    return ents, [vecs[v] for v in order], srate


def main():
    a = read_all(48000.0)
    b = read_all(44100.0)
    if a != b:
        raise SystemExit('the table differs between two boots: not static data -- refusing')
    ents, vecs, srate = a
    blob = b''.join(struct.pack('<iiiiii', *e) for e in ents) + b''.join(vecs) + srate
    out = ['/* conv_tables.h -- GENERATED by tools/verify/gen_conv_tables.py from the booted plugin;',
           ' * do not edit. The render-object table (rva 0xC43C30), its coefficient vectors and the',
           ' * engine-rate setting table (rva 0x94AB80). CLAIMS B13, docs/HOST_RENDER_LAYER.md. */',
           '#ifndef JUNO_CONV_TABLES_H', '#define JUNO_CONV_TABLES_H', '#include <stdint.h>',
           '#define JUNO_CONV_SHA256 "%s"' % hashlib.sha256(blob).hexdigest(),
           'typedef struct { int32_t engine, host, L, M, vec, kind; } juno_conv_entry;   /* kind: JUNO_RO_* (juno_conv.h) */',
           '#define JUNO_CONV_N %d          /* entries the lookup searches; [JUNO_CONV_N] is the terminator */' % (NENT - 1),
           '#define JUNO_CONV_NVEC %d' % len(vecs)]
    for i, v in enumerate(vecs):
        n = len(v) // 4
        words = struct.unpack('<%dI' % n, v) if n else ()
        out.append('static const uint32_t JUNO_CONV_V%d[%d] = {' % (i, max(n, 1)))
        if not n:
            out.append('    0u   /* an empty vector (size 0) */')
        for r in range(0, n, 8):
            out.append('    ' + ', '.join('0x%08xu' % w for w in words[r:r + 8]) + ',')
        out.append('};')
    out.append('static const uint32_t *const JUNO_CONV_VEC[JUNO_CONV_NVEC] = { %s };' % ', '.join(
        'JUNO_CONV_V%d' % i for i in range(len(vecs))))
    out.append('static const int32_t JUNO_CONV_VLEN[JUNO_CONV_NVEC] = { %s };' % ', '.join(
        '%d' % (len(v) // 4) for v in vecs))
    out.append('static const juno_conv_entry JUNO_CONV[JUNO_CONV_N + 1] = {')
    for e in ents:
        out.append('    { %d, %d, %d, %d, %d, %d },' % e)
    out.append('};')
    sr = struct.unpack('<128i', srate)
    out.append('static const int32_t JUNO_SRATE[128] = {')
    for r in range(0, 128, 8):
        out.append('    ' + ', '.join('%d' % x for x in sr[r:r + 8]) + ',')
    out.append('};')
    out.append('#endif')
    sys.stdout.write('\n'.join(out) + '\n')
    sys.stderr.write('%d entries, %d vectors (%s floats), sha256 %s\n' % (
        len(ents), len(vecs), '+'.join(str(len(v) // 4) for v in vecs), hashlib.sha256(blob).hexdigest()))
    return 0


if __name__ == '__main__':
    sys.exit(main())
