import pickle
SP='/tmp/claude-0/-home-user-jn60c99/89f5fa0d-6fc0-55d6-a056-fe6fb14fdde6/scratchpad'
L=pickle.load(open(SP+'/finefx_delay_rates.pkl','rb'))
RATES=[44100,48000,88200,96000]
# verify clamp: entry[max]==entry[max+1..255]
def check_clamp(nm, cell, mx, rate=44100):
    arr=L[nm][rate][cell]
    return all(arr[v]==arr[mx] for v in range(mx,256))
HC_CELLS=[102368,102384,102400,102416,102432,102464,102496]
assert all(check_clamp('DELAY HIGH CUT',c,14) for c in HC_CELLS), "HC clamp!=14"
assert check_clamp('DELAY LF DAMP',102640,81), "LFDMP clamp!=81"
assert check_clamp('DELAY HF DAMP',102672,81), "HFDMP clamp!=81"
assert check_clamp('DELAY LF DAMP FREQ',102608,10), "LFDF clamp!=10"
assert check_clamp('DELAY HF DAMP FREQ',102656,13), "HFDF clamp!=13"
# also verify HC rate-independence across all 4 rates
for c in HC_CELLS+[102640,102672]:
    nm={102640:'DELAY LF DAMP',102672:'DELAY HF DAMP'}.get(c,'DELAY HIGH CUT')
    a=[L[nm][r][c] for r in RATES]
    assert all(a[0]==a[i] for i in range(4)), "%s cell %d NOT rate-indep"%(nm,c)
print("clamp + rate-indep checks PASS")

def hexrow(vals): return ", ".join("0x%08xu"%v for v in vals)
out=[]
out.append("/* GENERATED by scratchpad/gen_finefx_c.py from the plugin's own DELAY")
out.append(" * fine-FX setters (dispatch 1180/1182..1185) executed under Unicorn at all")
out.append(" * four host rates (scratchpad/finefx_delay_rates.py -> finefx_delay_rates.pkl).")
out.append(" * DO NOT EDIT BY HAND. Each table row = the exact float32 coefficient the")
out.append(" * plugin writes for that param byte (clamped to the leaf range). Byte 0 of")
out.append(" * every table == the plugin default byte, so at the factory-default value")
out.append(" * these equal delay_recall.c's frozen FILT[]/put_rate constants (proven). */")
out.append("")
# HIGH CUT: 15 bytes x 7 cells, rate-independent
out.append("/* DELAY HIGH CUT (roff 3059, int1x7, range 0..14): 7 cells, rate-independent. */")
out.append("static const int      DLY_HC_CELLS[7] = {%s};"%", ".join(str(c) for c in HC_CELLS))
out.append("static const uint32_t DLY_HC[15][7] = {")
for b in range(15):
    row=[L['DELAY HIGH CUT'][44100][c][b] for c in HC_CELLS]
    out.append("  {%s}, /* byte %2d */"%(hexrow(row),b))
out.append("};")
out.append("")
# LF DAMP / HF DAMP: 82 bytes x 1 cell, rate-independent
for nm,cell,vn in [('DELAY LF DAMP',102640,'DLY_LFDMP'),('DELAY HF DAMP',102672,'DLY_HFDMP')]:
    out.append("/* %s (int8x4, range 0..81): cell %d, rate-independent. */"%(nm,cell))
    out.append("static const uint32_t %s[82] = {"%vn)
    arr=[L[nm][44100][cell][b] for b in range(82)]
    for i in range(0,82,8):
        out.append("  "+hexrow(arr[i:i+8])+",")
    out.append("};")
    out.append("")
# LF DAMP FREQ / HF DAMP FREQ: rate-armed [4][N]
for nm,cell,vn,mx in [('DELAY LF DAMP FREQ',102608,'DLY_LFDF',11),
                      ('DELAY HF DAMP FREQ',102656,'DLY_HFDF',14)]:
    out.append("/* %s (int8x4, range 0..%d): cell %d, RATE-DEPENDENT (arms 44100/48000/88200/96000). */"%(nm,mx-1,cell))
    out.append("static const uint32_t %s[4][%d] = {"%(vn,mx))
    for ri,r in enumerate(RATES):
        arr=[L[nm][r][cell][b] for b in range(mx)]
        out.append("  {%s}, /* %d */"%(hexrow(arr),r))
    out.append("};")
    out.append("")
open('/home/user/jn60c99/src/finefx_tables.h','w').write("\n".join(out)+"\n")
print("wrote src/finefx_tables.h (%d lines)"%len(out))
