#!/usr/bin/env python3
"""gen_teensy_golden.py — emit tests/teensy_golden.h: a standalone golden corpus
for the Teensy 4.1 (44.1 kHz) port.

Each scenario is (222-byte patch blob, note event list, render length) plus the
FNV-1a-64 hash of the port's stereo output. The port is proven bit-exact to the
plugin at 44100 (docs/CLAIMS.md A2/A8), so this golden == the plugin's output.
The on-device test (tests/test_teensy_golden.c) replays each scenario through the
SAME C engine and checks the hash: a match proves the ARM build reproduces the
x86 reference (hence the plugin) bit-for-bit. Fully self-contained — no bank file
needed on the target.

Run: python3 tools/verify/gen_teensy_golden.py  (writes tests/teensy_golden.h)
"""
import ctypes, struct, sys
sys.path.insert(0, '/home/user/jn60c99/tools/verify')
import e2e_emu as E

RATE = 44100.0
BANK = E.bank_bytes()
H, S, BO = E.HEADER, E.STRIDE, E.BLOB_OFF

lib = ctypes.CDLL('/home/user/jn60c99/libjuno.so')
lib.juno_gui_create.restype = ctypes.c_void_p
lib.juno_gui_create.argtypes = [ctypes.c_float, ctypes.c_int]
lib.juno_gui_apply_bank.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_int, ctypes.c_int]
lib.juno_gui_note_on.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_int]
lib.juno_gui_note_off.argtypes = [ctypes.c_void_p, ctypes.c_int]
lib.juno_gui_render.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_int]

def blob_of(patch):
    off = H + patch * S + BO
    return BANK[off:off + 704]

def fnv1a64(b):
    h = 0xcbf29ce484222325
    for x in b:
        h ^= x; h = (h * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return h

def render(patch, events, n):
    c = lib.juno_gui_create(ctypes.c_float(RATE), 0)
    lib.juno_gui_apply_bank(c, BANK, len(BANK), patch)
    cur = 0; buf = (ctypes.c_float * (2 * n))(); pos = 0
    out = bytearray()
    for (at, kind, note, vel) in events:
        if at > cur:
            b = (ctypes.c_float * (2 * (at - cur)))(); lib.juno_gui_render(c, b, at - cur)
            out += bytes(b); cur = at
        if kind == 1: lib.juno_gui_note_on(c, note, vel)
        else: lib.juno_gui_note_off(c, note)
    if n > cur:
        b = (ctypes.c_float * (2 * (n - cur)))(); lib.juno_gui_render(c, b, n - cur); out += bytes(b)
    return bytes(out)

# (name, patch, events[(sample,kind,note,vel)], nframes)  kind: 1=on 0=off
# Patch types: 5 pluck (MONO-stored), 31 (MONO), 61/63 (UNISON), 0/22 varied, 20 pad.
SCEN = [
    ("pluck_note",   5,  [(0,1,60,100)], 12000),
    ("chord_rel",   22,  [(0,1,48,100),(0,1,55,100),(0,1,60,100),(6000,0,48,0),(6000,0,55,0),(6000,0,60,0)], 14000),
    ("bass_low",    31,  [(0,1,36,110)], 12000),
    ("unison61",    61,  [(0,1,64,100)], 12000),
    ("unison63",    63,  [(0,1,60,90)],  12000),
    ("pad_sustain", 20,  [(0,1,72,80)],  16000),
    ("restrike",     0,  [(0,1,60,100),(4000,0,60,0),(8000,1,60,100)], 14000),
    ("high_note",   40,  [(0,1,96,100)], 10000),
]

def main():
    rows = []
    for (name, patch, events, n) in SCEN:
        data = render(patch, events, n)
        h = fnv1a64(data)
        first = struct.unpack("<2I", data[:8])
        rows.append((name, patch, events, n, h, first))
        print(f"{name:14s} patch {patch:2d}  n={n:5d}  hash={h:016x}", flush=True)

    with open('/home/user/jn60c99/tests/teensy_golden.h', 'w') as f:
        f.write("/* teensy_golden.h — GENERATED by tools/verify/gen_teensy_golden.py.\n")
        f.write(" * Standalone 44.1 kHz golden corpus for the Teensy 4.1 port. Each scenario\n")
        f.write(" * embeds its patch blob + note events + expected FNV-1a-64 output hash. The\n")
        f.write(" * hash is of the port's stereo float output, which is bit-exact to the plugin\n")
        f.write(" * (docs/CLAIMS.md). tests/test_teensy_golden.c replays each and checks the hash. */\n")
        f.write("#ifndef TEENSY_GOLDEN_H\n#define TEENSY_GOLDEN_H\n#include <stdint.h>\n\n")
        f.write("#define TG_RATE 44100.0f\n")
        f.write("typedef struct { int at, kind, note, vel; } tg_event;\n")
        f.write("typedef struct { const char *name; int patch; const unsigned char *blob;\n")
        f.write("                 const tg_event *ev; int nev; int nframes; uint64_t hash;\n")
        f.write("                 uint32_t first_l, first_r; } tg_scenario;\n\n")
        for i, (name, patch, events, n, h, first) in enumerate(rows):
            blob = blob_of(patch)
            f.write(f"static const unsigned char tg_blob_{i}[704] = {{")
            f.write(",".join(str(x) for x in blob)); f.write("};\n")
            f.write(f"static const tg_event tg_ev_{i}[] = {{")
            f.write(",".join("{%d,%d,%d,%d}" % e for e in events)); f.write("};\n")
        f.write("\nstatic const tg_scenario tg_scenarios[] = {\n")
        for i, (name, patch, events, n, h, first) in enumerate(rows):
            f.write(f'  {{"{name}",{patch},tg_blob_{i},tg_ev_{i},{len(events)},{n},'
                    f'0x{h:016x}ULL,0x{first[0]:08x}u,0x{first[1]:08x}u}},\n')
        f.write("};\n")
        f.write(f"#define TG_NSCEN {len(rows)}\n\n#endif\n")
    print(f"wrote tests/teensy_golden.h ({len(rows)} scenarios)")

    # Same corpus as JSON, for the WASM verifier (tools/verify/wasm_golden.mjs).
    import json
    js = [{"name": name, "patch": patch, "blob": list(blob_of(patch)),
           "events": [list(e) for e in events], "nframes": n, "hash": f"{h:016x}"}
          for (name, patch, events, n, h, first) in rows]
    with open('/home/user/jn60c99/tools/verify/teensy_golden.json', 'w') as f:
        json.dump(js, f)
    print(f"wrote tools/verify/teensy_golden.json")

if __name__ == '__main__':
    main()
