#!/usr/bin/env python3
"""gen_midi_tables.py -- generate src/midi_tables.h: the plugin's MIDI controller intake tables
(CLAIMS B16, docs/HOST_RENDER_LAYER.md), EXECUTED IN THE BOOTED PLUGIN (Unicorn only; two-process
rule). The plugin is booted as a host does (tools/verify/host_process_emu.py) at two host rates;
every table must be equal between the boots, or the generator refuses.

  JUNO_MIDI_BASE     the first VST3 MIDI-mapping parameter id (core +48, read by process(), rva
                     0x34A380): id - base = 0..127 CC n, 128 channel aftertouch, 129 pitch bend.
  JUNO_MIDI_PARAM[]  the core's parameter vector (core +24, 24-byte entries): per entry the id
                     (rva 0x319C50, EXECUTED), the range the parameter object gives (its vt+96 info:
                     +44 min, +48 max, EXECUTED), the entry's byte +16 (the CC value conversion's
                     truncate flag, rva 0x31A850) and the port's host index for the id
                     (src/juno_state_tables.h; the generator refuses an id it lacks).
  JUNO_CC_MAP[128]   CC number -> vector entry, -1 none (rva 0x319A60 EXECUTED for every n): the
                     plugin's default CC assignments (no learn slot open at boot).
  JUNO_MIDI_IDMAP[]  the global id -> vector entry map (rva 0xCB04F8) the render driver searches for
                     a kind-1 record (rva 0x319AB0), walked; every key cross-checked by executing the
                     lookup, and ids outside it (every state id, every host id, the MIDI ids) must
                     return -1 there unless they are keys.

    python3 tools/verify/gen_midi_tables.py > src/midi_tables.h"""
import hashlib
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

CC_LOOKUP, ID_OF, ID_LOOKUP = 0x319A60, 0x319C50, 0x319AB0
IDMAP_RVA = 0xCB04F8


def state_ids():
    src = open(os.path.join(REPO, 'src', 'juno_state_tables.h')).read()
    blk = src[src.index('JUNO_STATE_ENT[JUNO_STATE_N]'):]
    blk = blk[:blk.index('};')]
    out = {}
    for m in re.finditer(r'\{\s*0x([0-9A-Fa-f]+)u,\s*([A-Z_]+|-?\d+),', blk):
        out[int(m.group(1), 16)] = m.group(2)
    return out


def host_ids():
    src = open(os.path.join(REPO, 'src', 'juno_hostparams.c')).read()
    return sorted(set(int(m.group(1), 16) for m in re.finditer(r'0x([0-9A-Fa-f]{6,8})', src)))


def read_all(host_rate):
    import host_process_emu as H
    h = H.HostProcess()
    h.start(host_rate, 512)
    uc = h.uc
    q = lambda a: struct.unpack('<Q', uc.mem_read(a, 8))[0]
    i32 = lambda a: struct.unpack('<i', uc.mem_read(a, 4))[0]
    s32 = lambda x: x - (1 << 32) if x & 0x80000000 else x
    m = h.core + 24
    base = i32(h.core + 48)
    if i32(m + 64) >= 0:
        raise SystemExit('a MIDI-learn slot is open at boot (core+88 = %d)' % i32(m + 64))
    vb, ve = q(m), q(m + 8)
    n = (ve - vb) // 24
    params = []
    for k in range(n):
        obj = q(vb + 24 * k)
        pid = h.call(H.IB + ID_OF, rcx=m, rdx=k, count=2_000_000) & 0xFFFFFFFF
        info = h.call(q(q(obj) + 96), rcx=obj, count=2_000_000)
        params.append((pid, i32(info + 44), i32(info + 48), uc.mem_read(vb + 24 * k + 16, 1)[0]))
    ccmap = [s32(h.call(H.IB + CC_LOOKUP, rcx=m, rdx=c, count=2_000_000) & 0xFFFFFFFF) for c in range(128)]
    head = q(H.IB + IDMAP_RVA)
    keys = []

    def walk(nd):
        if uc.mem_read(nd + 25, 1)[0]:
            return
        walk(q(nd))
        keys.append((struct.unpack('<I', uc.mem_read(nd + 28, 4))[0], i32(nd + 32)))
        walk(q(nd + 16))
    walk(q(head + 8))
    if len(keys) != q(H.IB + IDMAP_RVA + 8):
        raise SystemExit('id map: walked %d nodes, size says %d' % (len(keys), q(H.IB + IDMAP_RVA + 8)))
    kd = dict(keys)
    probe = set(kd) | set(state_ids()) | set(host_ids()) | {base + i for i in range(130)} | {0, 0xFFFFFFFF}
    for pid in sorted(probe):
        got = s32(h.call(H.IB + ID_LOOKUP, rcx=m, rdx=pid, count=2_000_000) & 0xFFFFFFFF)
        if got != kd.get(pid, -1):
            raise SystemExit('id map: lookup(0x%x) = %d, walk says %d' % (pid, got, kd.get(pid, -1)))
    return base, params, ccmap, keys


def main():
    a = read_all(48000.0)
    b = read_all(44100.0)
    if a != b:
        raise SystemExit('the MIDI tables differ between two boots -- refusing')
    base, params, ccmap, keys = a
    sid = state_ids()
    for pid, _, _, _ in params:
        if pid not in sid:
            raise SystemExit('vector id 0x%x is not a state entry (src/juno_state_tables.h)' % pid)
    blob = struct.pack('<I', base) + b''.join(struct.pack('<IiiB', *p) for p in params) + \
        struct.pack('<128i', *ccmap) + b''.join(struct.pack('<Ii', *k) for k in keys)
    out = ['/* midi_tables.h -- GENERATED by tools/verify/gen_midi_tables.py from the booted plugin;',
           ' * do not edit. The MIDI controller intake (CLAIMS B16, docs/HOST_RENDER_LAYER.md): the',
           ' * VST3 MIDI-mapping base, the core\'s parameter vector, the default CC assignments and the',
           ' * id map the render driver searches for a kind-1 record. */',
           '#ifndef JUNO_MIDI_TABLES_H', '#define JUNO_MIDI_TABLES_H', '#include <stdint.h>',
           '#include "juno_state_tables.h"',
           '#define JUNO_MIDI_SHA256 "%s"' % hashlib.sha256(blob).hexdigest(),
           '#define JUNO_MIDI_BASE 0x%08Xu     /* id - base: 0..127 CC, 128 channel aftertouch, 129 bend */' % base,
           '/* id; the range its object gives (vt+96 info +44 / +48); the CC conversion\'s truncate flag',
           ' * (entry byte +16, rva 0x31A850); the port\'s host index for the id (JUNO_STATE_ENT) */',
           'typedef struct { uint32_t id; int32_t min, max; uint8_t trunc; int16_t host; } juno_midi_param;',
           '#define JUNO_MIDI_PARAM_N %d' % len(params),
           'static const juno_midi_param JUNO_MIDI_PARAM[JUNO_MIDI_PARAM_N] = {']
    for pid, lo, hi, fl in params:
        out.append('    { 0x%08Xu, %d, %d, %d, %s },' % (pid, lo, hi, fl, sid[pid]))
    out.append('};')
    out.append('/* CC number -> JUNO_MIDI_PARAM entry, -1: none (rva 0x319A60, the boot\'s map) */')
    out.append('static const int8_t JUNO_CC_MAP[128] = {')
    for r in range(0, 128, 16):
        out.append('    ' + ', '.join('%d' % x for x in ccmap[r:r + 16]) + ',')
    out.append('};')
    out.append('/* the id map (rva 0xCB04F8), ascending ids: id -> JUNO_MIDI_PARAM entry */')
    out.append('typedef struct { uint32_t id; int32_t entry; } juno_midi_idmap;')
    out.append('#define JUNO_MIDI_IDMAP_N %d' % len(keys))
    out.append('static const juno_midi_idmap JUNO_MIDI_IDMAP[JUNO_MIDI_IDMAP_N] = {')
    for k, v in keys:
        out.append('    { 0x%08Xu, %d },' % (k, v))
    out.append('};')
    out.append('#endif')
    sys.stdout.write('\n'.join(out) + '\n')
    sys.stderr.write('base 0x%x, %d params, %d CCs mapped, %d ids in the map, sha256 %s\n' % (
        base, len(params), sum(1 for x in ccmap if x >= 0), len(keys), hashlib.sha256(blob).hexdigest()))
    return 0


if __name__ == '__main__':
    sys.exit(main())
