#!/usr/bin/env python3
"""hostparams_check.py -- src/juno_hostparams.c (the 79 host parameters: name, record offset, type, range,
default) re-derived from the plugin's own data (task #62: its generator chain, two scratch scripts and a
json, was lost with an old container).

Each row against:
  src/juno_state_tables.h   JUNO_PATCH_EV (generated by gen_state_tables.py from the plugin's own patch
                            load, regen-checked): the row's record offset and decode, by host index
                            JUNO_STATE_ENT (the plugin's initialize): the row's default, by host index
  truth/Script.xml          the value leaf of the row's name: its type, range and default
Host-only rows (type 3: the H floats; type 4: MASTER TUNE, a SYSTEM leaf) are checked where a source
names them. Pure reading; no Unicorn, no port code.

usage: python3 tools/repro/hostparams_check.py [--tooth]    (--tooth: one row's default moved, must FAIL)
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(REPO, 'tools', 'verify'))
TOOTH = '--tooth' in sys.argv
TYPE_OF_DEC = {0: 0, 1: 1, 2: 2}          # JUNO_DEC_INT1X7 / INT2X4 / INT8X4 -> the row's type
# an int8x4 field is 8 nibbles; the port's row points at its low byte (the last nibble pair: the field's
# start + 6, the header's "reads the low byte as a nibble pair at roff/roff+1"); the plugin's patch load
# names the field's start
LOW_BYTE = {0: 0, 1: 0, 2: 6}
# the one row whose host range is not its record leaf's, each with its source
HOST_RANGE = {'HPF TYPE': ((0, 1), "the plugin's parameter database (host_edit_gate.py: a value outside it reaches "
                                   "no setter, EXECUTED); the record leaf's range is 0..8")}
XML_TYPE = {'int1x7': 0, 'int2x4': 1, 'int8x4': 2}


def rows():
    src = open(os.path.join(REPO, 'src', 'juno_hostparams.c')).read()
    out = [(n, sec, int(r), int(t), int(a), int(b), int(d)) for n, sec, r, t, a, b, d in re.findall(
        r'\{"([^"]*)"\s*,"([^"]*)"\s*,\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+)\}', src)]
    if TOOTH:
        n, sec, r, t, a, b, d = out[5]
        out[5] = (n, sec, r, t, a, b, d + 1)                       # TOOTH: one default moved
    return out


def state_tables():
    src = open(os.path.join(REPO, 'src', 'juno_state_tables.h')).read()
    dec = {m: i for i, m in enumerate(('JUNO_DEC_INT1X7', 'JUNO_DEC_INT2X4', 'JUNO_DEC_INT8X4', 'JUNO_DEC_INT4X4'))}
    a = src.index('JUNO_PATCH_EV[JUNO_PATCH_EV_N]')
    ev = {}
    for i, h, r, d in re.findall(r'\{ (0x[0-9A-F]+)u, (-?\d+), (\d+)u, (JUNO_DEC_\w+) \}', src[a:src.index('};', a)]):
        if int(h) >= 0:
            ev[int(h)] = (int(r), dec[d])
    b = src.index('JUNO_STATE_ENT[JUNO_STATE_N]')
    st = {}
    for i, h, m, d in re.findall(r'\{ (0x[0-9A-F]+)u, (-?\d+), (0x[0-9A-F]+)u, (-?\d+) \}', src[b:src.index('};', b)]):
        if int(h) >= 0:
            st[int(h)] = int(d)
    return ev, st


def xml_leaves():
    import truth
    leaves = {}
    for v in ET.parse(truth.SCRIPT_XML).getroot().iter('value'):
        n, t, r, d = (v.findtext(k) for k in ('name', 'type', 'range', 'default'))
        if n and t and r:
            leaves.setdefault(n.strip(), []).append((t.strip(), r.strip(), (d or '').strip()))
    return leaves


def main():
    hp = rows()
    ev, st = state_tables()
    xl = xml_leaves()
    bad, notes = [], []
    for k, (n, sec, roff, typ, mn, mx, de) in enumerate(hp):
        if k in ev:
            r, d = ev[k]
            if typ in (0, 1, 2) and (roff, typ) != (r + LOW_BYTE[typ], TYPE_OF_DEC.get(d, -1)):
                bad.append('%s: offset/type %d/%d, the plugin\'s patch load %d/%d' % (n, roff, typ, r + LOW_BYTE[typ],
                                                                                  TYPE_OF_DEC.get(d, -1)))
            if typ == 4 and roff != r:
                bad.append('%s: offset %d, the plugin\'s patch load %d' % (n, roff, r))
        elif typ in (0, 1, 2):
            bad.append('%s: no patch-load event names host index %d' % (n, k))
        if k in st and typ in (0, 1, 2) and st[k] != de:
            bad.append('%s: default %d, the plugin\'s initialize %d' % (n, de, st[k]))
        lv = xl.get(n)
        if n in HOST_RANGE:
            if (mn, mx) != HOST_RANGE[n][0]:
                bad.append('%s: range %d,%d, %s: %s' % (n, mn, mx, HOST_RANGE[n][0], HOST_RANGE[n][1]))
            notes.append(n + ' (range: ' + HOST_RANGE[n][1] + ')')
        elif lv:
            ok = [x for x in lv if x[1] == '%d,%d' % (mn, mx) and (x[2] == '' or int(x[2]) == de)
                  and (typ not in XML_TYPE.values() or XML_TYPE.get(x[0], typ) == typ)]
            if not ok:
                bad.append('%s: range %d,%d default %d type %d; Script.xml %s' % (n, mn, mx, de, typ, lv))
        else:
            notes.append(n)
    print('hostparams_check: %d rows; %d against the plugin\'s patch load, %d against its initialize, %d against '
          'Script.xml (%s otherwise: %s)' % (len(hp), sum(1 for k in range(len(hp)) if k in ev),
                                                  sum(1 for k in range(len(hp)) if k in st), len(hp) - len(notes),
                                                  len(notes), ', '.join(notes) or '-'))
    for b in bad[:20]:
        print('  DIFFERS ' + b)
    if TOOTH:
        print('hostparams_check --tooth: %s' % ('BITES' if bad else 'DID NOT BITE'))
        return 0 if bad else 1
    print('hostparams_check: %s' % ('GREEN' if not bad and len(hp) == 79 else 'RED'))
    return 0 if not bad and len(hp) == 79 else 1


if __name__ == '__main__':
    sys.exit(main())
