#!/usr/bin/env python3
"""gen_fx_coefs.py -- freeze JUNO-60 FX coefficient sets for jetsynth.

The engine_b FX modules (eb_chorus, eb_delay, eb_reverb) take coefficient
structs that only the proven recall can build. This tool runs that recall --
the certified `standalone` shim library, the same one
tools/engineb/gen_listen_coefs.py uses -- at 48 kHz on factory patches, and
freezes the resulting structs into jetsynth/gen/jet_fx_coefs.h.

Nothing is typed by hand and nothing is fitted: every number in the header is
the recall's own float, printed as a hex float by fx_emit.c.

  gen_fx_coefs.py scan            one summary line per factory patch
  gen_fx_coefs.py emit P1 P2 ...  write the header for those patches
  env FX_RATE (default 48000) and FX_OUT (default jetsynth/gen/jet_fx_coefs.h)
"""
import ctypes, os, subprocess, sys, tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path[:0] = [os.path.join(REPO, "tools", "verify"),
                os.path.join(REPO, "tools", "trackb"),
                os.path.join(REPO, "tools", "engineb")]
import truth, null_ab, null_b  # noqa: E402

RATE = float(os.environ.get("FX_RATE", "48000"))
OUT = os.environ.get("FX_OUT", os.path.join(REPO, "jetsynth", "gen", "jet_fx_coefs.h"))


def build(tmp):
    so = os.path.join(tmp, "eb.so")
    null_b.build(so, ["standalone"])
    exe = os.path.join(tmp, "fx_emit")
    cmd = ["cc"] + null_b.CFLAGS + ["-I" + os.path.join(REPO, "engine_b"),
                                    "-I" + os.path.join(REPO, "src"),
                                    "-o", exe,
                                    os.path.join(REPO, "jetsynth", "tools", "fx_emit.c")]
    subprocess.run(cmd, check=True)
    return null_ab.load(so), exe


def grab(lib, bank, patch, tmp):
    sizes = (ctypes.c_int * 20)()
    lib.ebsh_dump_sizes(sizes)
    nmc = sizes[1]
    c = lib.juno_gui_create(ctypes.c_float(RATE), 0)
    lib.juno_gui_apply_bank(c, bank, len(bank), patch)
    buf = (ctypes.c_float * 4096)()
    lib.juno_gui_render(c, buf, 64)       # coefficients are built on render
    mc = (ctypes.c_ubyte * nmc)()
    lib.ebsh_dump_blob(1, mc)
    taps = (ctypes.c_ubyte * (34 * 4))()
    lib.ebsh_dump_blob(23, taps)
    lib.juno_gui_destroy(c)
    pm = os.path.join(tmp, "mc%d.bin" % patch)
    pt = os.path.join(tmp, "taps%d.bin" % patch)
    open(pm, "wb").write(bytes(mc))
    open(pt, "wb").write(bytes(taps))
    return pm, pt, nmc


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "scan"
    tmp = tempfile.mkdtemp(prefix="jetfx_")
    lib, exe = build(tmp)
    bank = open(truth.BANK, "rb").read()
    if mode == "scan":
        for p in range(64):
            pm, pt, n = grab(lib, bank, p, tmp)
            r = subprocess.run([exe, pm, pt, str(n), "summary"],
                               capture_output=True, text=True, check=True)
            print("patch %2d: %s" % (p, r.stdout.strip()))
        return
    patches = [int(x) for x in sys.argv[2:]]
    body = []
    for p in patches:
        pm, pt, n = grab(lib, bank, p, tmp)
        r = subprocess.run([exe, pm, pt, str(n), "emit", "P%d" % p],
                           capture_output=True, text=True, check=True)
        s = subprocess.run([exe, pm, pt, str(n), "summary"],
                           capture_output=True, text=True, check=True)
        body.append("/* factory patch %d @ %d Hz: %s */\n%s"
                    % (p, int(RATE), s.stdout.strip(), r.stdout))
    with open(OUT, "w") as f:
        f.write("/* jet_fx_coefs.h -- GENERATED by jetsynth/tools/gen_fx_coefs.py.\n"
                " * DO NOT EDIT. The JUNO-60 FX coefficient sets, built by the\n"
                " * proven recall (standalone shim) at %d Hz and frozen bit-exact\n"
                " * (hex floats). Patches: %s. */\n"
                "#ifndef JET_FX_COEFS_H\n#define JET_FX_COEFS_H\n"
                "#include \"eb_chorus.h\"\n#include \"eb_delay.h\"\n"
                "#include \"eb_reverb.h\"\n#define JET_FX_RATE %d\n\n"
                % (int(RATE), patches, int(RATE)))
        f.write("\n".join(body))
        f.write("\n#endif\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
