#!/usr/bin/env python3
"""gen_tables.py -- bake pyNA's source spectra into jetsynth/gen/jet_tables.h.

RUN UNDER THE ORACLE VENV:  $JET_ORACLE/venv/bin/python jetsynth/tools/gen_tables.py

Grid: power setting TS (16) x flight Mach M_0 (5) x polar angle theta (19).
Per grid point, all from pyNA through pyna_oracle.py (gated vs NASA ANOPP):
  JET   jet mixing + jet shock      1/3-octave SPL, 24 bands, dB re 20 uPa at r_0
  CORE  combustor
  FAN   fan inlet + discharge broadband (tones removed)
  BUZZ  fan combination tones (buzz-saw), 1/3-octave        -- NOT NASA-verified
  TONE  BPF harmonics 1..10, inlet + discharge, dB            (liner applied)
Plus per (TS, M_0): fan rpm.  Plus air absorption (dB/m, sea level) per band.

ENGINE DATA: the NPSS deck pyNA ships for the NASA STCA engine
(cases/stca/engine/engine_deck_stca.csv, z = 0). Its fan_N column is
inconsistent with NASA's own STCA time series (3,233 vs 8,727 rpm at
TS 0.9, M 0: 202 m/s tip speed could not do the 62 K fan work). The deck's
SHAPE is kept and N is scaled so TS 0.9 / M 0 matches NASA's 8,726.7 rpm.
That scale is INFERRED, and it is the only number here not taken as-is.
"""
import os, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import pyna_oracle as o  # noqa: E402
import pandas as pd      # noqa: E402

OUT = os.path.join(os.path.dirname(HERE), "gen", "jet_tables.h")
TS = [round(0.30 + 0.05 * i, 2) for i in range(16)]        # 0.30 .. 1.05
M0 = [0.0, 0.1, 0.2, 0.3, 0.4]
TH = list(range(0, 181, 10))
NH = 10
N_SCALE = 8726.699976 / 3233.27818   # NASA Engine_to t=0 / deck (TS .9, M 0)
DB_OFF, DB_STEP = 20.0, 0.5          # uint8 code = (dB - 20) / 0.5, 20..147.5
# jet can exceed 147.5 at 1 ft; store jet/core/fan with a 16-bit code instead
Q = 100.0                            # uint16 code = dB * 100


def deck_row(d, ts, m):
    r = d[(d["z [m]"] == 0) & (np.isclose(d["M_0 [-]"], m)) &
          (np.isclose(d["T/TMAX [-]"], ts))]
    if len(r) != 1:
        raise SystemExit("deck has no unique row for TS %s M %s" % (ts, m))
    r = r.iloc[0]
    return {
        "Jet V [m/s]": r["jet_V [m/s]"], "Jet rho [kg/m3]": r["jet_rho [kg/m3]"],
        "Jet A [m2]": r["jet_A [m2]"], "Jet Tt [K]": r["jet_Tt [K]"],
        "Jet M [-]": r["jet_M [-]"],
        "Core mdot [kg/s]": r["core_mdot_in [kg/s]"], "Core Tti [K]": r["core_Tt_in [K]"],
        "Core Ttj [K]": r["core_Tt_out [K]"], "Core Pt [Pa]": r["core_Pt_in [Pa]"],
        "Core DT_t [K]": r["core_DT_t [K]"],
        "Fan delta T [K]": r["fan_DTt [K]"], "Fan mdot in [kg/s]": r["fan_mdot_in [kg/s]"],
        "Fan N [rpm]": r["fan_N [rpm]"] * N_SCALE, "Fan A [m2]": r["fan_A [m2]"],
        "Fan d [m]": r["fan_d [m]"], "TS [-]": ts,
    }


def main():
    p = o.load()
    sl = p.sealevel_atmosphere
    d = pd.read_csv(os.path.join(o.PKG, "cases", "stca", "engine", "engine_deck_stca.csv"))
    nb = len(p.noise_data.f)
    jet = np.zeros((len(TS), len(M0), len(TH), nb))
    core, fan, buzz = jet.copy(), jet.copy(), jet.copy()
    tone = np.zeros((len(TS), len(M0), len(TH), NH))
    rpm = np.zeros((len(TS), len(M0)))
    for i, ts in enumerate(TS):
        for k, m in enumerate(M0):
            eng = deck_row(d, ts, m)
            rpm[i, k] = eng["Fan N [rpm]"]
            amb = {"c_0": sl["c_0"], "T_0": sl["T_0"], "p_0": sl["p_0"],
                   "rho_0": sl["rho_0"], "M_0": m}
            for j, th in enumerate(TH):
                sp = o.spectra(p, eng, amb, th)
                fp = o.fan_parts(p, eng, amb, th, n_harm=NH)
                db = lambda ms: o.spl_db(np.clip(ms, 1e-30, None), amb)
                jet[i, k, j] = db(sp["jet_mixing"] + sp["jet_shock"])
                core[i, k, j] = db(sp["core"])
                fan[i, k, j] = db(fp["bb"]["fan_inlet"] + fp["bb"]["fan_discharge"])
                buzz[i, k, j] = db(np.clip(fp["ct"]["fan_inlet"] + fp["ct"]["fan_discharge"], 0, None))
                for h in range(NH):
                    w = fp["tones"]["fan_inlet"][h][1] + fp["tones"]["fan_discharge"][h][1]
                    tone[i, k, j, h] = db(np.array([w]))[0]
        print("TS %.2f done" % ts, flush=True)
    absorb = np.ravel(p.noise_data.abs_f(p.noise_data.f, 0.0))
    B = int(p.airframe.B_fan)

    def arr(name, a, ctype="uint16_t"):
        v = np.clip(np.round(np.ravel(a) * Q), 0, 65535).astype(int)
        body = ",".join(str(x) for x in v)
        return "static const %s %s[%d] = {%s};\n" % (ctype, name, v.size, body)

    with open(OUT, "w") as f:
        f.write("/* jet_tables.h -- GENERATED by jetsynth/tools/gen_tables.py (pyNA "
                "@ 7afcfd4, NASA STCA engine). DO NOT EDIT.\n"
                " * Levels: uint16 = dB re 20 uPa at r_0 = 0.3048 m, x100.\n"
                " * Layout [ts][m0][theta][band|harm]. */\n"
                "#ifndef JET_TABLES_H\n#define JET_TABLES_H\n#include <stdint.h>\n")
        f.write("#define JT_NTS %d\n#define JT_NM %d\n#define JT_NTH %d\n#define JT_NB %d\n"
                "#define JT_NH %d\n#define JT_B_FAN %d\n#define JT_Q %.1ff\n"
                % (len(TS), len(M0), len(TH), nb, NH, B, Q))
        f.write("#define JT_TS0 %.2ff\n#define JT_TSD 0.05f\n#define JT_MD 0.1f\n#define JT_THD 10.0f\n"
                "#define JT_R0 0.3048f\n" % TS[0])
        f.write("static const float JT_F[JT_NB] = {%s};\n"
                % ",".join("%.3ff" % x for x in p.noise_data.f))
        f.write("static const float JT_ABS[JT_NB] = {%s}; /* dB per metre, sea level */\n"
                % ",".join("%.6gf" % x for x in absorb))
        f.write("static const float JT_RPM[JT_NTS*JT_NM] = {%s};\n"
                % ",".join("%.2ff" % x for x in np.ravel(rpm)))
        f.write(arr("JT_JET", jet))
        f.write(arr("JT_CORE", core))
        f.write(arr("JT_FAN", fan))
        f.write(arr("JT_BUZZ", buzz))
        f.write(arr("JT_TONE", tone))
        f.write("#endif\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
