/* fx_coefs.h -- GENERATED by gen_fx_coefs.py. DO NOT EDIT.
 * Source: the sealed port (libjuno.so) natively, factory patch 0,
 * 48000 Hz, note 48 vel 100, 6000 samples rendered (reverb wipe+mute settled).
 * Every value is the port's own recalled cell, emitted as exact float bits.
 * Label: MEASURED. */
#include <stdint.h>
static inline float ebq_f(uint32_t b){float f;__builtin_memcpy(&f,&b,4);return f;}
#define EBQ_DL_B0 ebq_f(0x3e1b31ceu) /* cell 102368 = 0.15155717730522156 */
#define EBQ_DL_B1 ebq_f(0x00000000u) /* cell 102384 = 0.0 */
#define EBQ_DL_B2 ebq_f(0x00000000u) /* cell 102400 = 0.0 */
#define EBQ_DL_A1 ebq_f(0x3fb07de6u) /* cell 102416 = 1.3788421154022217 */
#define EBQ_DL_A2 ebq_f(0xbf07c840u) /* cell 102432 = -0.5303993225097656 */
#define EBQ_DL_MIXA ebq_f(0x00000000u) /* cell 102448 = 0.0 */
#define EBQ_DL_SVFG ebq_f(0x3e52bdc7u) /* cell 102464 = 0.2058020681142807 */
#define EBQ_DL_SVFR ebq_f(0x3fb50bf3u) /* cell 102480 = 1.4144271612167358 */
#define EBQ_DL_MIXB ebq_f(0x3f800000u) /* cell 102496 = 1.0 */
#define EBQ_DL_DRY ebq_f(0x3f800000u) /* cell 102512 = 1.0 */
#define EBQ_DL_WET ebq_f(0x3da0a0a1u) /* cell 102528 = 0.0784313753247261 */
#define EBQ_DL_FB ebq_f(0x3ed8d8d9u) /* cell 102560 = 0.42352941632270813 */
#define EBQ_DL_ON ebq_f(0x3f800000u) /* cell 102576 = 1.0 */
#define EBQ_DL_MUTE ebq_f(0x3f800000u) /* cell 102592 = 1.0 */
#define EBQ_DL_LPG ebq_f(0x3c2b929au) /* cell 102608 = 0.010471964254975319 */
#define EBQ_DL_K624 ebq_f(0x3f800000u) /* cell 102624 = 1.0 */
#define EBQ_DL_LFD ebq_f(0x3f800000u) /* cell 102640 = 1.0 */
#define EBQ_DL_HPG ebq_f(0x3f4ba5b0u) /* cell 102656 = 0.795496940612793 */
#define EBQ_DL_HFD ebq_f(0x3f800000u) /* cell 102672 = 1.0 */
#define EBQ_DL_K688 ebq_f(0x3f800000u) /* cell 102688 = 1.0 */
#define EBQ_DL_DCG ebq_f(0x3b6be99cu) /* cell 102704 = 0.003599739633500576 */
#define EBQ_DL_FADEK ebq_f(0x38800000u) /* cell 102720 = 6.103515625e-05 */
#define EBQ_DL_FADEUP ebq_f(0x3c000000u) /* cell 102752 = 0.0078125 */
#define EBQ_DL_FADEDN ebq_f(0xbc000000u) /* cell 102768 = -0.0078125 */
#define EBQ_DL_SLEW ebq_f(0x39aec33eu) /* cell 102784 = 0.00033333332976326346 */
#define EBQ_DL_TT ebq_f(0x3f83d200u) /* cell 102352 = 1.02984619140625 */
#define EBQ_DL_FADEG ebq_f(0x3f800000u) /* cell 84496 = 1.0 */
#define EBQ_RV_SEND ebq_f(0x3ebedc00u) /* cell 10759408 = 0.372772216796875 */
#define EBQ_RV_GATE ebq_f(0x3f800000u) /* cell 10759376 = 1.0 */
#define EBQ_RV_DRY ebq_f(0x3f800000u) /* cell 10759424 = 1.0 */
#define EBQ_RV_WET ebq_f(0x3efefeffu) /* cell 10759440 = 0.49803921580314636 */
#define EBQ_RV_AP ebq_f(0x3f000000u) /* cell 10759392 = 0.5 */
#define EBQ_RV_LFOINC ebq_f(0x37ae2650u) /* cell 10759504 = 2.0760257029905915e-05 */
#define EBQ_RV_LFODEPTH ebq_f(0x00000000u) /* cell 10759488 = 0.0 */
static const uint32_t EBQ_RV_FIN[8] = {0x3f7f8b7eu,0xbf7f8b7eu,0x3f7f16fbu,0x3d434c95u,0x3dc34c95u,0x3d434c95u,0x3fa5addfu,0xbef85dc7u}; /* cells 10759520+16k */
static const uint32_t EBQ_RV_DAMP[4][3] = {{0x3d090dbbu,0x3f194980u,0xbf4934d7u},{0x3d090dbbu,0x3f194980u,0xbf4934d7u},{0x3d090dbbu,0x3f03a1aau,0xbf3a12b2u},{0x3d090dbbu,0x3f03a1aau,0xbf3a12b2u}}; /* cells 10759648+48k */
static const int32_t EBQ_RV_TAPS[34] = {1,959,1921,3832,3834,5351,5353,6260,6262,6623,6625,7972,7974,9315,9317,10668,10670,12017,12019,16208,19064,19184,19186,23135,26563,26801,26803,30254,35012,36558,36560,40249,45007,46551}; /* WORKING taps 11022064 */
#define EBQ_RV_MUTE ebq_f(0x3f800000u) /* cell 11022032 = 1.0 (settled) */
#define EBQ_CH_DTIME ebq_f(0x3b8c0000u) /* cell 91120 = 0.0042724609375 */
#define EBQ_CH_DEPTHR ebq_f(0x3f77b282u) /* cell 91136 = 0.9675675630569458 */
#define EBQ_CH_RATE ebq_f(0x37a7c5acu) /* cell 91152 = 1.9999999494757503e-05 */
#define EBQ_CH_PHOFF ebq_f(0x3f800000u) /* cell 91168 = 1.0 */
#define EBQ_CH_DEPTH ebq_f(0x3b83126fu) /* cell 91184 = 0.004000000189989805 */
#define EBQ_CH_NOISE ebq_f(0x3ac8768bu) /* cell 91200 = 0.001529411762021482 */
#define EBQ_CH_DRY ebq_f(0x3fa66666u) /* cell 91216 = 1.2999999523162842 */
#define EBQ_CH_WET ebq_f(0x3f95c28fu) /* cell 91232 = 1.1699999570846558 */
#define EBQ_CH_SMCO ebq_f(0x387fd974u) /* cell 91248 = 6.099925667513162e-05 */
#define EBQ_CH_ONOFF ebq_f(0x3f800000u) /* cell 91264 = 1.0 */
#define EBQ_CH_MUTE ebq_f(0x3f800000u) /* cell 91280 = 1.0 */
#define EBQ_CH_B0 ebq_f(0x3da23a31u) /* cell 91296 = 0.07921255379915237 */
#define EBQ_CH_B1 ebq_f(0x3e223a31u) /* cell 91312 = 0.15842510759830475 */
#define EBQ_CH_B2 ebq_f(0x3da23a31u) /* cell 91328 = 0.07921255379915237 */
#define EBQ_CH_A1 ebq_f(0x3f9bb474u) /* cell 91344 = 1.216444492340088 */
#define EBQ_CH_A2 ebq_f(0xbf088600u) /* cell 91360 = -0.533294677734375 */
#define EBQ_CH_HB0 ebq_f(0x3f7fbfb9u) /* cell 91376 = 0.999019205570221 */
#define EBQ_CH_HB1 ebq_f(0xbf7fbfb9u) /* cell 91392 = -0.999019205570221 */
#define EBQ_CH_HA1 ebq_f(0x3f7f7f72u) /* cell 91408 = 0.9980384111404419 */
#define EBQ_CH_SVFF ebq_f(0x3e80d8ceu) /* cell 91424 = 0.25165408849716187 */
#define EBQ_CH_SVFD ebq_f(0x3fc4ec4fu) /* cell 91440 = 1.5384615659713745 */
#define EBQ_CH_EPS ebq_f(0x350637bdu) /* cell 91456 = 4.999999987376214e-07 */
#define EBQ_CH_MODSCALE ebq_f(0x40bb8000u) /* cell 91472 = 5.859375 */
#define EBQ_CH_MODOFF ebq_f(0x39000000u) /* cell 91488 = 0.0001220703125 */
#define EBQ_CH_RAMPINC ebq_f(0x38800000u) /* cell 91504 = 6.103515625e-05 */
#define EBQ_CH_RAMPMAX ebq_f(0x3d800000u) /* cell 91520 = 0.0625 */
#define EBQ_CH_SLEWUP ebq_f(0x3c000000u) /* cell 91536 = 0.0078125 */
#define EBQ_CH_SLEWDN ebq_f(0xbc000000u) /* cell 91552 = -0.0078125 */
#define EBQ_CH_NGAIN ebq_f(0x3f800000u) /* cell 91568 = 1.0 */
#define EBQ_CH_NOFF ebq_f(0x3e99999au) /* cell 91584 = 0.30000001192092896 */
static const uint32_t EBQ_CH_NF[8] = {0x3f5bb937u,0xbf5bb937u,0x3f37726fu,0x3d486075u,0x3dc86075u,0x3d486075u,0x3fb5a42du,0xbf1d6077u}; /* cells 91600+16i */
#define EBQ_CH_RINGLEN 1024 /* cell 95828 */
static const uint32_t EBQ_ENV1_RAW[15] = {0x3eb78a95u,0x3f005b8du,0x3cf87c43u,0x3d1396ffu,0xbf000000u,0xc10c0000u,0x413c0000u,0x416c0000u,0x410c0000u,0x41026666u,0x393d5383u,0x3f800000u,0x3e05f213u,0x3dea0ea1u,0x3f800000u}; /* cells +0 each of 2784,2800,2816,2832,2864,2880,2896,2912,2928,2944,2960,2848,2976,2992,3008 */
static const uint32_t EBQ_ENV2_RAW[15] = {0x40e38db9u,0x3f42739fu,0x3d1396ffu,0x3d0c549du,0xbf000000u,0xc10c0000u,0x413c0000u,0x416c0000u,0x410c0000u,0x41026666u,0x393d5383u,0x3f800000u,0x3e05f213u,0x3dea0ea1u,0x3f800000u}; /* cells +480 each of 2784,2800,2816,2832,2864,2880,2896,2912,2928,2944,2960,2848,2976,2992,3008 */
