#!/usr/bin/env python3
"""gen_fx_coefs.py — dump REAL recalled FX + envelope coefficients from the
sealed port (libjuno.so, natively) into fx_coefs.h for the QEMU instruction
harness.

WHY. tools/engineb/standalone_cost.c's invented coefficients leave the chain
SILENT (its own guard fires: the VCF CV coef set is zeroed, so cut==0 and the
ladder outputs exactly 0; the reverb was seeded mute=0, so its tank arm never
ran). A silent benchmark measures a cheaper engine than the one that ships.
This script replaces the invented FX/env values with the port's own recalled
values for one factory patch, read cell-by-cell over juno_gui_peek using the
EXACT cell lists of the null-harness shims:
  delay  : engine_b/shim/delay/master_render.c:1126-1139
  reverb : engine_b/shim/reverb/master_render.c:2135-2149 (+ working taps 11022064)
  chorus : engine_b/eb_chorus_shim.c ebsh_load_coef (91120..95828)
  env    : engine_b/shim/env/voice_render.c raw[0..14] (2784..3008 +480*ei)
Values are emitted as float BITS (hex) so the header is bit-exact.

PROVENANCE label for everything emitted: MEASURED (the port's own recalled
state, native build, 48000 Hz). The port is the sealed bit-exact engine; this
is a cost harness input, not a gate reference.
"""
import ctypes, os, struct, sys

REPO = "/home/user/jn60c99"
sys.path.insert(0, os.path.join(REPO, "tools", "verify"))
import truth

SR = 48000.0
RENDER_AFTER_NOTE = 6000     # > 256 wipe + 2500 mute ramp
NOTE, VEL = 48, 100

lib = ctypes.CDLL(os.path.join(REPO, "libjuno.so"))
lib.juno_gui_create.restype = ctypes.c_void_p
lib.juno_gui_create.argtypes = [ctypes.c_float, ctypes.c_int]
lib.juno_gui_apply_bank.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_int, ctypes.c_int]
lib.juno_gui_note_on.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_int]
lib.juno_gui_render.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_int]
lib.juno_gui_peek.restype = ctypes.c_uint
lib.juno_gui_peek.argtypes = [ctypes.c_void_p, ctypes.c_int]
lib.juno_gui_destroy.argtypes = [ctypes.c_void_p]

bank = open(truth.BANK, "rb").read()

def peekf(c, off):
    return lib.juno_gui_peek(c, off)          # raw bits

def as_f(bits):
    return struct.unpack("<f", struct.pack("<I", bits))[0]

def render(c, n):
    buf = (ctypes.c_float * (2 * n))()
    lib.juno_gui_render(c, buf, n)
    return buf

# ---- pick the patch: chorus arm live (11022052 in 2..4) AND delay on ------
best = None
for p in range(64):
    c = lib.juno_gui_create(SR, 0)
    lib.juno_gui_apply_bank(c, bank, len(bank), p)
    et  = peekf(c, 11022052)                  # EFFECT TYPE routing (int cell)
    don = as_f(peekf(c, 102576))              # delay on gate
    dwet= as_f(peekf(c, 102528))
    rsend = as_f(peekf(c, 10759408))
    lib.juno_gui_destroy(c)
    if et in (2, 3, 4) and don == 1.0 and best is None:
        best = (p, et, don, dwet, rsend)
        print("PICKED patch %d: EFFECT TYPE routing %d delay_on %g wet %g rev_send %g"
              % best)
if best is None:
    raise SystemExit("no factory patch with chorus routing + delay on")
PATCH = best[0]

c = lib.juno_gui_create(SR, 0)
lib.juno_gui_apply_bank(c, bank, len(bank), PATCH)
lib.juno_gui_note_on(c, NOTE, VEL)
render(c, RENDER_AFTER_NOTE)

out = []
out.append("/* fx_coefs.h -- GENERATED by gen_fx_coefs.py. DO NOT EDIT.")
out.append(" * Source: the sealed port (libjuno.so) natively, factory patch %d," % PATCH)
out.append(" * 48000 Hz, note %d vel %d, %d samples rendered (reverb wipe+mute settled)." % (NOTE, VEL, RENDER_AFTER_NOTE))
out.append(" * Every value is the port's own recalled cell, emitted as exact float bits.")
out.append(" * Label: MEASURED. */")
out.append("#include <stdint.h>")
out.append("static inline float ebq_f(uint32_t b){float f;__builtin_memcpy(&f,&b,4);return f;}")

def emitf(name, off):
    b = peekf(c, off)
    out.append("#define %s ebq_f(0x%08xu) /* cell %d = %r */" % (name, b, off, as_f(b)))

# ---- delay cfg (shim/delay/master_render.c:1126-1139) ----------------------
for name, off in [("EBQ_DL_B0",102368),("EBQ_DL_B1",102384),("EBQ_DL_B2",102400),
    ("EBQ_DL_A1",102416),("EBQ_DL_A2",102432),("EBQ_DL_MIXA",102448),
    ("EBQ_DL_SVFG",102464),("EBQ_DL_SVFR",102480),("EBQ_DL_MIXB",102496),
    ("EBQ_DL_DRY",102512),("EBQ_DL_WET",102528),("EBQ_DL_FB",102560),
    ("EBQ_DL_ON",102576),("EBQ_DL_MUTE",102592),("EBQ_DL_LPG",102608),
    ("EBQ_DL_K624",102624),("EBQ_DL_LFD",102640),("EBQ_DL_HPG",102656),
    ("EBQ_DL_HFD",102672),("EBQ_DL_K688",102688),("EBQ_DL_DCG",102704),
    ("EBQ_DL_FADEK",102720),("EBQ_DL_FADEUP",102752),("EBQ_DL_FADEDN",102768),
    ("EBQ_DL_SLEW",102784),("EBQ_DL_TT",102352),("EBQ_DL_FADEG",84496)]:
    emitf(name, off)

# ---- reverb cfg (shim/reverb/master_render.c:2135-2149) --------------------
for name, off in [("EBQ_RV_SEND",10759408),("EBQ_RV_GATE",10759376),
    ("EBQ_RV_DRY",10759424),("EBQ_RV_WET",10759440),("EBQ_RV_AP",10759392),
    ("EBQ_RV_LFOINC",10759504),("EBQ_RV_LFODEPTH",10759488)]:
    emitf(name, off)
fin = [peekf(c, 10759520 + 16*k) for k in range(8)]
out.append("static const uint32_t EBQ_RV_FIN[8] = {%s}; /* cells 10759520+16k */"
           % ",".join("0x%08xu" % b for b in fin))
damp = [[peekf(c, 10759648 + 48*rk + 16*j) for j in range(3)] for rk in range(4)]
out.append("static const uint32_t EBQ_RV_DAMP[4][3] = {%s}; /* cells 10759648+48k */"
           % ",".join("{%s}" % ",".join("0x%08xu" % b for b in row) for row in damp))
taps = [ctypes.c_int32(peekf(c, 11022064 + 4*t)).value for t in range(34)]
out.append("static const int32_t EBQ_RV_TAPS[34] = {%s}; /* WORKING taps 11022064 */"
           % ",".join(str(t) for t in taps))
mute = peekf(c, 11022032)
out.append("#define EBQ_RV_MUTE ebq_f(0x%08xu) /* cell 11022032 = %r (settled) */"
           % (mute, as_f(mute)))

# ---- chorus coef (eb_chorus_shim.c ebsh_load_coef) -------------------------
ch_map = [("EBQ_CH_DTIME",91120),("EBQ_CH_DEPTHR",91136),("EBQ_CH_RATE",91152),
    ("EBQ_CH_PHOFF",91168),("EBQ_CH_DEPTH",91184),("EBQ_CH_NOISE",91200),
    ("EBQ_CH_DRY",91216),("EBQ_CH_WET",91232),("EBQ_CH_SMCO",91248),
    ("EBQ_CH_ONOFF",91264),("EBQ_CH_MUTE",91280),("EBQ_CH_B0",91296),
    ("EBQ_CH_B1",91312),("EBQ_CH_B2",91328),("EBQ_CH_A1",91344),
    ("EBQ_CH_A2",91360),("EBQ_CH_HB0",91376),("EBQ_CH_HB1",91392),
    ("EBQ_CH_HA1",91408),("EBQ_CH_SVFF",91424),("EBQ_CH_SVFD",91440),
    ("EBQ_CH_EPS",91456),("EBQ_CH_MODSCALE",91472),("EBQ_CH_MODOFF",91488),
    ("EBQ_CH_RAMPINC",91504),("EBQ_CH_RAMPMAX",91520),("EBQ_CH_SLEWUP",91536),
    ("EBQ_CH_SLEWDN",91552),("EBQ_CH_NGAIN",91568),("EBQ_CH_NOFF",91584)]
for name, off in ch_map:
    emitf(name, off)
nf = [peekf(c, 91600 + 16*i) for i in range(8)]
out.append("static const uint32_t EBQ_CH_NF[8] = {%s}; /* cells 91600+16i */"
           % ",".join("0x%08xu" % b for b in nf))
rl = ctypes.c_int32(peekf(c, 95828)).value
out.append("#define EBQ_CH_RINGLEN %d /* cell 95828 */" % rl)

# ---- envelope raw cells (shim/env raw[0..14], voice 0, ENV1/ENV2) ----------
for ei in range(2):
    off = 480 * ei
    cells = [2784,2800,2816,2832,2864,2880,2896,2912,2928,2944,2960,2848,2976,2992,3008]
    raw = [peekf(c, cc + off) for cc in cells]
    out.append("static const uint32_t EBQ_ENV%d_RAW[15] = {%s}; /* cells %s */"
               % (ei+1, ",".join("0x%08xu" % b for b in raw),
                  "+%d each of " % off + ",".join(str(x) for x in cells)))

open(os.path.join(REPO, "tools", "engineb", "qemu", "fx_coefs.h"), "w").write(
    "\n".join(out) + "\n")
print("wrote tools/engineb/qemu/fx_coefs.h (%d lines)" % len(out))
lib.juno_gui_destroy(c)
