/* eb_dsp.c — GENERATED BY HAND FROM src/juno_dsp.c, VERBATIM. See eb_dsp.h.
 *
 * Each function below is the port's own, copied without change. If src/ ever
 * moves (it is frozen, so it should not), these drift silently — which is why
 * engine_b/tests/test_eb_dsp.c compares all four against the port's versions
 * rather than trusting the copy.
 */
#include "eb_dsp.h"
#include "juno_tables.h"
#include <math.h>

/* src/juno_dsp.c:77 — 0x180368DC0 */
double eb_pitch_poly(double x)
{
    double v1 = fmin(fmax(x, -20.0), 8.9);
    double v2 = v1 * v1 * v1;
    const double *v3 = juno_pitch_table[(int)(v1 + 20.0)];
    double v4 = v2 * v1 * v1;
    double v5 = v4 * v1 * v1;
    double v6 = v5 * v1 * v1;
    return v1 * v3[2]
         + v3[0]
         + v1 * v1 * v3[4]
         + v2 * v3[6]
         + v2 * v1 * v3[8]
         + v4 * v3[10]
         + v4 * v1 * v3[12]
         + v5 * v3[14]
         + v5 * v1 * v3[16]
         + v6 * v3[18]
         + v6 * v1 * v3[20]
         + v6 * v1 * v1 * v3[22]
         + v6 * v1 * v1 * v1 * v3[24];
}

/* src/juno_dsp.c:54 */
float eb_triangle_wrap(float phase)
{
    if (phase <= 1.0f) {
        if (phase < -1.0f)
            phase = fmodf(phase - 1.0f, 2.0f) + 1.0f;
    } else {
        phase = fmodf(phase + 1.0f, 2.0f) - 1.0f;
    }
    float v2 = phase + phase;       /* 2*p */
    if (phase >= -0.5f) {
        if (phase <= 0.5f)
            return v2;              /* 2*p */
        else
            return 2.0f - v2;       /* 2 - 2*p */
    } else {
        return -2.0f - v2;          /* -2 - 2*p */
    }
}

/* src/juno_dsp.c:101 — 0x180368F30 */
float eb_wrap_unit(float x)
{
    if (x > 1.0f)  return fmodf(x + 1.0f, 2.0f) - 1.0f;
    if (x < -1.0f) return fmodf(x - 1.0f, 2.0f) + 1.0f;
    return x;
}

/* src/juno_dsp.c:109 — 0x180368F90 */
float eb_wrap_hi(float x)
{
    if (x > 1.0f) return fmodf(x + 1.0f, 2.0f) - 1.0f;
    return x;
}
