/* eb_delay_t5.h -- GENERATED by tools/engineb/arm_xform.py; see the .c */
#ifndef ENGINEB_EB_DELAY_T5_H
#define ENGINEB_EB_DELAY_T5_H
#include <stdint.h>

typedef struct {
    float   k101744;
    float   k6497168;
    float   k6497184;
    float   k6497200;
    float   k6497216;
    float   k6497232;
    float   k6497248;
    float   k6497264;
    float   k6497280;
    float   k6497296;
    float   k6497312;
    float   k6497328;
    float   k6497344;
    float   k6497376;
    float   k6497392;
    float   k6497408;
    float   k6497424;
    float   k6497440;
    float   k6497456;
    float   k6497472;
    float   k6497488;
    float   k6497504;
    float   k6497520;
    float   k6497536;
    float   k6497568;
    float   k6497584;
    float   k6497600;
    int32_t k8594772;   /* ring length, a power of two */
    int32_t k10691940;   /* ring length, a power of two */
    float   k10692016;
    float   k10692032;
    float   k10692112;
    /* ⚑ THE PER-SAMPLE DOUBLE-PRECISION PITCH CALL, HOISTED. EXACTLY 0.
     *
     * MEASURED on the user's board 2026-08-12: patches with DELAY TYPE 2, 3 or
     * 5 cost about DOUBLE -- ~10,000 cycles against ~5,200 -- and 18 of the 64
     * factory patches use them. The cause is this expression, which ran ONCE
     * PER SAMPLE:
     *
     *     v = eb_pitch_poly((double)(float)(k_a + k_b));
     *     v = clamp(v, -512, 512);
     *
     * eb_pitch_poly is a THIRTEEN-TERM DOUBLE-PRECISION polynomial and the
     * ESP32-S3 HAS NO DOUBLE FPU, so every term is a libgcc soft-double call.
     * CLAUDE.md already prices that shape at 18,200-22,300 instructions a
     * sample where it appears in the DCO.
     *
     * BOTH INPUTS ARE COEFFICIENTS. k_a and k_b are set once by
     * eb_master_coefs_build from CF(base, ...) and never change between
     * recalls, so the whole expression is LOOP-INVARIANT and was being
     * recomputed 44,100 times a second for a value that cannot move.
     *
     * This is not an approximation and needs no sonic gate: the same
     * expression, same types, same order, evaluated once at build time. The
     * null must stay EXACTLY 0 and that is the whole proof. */
    float   pitchmod_pre;
    float   k10692352;
    float   k10692368;
    float   k10692400;
    float   k10692416;
    float   k10693008;
    float   k10693024;
    float   k10693040;
    float   k10693056;
    float   k10693072;
    float   k10693088;
    float   k10693104;
    float   k10693120;
    float   k10693136;
    float   k10693152;
    float   k10693168;
    float   k10693184;
    float   k10693200;
    float   k10693216;
    float   k10693232;
    float   k10693248;
    float   k10693264;
    float   k10693280;
    float   k10693296;
    float   k10693312;
    float   k10693328;
    float   k10693344;
    float   k10693360;
    float   k10693376;
    float   k10693392;
    float   k10693408;
    float   k10693424;
    float   k10693440;
    float   k10693456;
    float   k10693472;
    int32_t k10726260;   /* ring length, a power of two */
    int32_t k10759044;   /* ring length, a power of two */
} eb_dly5_coef;

typedef struct {
    float   s6496576;
    float   s6496592;
    float   s6496608;
    float   s6496624;
    float   s6496640;
    float   s6496656;
    float   s6496672;
    float   s6496688;
    float   s6496704;
    float   s6496720;
    float   s6496736;
    float   s6496752;
    float   s6496768;
    float   s6496784;
    float   s6496800;
    float   s6496816;
    float   s6496832;
    float   s6496848;
    float   s6496864;
    float   s6496880;
    float   s6496896;
    float   s6496912;
    float   s6496928;
    float   s6496944;
    float   s6496960;
    float   s6496976;
    float   s6496992;
    float   s6497008;
    float   s6497024;
    float   s6497040;
    float   s6497056;
    float   s6497072;
    float   s6497088;
    float   s6497104;
    float   s6497120;
    float   s6497136;
    float   s6497152;
    float   s10691952;
    float   s10691968;
    float   s10691972;
    float   s10691976;
    float   s10691984;
    float   s10692000;
    float   s10692004;
    float   s10692008;
    float   s10692048;
    float   s10692064;
    float   s10692080;
    float   s10692304;
    float   s10692320;
    float   s10692336;
    float   s10692384;
    float   s10692432;
    float   s10692448;
    float   s10692464;
    float   s10692480;
    float   s10692496;
    float   s10692512;
    float   s10692528;
    float   s10692544;
    float   s10692560;
    float   s10692576;
    float   s10692592;
    float   s10692608;
    float   s10692624;
    float   s10692640;
    float   s10692656;
    float   s10692672;
    float   s10692688;
    float   s10692704;
    float   s10692720;
    float   s10692736;
    float   s10692752;
    float   s10692768;
    float   s10692784;
    float   s10692800;
    float   s10692816;
    float   s10692832;
    float   s10692848;
    float   s10692864;
    float   s10692880;
    float   s10692896;
    float   s10692912;
    float   s10692928;
    float   s10692944;
    float   s10692960;
    float   s10692976;
    float   s10692992;
    float   s10759056;
    float   s10759072;
    float   s10759076;
    float   s10759080;
    float   s10759088;
    float   s10759104;
    float   s10759108;
    float   s10759112;
    int32_t s8594768;
    int32_t s10691936;
    int32_t s10726256;
    int32_t s10759040;
    int32_t s11022348;
    float  *ring0;   /* port 6497616  */
    float  *ring1;   /* port 8594784  */
    float  *ring2;   /* port 10693488 */
    float  *ring3;   /* port 10726272 */
} eb_dly5_state;

void eb_dly5_tick(eb_dly5_state *s, const eb_dly5_coef *c,
                  float in36, float in38, float k5,
                  float *o176, float *o177, float *o56, float *o58);

#endif
