/* eb_delay_t5.c -- GENERATED by tools/engineb/arm_xform.py from
 * src/master_render.c:1459-1866, the DELAY TYPE 5 algorithm.
 *
 * FOUR ring buffers, and each ring's control pair sits immediately AFTER
 * the PREVIOUS ring's data -- so a ring's index cell is nowhere near its
 * own base and the pairing must be read off the write expression, never
 * guessed from the addresses. One read spells its subtrahend inline as
 * `(int)(float)(v55 * -16384.0)` rather than as a local, which a
 * plain-local capture would have skipped silently.
 */
#include "eb_delay_t5.h"
#include "eb_minmax.h"

/* EB_ZEROCOEF_T5 (2026-08-30) -- delete the six t5 coefficient slots proven
 * structurally zero at 44.1 kHz by tools/engineb/mc_zero_proof.c (64 patches
 * + 31,744 single-parameter sweeps + 4,000 random presets, moved-witness
 * alive each stage) and by the port's own writers: k6497200/k6497216 are
 * DLY_HC table columns 1-2 (zero for every legal byte, finefx_recall.c);
 * k6497264/k10693152 are the ARM_HCSW rate switches' 44.1k arm;
 * k10693024/k10693296 sweep zero over the whole preset space. With
 * k10693152 == 0 the two 5-tap chorus FIRs (v116/v127) feed NOTHING and are
 * deleted whole. 44.1 kHz ONLY -- the other rate arms are nonzero, so this
 * flag must never reach a build with a different rate. Default 0 = trunk
 * verbatim; judged by the foundation gate at EXACTLY 0. */
#ifndef EB_ZEROCOEF_T5
#define EB_ZEROCOEF_T5 0
#endif
#include "eb_ring_probe.h"
#include "eb_dsp.h"
#include "juno_tables.h"
#include <math.h>
#include <string.h>

#define LODWORD(x)  (*(uint32_t *)&(x))
#define RINGR0(i)   (s->ring0[EB_RP_R(EB_RP_T5_0, c->k8594772,  (i), s->s8594768)])
#define RINGR1(i)   (s->ring1[EB_RP_R(EB_RP_T5_1, c->k10691940, (i), s->s10691936)])
#define RINGR2(i)   (s->ring2[EB_RP_R(EB_RP_T5_2, c->k10726260, (i), s->s10726256)])
#define RINGR3(i)   (s->ring3[EB_RP_R(EB_RP_T5_3, c->k10759044, (i), s->s10759040)])
#define RINGI0(i)   (s->ring0[(i)])
#define RINGI1(i)   (s->ring1[(i)])
#define RINGI2(i)   (s->ring2[(i)])
#define RINGI3(i)   (s->ring3[(i)])

void eb_dly5_tick(eb_dly5_state *s, const eb_dly5_coef *c,
                  float in36, float in38, float k5,
                  float *o176, float *o177, float *o56, float *o58)
{
    float v5;
    float v36;
    float v38;
    float v40;
    float v41;
    float v42;
    float v43;
    float v44;
    float v45;
    float v46;
    float v47;
    float v48;
    float v49;
    float v50;
    float v51;
    float v52;
    float v53;
    float v54;
    float v55;
    double v56;
    double v57;
    float v58;
    float v59;
    float v60;
    float v61;
    float v62;
    float v63;
    float v64;
    float v65;
    float v66;
    float v67;
    float v68;
    float v69;
    float v70;
    float v71;
    float v72;
    float v73;
    float v74;
    float v75;
    float v76;
    float v77;
    float v78;
    float v79;
    float v80;
    float v81;
    float v82;
    float v83;
    float v84;
    float v85;
    float v86;
    float v87;
    float v88;
    float v89;
    float v90;
    float v91;
    float v92;
    float v93;
    float v94;
    float v95;
    float v96;
    int v97;
    int v98;
    float v99;
    float v100;
    float v101;
    float v102;
    float v103;
    float v104;
    float v105;
    float v106;
    float v107;
    float v108;
    float v109;
    float v110;
    float v111;
    float v112;
    float v113;
    float v114;
    float v115;
    float v116;
    float v117;
    float v118;
    float v119;
    float v120;
    float v121;
    float v122;
    float v123;
    float v124;
    float v125;
    float v126;
    float v127;
    float v128;
    float v129;
    float v130;
    float v131;
    float v132;
    float v133;
    float v134;
    float v135;
    float v136;
    float v137;
    float v138;
    float v139;
    float v140;
    float v141;
    float v142;
    float v143;
    float v144;
    float v145;
    float v146;
    double v147;
    float v148;
    float v149;
    float v150;
    float v151;
    float v152;
    int v153;
    float v154;
    float v155;
    float v156;
    float v157;
    int v158;
    float v159;
    float v160;
    float v161;
    float v162;
    float v163;
    float v164;
    float v165;
    float v166;
    float v167;
    float v168;
    float v169;
    float v170;
    float v171;
    float v172;
    int v173;
    int v174;
    float v175;
    float v176;
    float v177;
    (void)k5;
          if ( s->s11022348 != 5 )
          {
            s->s6497088 = 0;
            s->s6497104 = 0;
            s->s6497120 = 0;
            s->s10692864 = 0;
            s->s10692880 = 0;
            s->s10692896 = 0;
          }
          s->s11022348 = 5;
          s->s6496720 = s->s6496704;
          s->s6496704 = s->s6496688;
          s->s6496688 = s->s6496672;
          s->s6496672 = s->s6496656;
          s->s6496656 = s->s6496640;
          s->s6496640 = s->s6496624;
          s->s6496624 = s->s6496608;
          s->s6496848 = s->s6496832;
          s->s6496832 = s->s6496816;
          s->s6496816 = s->s6496800;
          s->s6496800 = s->s6496784;
          s->s6496784 = s->s6496768;
          s->s6496768 = s->s6496752;
          s->s6496752 = s->s6496736;
          s->s6496928 = s->s6496912;
          s->s6496912 = s->s6496896;
          s->s6496896 = s->s6496880;
          s->s6496880 = s->s6496864;
          s->s6497008 = s->s6496992;
          s->s6496992 = s->s6496976;
          s->s6496976 = s->s6496960;
          s->s6496960 = s->s6496944;
          s->s6497120 = s->s6497104;
          s->s6497104 = s->s6497088;
          s->s6497072 = s->s6497056;
          s->s6497056 = s->s6497040;
          s->s6497040 = s->s6497024;
          s->s6496576 = in36;
          s->s6496592 = in38;
          s->s6496864 = in36;
#if EB_ZEROCOEF_T5
/* EB_ZC_T5_TOOTH: zc_t5_gate.py's non-vacuity probe. Deleting k6497232 -- a
 * LIVE coefficient -- MUST change the battery's audio, or the gate is blind. */
#if defined(EB_ZC_T5_TOOTH) && EB_ZC_T5_TOOTH
          v40 = (float)(in36 * c->k6497184)
              + (float)(c->k6497248 * s->s6496928);
#else
          v40 = (float)((float)(in36 * c->k6497184)
                      + (float)(c->k6497232 * s->s6496912))
              + (float)(c->k6497248 * s->s6496928);
#endif
#else
          v40 = (float)((float)((float)((float)(in36 * c->k6497184)
                                      + (float)(c->k6497200 * s->s6496880))
                              + (float)(s->s6496896 * c->k6497216))
                      + (float)(c->k6497232 * s->s6496912))
              + (float)(c->k6497248 * s->s6496928);
#endif
          s->s6496896 = v40;
          s->s6496608 = (float)((float)((float)(in36
                                                           - (float)(s->s6496624 * c->k6497296))
                                                   - s->s6496640)
                                           * c->k6497280)
                                   + s->s6496624;
          v41 = (float)(c->k6497280 * s->s6496624) + s->s6496640;
          s->s6496624 = v41;
#if EB_ZEROCOEF_T5
          s->s10691952 = (float)((float)((float)((float)(v41 * c->k6497312)
                                                            + (float)((float)(1.0 - c->k6497312) * in36))
                                                    * c->k6497392)
                                            + (float)(c->k6497376 * s->s6496704))
                                    * c->k6497408;

#else
          s->s10691952 = (float)((float)((float)((float)((float)((float)((float)(1.0
                                                                                            - c->k6497264)
                                                                                    * v41)
                                                                            + (float)(c->k6497264 * v40))
                                                                    * c->k6497312)
                                                            + (float)((float)(1.0 - c->k6497312) * in36))
                                                    * c->k6497392)
                                            + (float)(c->k6497376 * s->s6496704))
                                    * c->k6497408;
#endif
          v42 = s->s6496592;
          s->s6496944 = v42;
#if EB_ZEROCOEF_T5
          v43 = (float)((float)(v42 * c->k6497184)
                      + (float)(s->s6496992 * c->k6497232))
              + (float)(c->k6497248 * s->s6497008);
#else
          v43 = (float)((float)((float)((float)(v42 * c->k6497184)
                                      + (float)(c->k6497200 * s->s6496960))
                              + (float)(c->k6497216 * s->s6496976))
                      + (float)(s->s6496992 * c->k6497232))
              + (float)(c->k6497248 * s->s6497008);
#endif
          s->s6496976 = v43;
          s->s6496736 = (float)((float)((float)(v42
                                                           - (float)(s->s6496752 * c->k6497296))
                                                   - s->s6496768)
                                           * c->k6497280)
                                   + s->s6496752;
          v44 = (float)(s->s6496752 * c->k6497280) + s->s6496768;
          s->s6496752 = v44;
#if EB_ZEROCOEF_T5
          s->s10691984 = (float)((float)((float)((float)(v44 * c->k6497312)
                                                            + (float)((float)(1.0 - c->k6497312) * v42))
                                                    * c->k6497392)
                                            + (float)(c->k6497376 * s->s6496832))
                                    * c->k6497408;

#else
          s->s10691984 = (float)((float)((float)((float)((float)((float)((float)(1.0
                                                                                            - c->k6497264)
                                                                                    * v44)
                                                                            + (float)(c->k6497264 * v43))
                                                                    * c->k6497312)
                                                            + (float)((float)(1.0 - c->k6497312) * v42))
                                                    * c->k6497392)
                                            + (float)(c->k6497376 * s->s6496832))
                                    * c->k6497408;
#endif
          v45 = (float)(c->k6497536 + s->s6497104) * k5;
          s->s6497088 = v45;
          if ( (float)(v45 - s->s6497072) >= 0.0 )
            v46 = c->k6497568;
          else
            v46 = c->k6497584;
          v47 = c->k6497168;
          v48 = s->s6497120 + v46;
          s->s6497024 = v47;
          v49 = s->s6497072;
          v50 = s->s6497056;
          v51 = v47 - v49;
          v52 = c->k6497600;
          if ( (float)(v47 - s->s6497040) != 0.0 )
            v50 = v47 - v49;
          s->s6497040 = v50;
          v53 = fabs(v50) * v52;
          v54 = v49 + v53;
          v55 = eb_fmaxf(v49 - v53, v47);
          if ( v51 > 0.0 )
            v55 = eb_fminf(v54, v47);
          s->s6497056 = v55;
          v56 = 0.0;
          if ( v48 <= 0.0 )
            v57 = 0.0;
          else
            v57 = v48;
          v58 = -1.0;
          v59 = v57;
          if ( v59 >= -1.0 )
            v60 = eb_fminf_c(v59, 1.0);
          else
            v60 = -1.0;
          s->s6497104 = v60 * c->k6497408;
          s->s10691968 = RINGR0(s->s8594768 - ((int)(float)(v55 * -16384.0)) + 1);
          s->s10691972 = RINGR0(s->s8594768 - ((int)(float)(v55 * -16384.0)) + 2);
          v61 = (float)(v55 * 16384.0) - (double)(int)(float)(v55 * 16384.0);
          s->s10691976 = v61;
          v62 = s->s10691968;
          s->s10692000 = RINGR1(s->s10691936 - ((int)(float)(v55 * -16384.0)) + 1);
          s->s10692004 = RINGR1(s->s10691936 - ((int)(float)(v55 * -16384.0)) + 2);
          s->s10692008 = v61;
          v63 = s->s6496672;
          v64 = (float)((float)((float)(v61 * s->s10691972) - (float)(v61 * v62)) + v62)
              * s->s6497120;
          s->s6496640 = v64;
          v65 = v64 - v63;
          v66 = s->s6496688;
          v67 = s->s10692000;
          v68 = c->k6497440 * v65;
          v69 = (float)(v65 * c->k6497424) + v63;
          v70 = c->k6497456;
          s->s6496656 = v69;
          v71 = s->s6496720;
          v72 = v68 - (float)(v70 * v69);
          v73 = c->k6497488;
          v74 = v72 - v66;
          v75 = (float)(v74 * c->k6497472) + v66;
          v76 = c->k6497504;
          s->s6496672 = v75;
          v77 = (float)((float)(v76 * v75) - (float)(v73 * v74)) - v71;
          s->s6496688 = v77;
          s->s6496704 = (float)(v77 * c->k6497520) + v71;
          v78 = s->s6496800;
          v79 = (float)((float)((float)(v61 * s->s10692004) - (float)(v61 * v67)) + v67)
              * s->s6497120;
          s->s6496768 = v79;
          v80 = v79 - v78;
          v81 = s->s6496816;
          v82 = c->k6497440 * v80;
          v83 = (float)(v80 * c->k6497424) + v78;
          v84 = c->k6497456;
          s->s6496784 = v83;
          v85 = s->s6496848;
          v86 = (float)(v82 - (float)(v84 * v83)) - v81;
          v87 = c->k6497488 * v86;
          v88 = (float)(v86 * c->k6497472) + v81;
          v89 = c->k6497504;
          s->s6496800 = v88;
          v90 = (float)((float)(v89 * v88) - v87) - v85;
          s->s6496816 = v90;
          v91 = c->k6497344;
          v92 = s->s6496640 * v91;
          v93 = s->s6496768 * v91;
          s->s6496832 = v85 + (float)(v90 * c->k6497520);
          v94 = c->k6497392;
          v95 = 1.0 - v94;
          v96 = (float)((float)(v94 * (float)(c->k6497328 * s->s6496592))
                      + (float)((float)(1.0 - v94) * s->s6496592))
              + v93;
          s->s6497136 = (float)((float)(c->k6497392
                                                   * (float)(c->k6497328 * s->s6496576))
                                           + (float)(v95 * s->s6496576))
                                   + v92;
          s->s6497152 = v96;
          v97 = (s->s8594768 - 1) & (c->k8594772 - 1);
          s->s8594768 = v97;
          RINGI0(v97) = s->s10691952;
          v98 = (s->s10691936 - 1) & (c->k10691940 - 1);
          s->s10691936 = v98;
          RINGI1(v98) = s->s10691984;
          v99 = c->k10692032;
          s->s10692048 = c->k10692016;
          s->s10692064 = v99;
          /* HOISTED -- see eb_delay_t5.h. */
          s->s10692080 = c->pitchmod_pre;
          (void)v100;
          v101 = s->s10692064;
          s->s10692320 = s->s10692304;
          { float _inc2 = (float)(s->s10692080 * c->k10692352);
    if ( _inc2 < 4.0 ) { if ( _inc2 >= 2.0 ) _inc2 = _inc2 + -2.0; } else _inc2 = _inc2 + -4.0;
    if ( _inc2 == 0.0 ) _inc2 = c->k10692368;
    v102 = eb_wrap_hi((float)(s->s10692304 + _inc2)); }
          v103 = *(float *)&v102;
          v104 = eb_triangle_wrap(v102);
          s->s10692336 = v104;
          s->s10692304 = (float)(v103 * v101) + (float)(v101 - 1.0);
          v105 = (float)(v104 * c->k10692400) + c->k10692416;
          s->s10692384 = v105;
          v106 = s->s6497152;
          v107 = s->s6497136;
          s->s10692560 = s->s10692544;
          s->s10692544 = s->s10692528;
          s->s10692528 = s->s10692512;
          s->s10692512 = s->s10692496;
          s->s10692496 = s->s10692480;
          s->s10692656 = s->s10692640;
          s->s10692640 = s->s10692624;
          s->s10692624 = s->s10692608;
          s->s10692608 = s->s10692592;
          s->s10692592 = s->s10692576;
          s->s10692736 = s->s10692720;
          s->s10692720 = s->s10692704;
          s->s10692704 = s->s10692688;
          s->s10692688 = s->s10692672;
          s->s10692816 = s->s10692800;
          s->s10692800 = s->s10692784;
          s->s10692784 = s->s10692768;
          s->s10692768 = s->s10692752;
          s->s10692848 = s->s10692832;
          s->s10692896 = s->s10692880;
          s->s10692880 = s->s10692864;
          s->s10692464 = v105;
          v108 = c->k10693040;
          v109 = (float)(v105 * c->k10693344) + c->k10693360;
          s->s10692432 = v107;
          s->s10692448 = v106;
#if EB_ZEROCOEF_T5
          v110 = 0.0f;
          v111 = v105;
          v112 = 0.0f;
          v113 = c->k10693376;
          v114 = c->k10693392;
          v115 = c->k10693056 * v109;
          (void)v110; (void)v112;
#else
          v110 = c->k10693024;
          v111 = v105
               + (float)((float)((float)((float)((float)(v105 * 0.5) + v108) * (float)((float)(v105 * 0.5) + v108))
                               * v110)
                       - (float)(v110 * v105));
          v112 = (float)((float)((float)((float)(v109 * 0.5) + v108) * (float)((float)(v109 * 0.5) + v108)) * v110)
               - (float)(v110 * v109);
          v113 = c->k10693376;
          v114 = c->k10693392;
          v115 = c->k10693056 * (float)(v109 + v112);
#endif
          s->s10692912 = (float)((float)(c->k10693056 * v111) * v113) + v114;
          s->s10692928 = (float)(v115 * v113) + v114;
          s->s10692672 = v107;
#if EB_ZEROCOEF_T5
          /* v116's FIR is DEAD: its only consumer is k10693152 * v116 == 0.
           * The shift chain above still runs (cheap moves, state preserved). */
          v116 = 0.0f;
          (void)v116;
#else
          v116 = (float)((float)((float)((float)(v107 * c->k10693072)
                                       + (float)(c->k10693088 * s->s10692688))
                               + (float)(c->k10693104 * s->s10692704))
                       + (float)(c->k10693120 * s->s10692720))
               + (float)(s->s10692736 * c->k10693136);
          s->s10692704 = v116;
#endif
          s->s10692480 = (float)((float)((float)(v107
                                                            - (float)(s->s10692496
                                                                    * c->k10693184))
                                                    - s->s10692512)
                                            * c->k10693168)
                                    + s->s10692496;
          v117 = (float)(s->s10692496 * c->k10693168) + s->s10692512;
          s->s10692496 = v117;
#if EB_ZEROCOEF_T5
          v118 = 0.0f; (void)v118;
          v119 = v117;
          v120 = s->s10692528;
          v121 = (float)(v119 * c->k10693200)
               + (float)((float)(1.0 - c->k10693200) * v107);
#else
          v118 = c->k10693152;
          v119 = (float)(1.0 - v118) * v117;
          v120 = s->s10692528;
          v121 = (float)((float)(v119 + (float)(v118 * v116)) * c->k10693200)
               + (float)((float)(1.0 - c->k10693200) * v107);
#endif
          v122 = c->k10693312;
          v123 = (float)((float)(v121 - v120) * c->k10693216) + v120;
          v124 = v121
               + (float)((float)(c->k10693232 * (float)(v121 - v120))
                       - (float)(c->k10693232 * v121));
#if EB_ZEROCOEF_T5
          v125 = 0.0f; (void)v125;
          s->s10692512 = v123;
          s->s10759056 = (float)(v122 * v124) * c->k10693328;
#else
          v125 = c->k10693296;
          s->s10692512 = v123;
          s->s10759056 = (float)((float)(v125 * s->s10692544) + (float)(v122 * v124))
                                    * c->k10693328;
#endif
          v126 = s->s10692448;
          s->s10692752 = v126;
#if EB_ZEROCOEF_T5
          /* v127's FIR is DEAD for the same reason as v116's. */
          v127 = 0.0f;
          (void)v127;
#else
          v127 = (float)((float)((float)((float)(v126 * c->k10693072)
                                       + (float)(s->s10692768 * c->k10693088))
                               + (float)(s->s10692784 * c->k10693104))
                       + (float)(c->k10693120 * s->s10692800))
               + (float)(s->s10692816 * c->k10693136);
          s->s10692784 = v127;
#endif
          s->s10692576 = (float)((float)((float)(v126
                                                            - (float)(s->s10692592
                                                                    * c->k10693184))
                                                    - s->s10692608)
                                            * c->k10693168)
                                    + s->s10692592;
          v128 = (float)(s->s10692592 * c->k10693168) + s->s10692608;
          s->s10692592 = v128;
#if EB_ZEROCOEF_T5
          v129 = 0.0f; (void)v129;
          v130 = c->k10693200;
          v131 = v128;
          v132 = s->s10692624;
          v133 = v131;
          v134 = (float)(1.0 - v130) * v126;
          v135 = 0.0f; (void)v135;
          v136 = (float)(v133 * v130) + v134;
#else
          v129 = c->k10693152;
          v130 = c->k10693200;
          v131 = (float)(1.0 - v129) * v128;
          v132 = s->s10692624;
          v133 = v131 + (float)(v129 * v127);
          v134 = (float)(1.0 - v130) * v126;
          v135 = c->k10693296;
          v136 = (float)(v133 * v130) + v134;
#endif
          v137 = c->k10693312;
          v138 = (float)((float)(v136 - v132) * c->k10693216) + v132;
          v139 = v136
               + (float)((float)(c->k10693232 * (float)(v136 - v132))
                       - (float)(c->k10693232 * v136));
          s->s10692608 = v138;
          v140 = c->k10693328;
          v141 = c->k10693424 + s->s10692880;
#if EB_ZEROCOEF_T5
          s->s10759088 = v140 * (float)(v137 * v139);
#else
          s->s10759088 = v140 * (float)((float)(v135 * s->s10692640) + (float)(v137 * v139));
#endif
          v142 = eb_fminf(c->k10693440, v141) * v140;
          s->s10692864 = v142;
          v143 = s->s10692896;
          if ( (float)(v142 - s->s10692848) >= 0.0 )
            v144 = v143 + c->k10693456;
          else
            v144 = v143 + c->k10693472;
          v145 = c->k10693008;
          v146 = s->s10692848;
          if ( v144 <= 0.0 )
            v147 = 0.0;
          else
            v147 = v144;
          v148 = v147;
          v149 = (float)((float)(c->k10693008 - v146) * c->k10693280) + v146;
          if ( v148 >= -1.0 )
            v150 = eb_fminf_c(v148, 1.0);
          else
            v150 = -1.0;
          s->s10692880 = v150 * c->k10693328;
          if ( (float)(v149 - v146) != 0.0 )
            v145 = v149;
          s->s10692832 = v145;
          v151 = v145;
          v152 = v145 + s->s10692912;
          v153 = (int)(float)(v152 * -16384.0);
          s->s10759072 = RINGR2(s->s10726256 - (v153) + 1);
          s->s10759076 = RINGR2(s->s10726256 - (v153) + 2);
          v154 = (float)(v152 * 16384.0) - (double)(int)(float)(v152 * 16384.0);
          s->s10759080 = v154;
          v155 = s->s10759072;
          v156 = s->s10692896;
          v157 = v151 + s->s10692928;
          v158 = (int)(float)(v157 * -16384.0);
          s->s10759104 = RINGR3(s->s10759040 - (v158) + 1);
          s->s10759108 = RINGR3(s->s10759040 - (v158) + 2);
          v159 = (float)(v157 * 16384.0) - (double)(int)(float)(v157 * 16384.0);
          s->s10759112 = v159;
          v160 = s->s10692560;
          v161 = (float)((float)(v154 * s->s10759076) - (float)(v154 * v155)) + v155;
          v162 = s->s10759104;
          v163 = v161 * v156;
          s->s10692528 = v163 - v160;
          s->s10692544 = (float)((float)(v163 - v160) * c->k10693408) + v160;
          v164 = s->s10692656;
          v165 = (float)((float)((float)(v159 * s->s10759108) - (float)(v159 * v162)) + v162) * v156;
          v166 = v165 - v164;
          s->s10692624 = v165 - v164;
          v167 = c->k10693264;
          v168 = v165 * v167;
          s->s10692640 = (float)(v166 * c->k10693408) + v164;
          v169 = s->s10692448;
          v170 = s->s10692432;
          v171 = c->k10693248;
          s->s10692944 = v163 * v167;
          s->s10692960 = v168;
          v172 = c->k10693312;
          s->s10692976 = (float)((float)(v172 * (float)(v171 * v170)) + (float)((float)(1.0 - v172) * v170))
                                    + s->s10692944;
          s->s10692992 = (float)((float)(v172 * (float)(v171 * v169)) + (float)((float)(1.0 - v172) * v169))
                                    + v168;
          v173 = (s->s10726256 - 1) & (c->k10726260 - 1);
          s->s10726256 = v173;
          RINGI2(v173) = s->s10759056;
          v174 = (c->k10759044 - 1) & (s->s10759040 - 1);
          s->s10759040 = v174;
          RINGI3(v174) = s->s10759088;
          v175 = c->k101744;
          v176 = v175 * s->s10692992;
          v177 = v175 * s->s10692976;
    *o176 = v176; *o177 = v177; *o56 = v56; *o58 = v58;
}
