/* eb_dly_t4.h -- GENERATED by tools/engineb/arm_xform.py */
#ifndef ENGINEB_EB_DLY_T4_H
#define ENGINEB_EB_DLY_T4_H
#include <stdint.h>

/* DELAY TYPE 4. No factory patch selects it; reached only by the
 * DOCTORED-bank scenario in null_b.py (task 1b-3). */

typedef struct {
    float   k101744;
    float   k6429472;
    float   k6429488;
    float   k6429568;
    float   k6429808;
    float   k6429824;
    float   k6429856;
    float   k6429872;
    float   k6430464;
    float   k6430480;
    float   k6430496;
    float   k6430512;
    float   k6430528;
    float   k6430544;
    float   k6430560;
    float   k6430576;
    float   k6430592;
    float   k6430608;
    float   k6430624;
    float   k6430640;
    float   k6430656;
    float   k6430672;
    float   k6430688;
    float   k6430704;
    float   k6430720;
    float   k6430736;
    float   k6430752;
    float   k6430768;
    float   k6430784;
    float   k6430800;
    float   k6430816;
    float   k6430832;
    float   k6430848;
    float   k6430864;
    float   k6430880;
    float   k6430896;
    float   k6430912;
    float   k6430928;
    int32_t k6463716;
    int32_t k6496500;
} eb_dly_t4_coef;

typedef struct {
    float   s6429504;
    float   s6429520;
    float   s6429536;
    float   s6429760;
    float   s6429776;
    float   s6429792;
    float   s6429840;
    float   s6429888;
    float   s6429904;
    float   s6429920;
    float   s6429936;
    float   s6429952;
    float   s6429968;
    float   s6429984;
    float   s6430000;
    float   s6430016;
    float   s6430032;
    float   s6430048;
    float   s6430064;
    float   s6430080;
    float   s6430096;
    float   s6430112;
    float   s6430128;
    float   s6430144;
    float   s6430160;
    float   s6430176;
    float   s6430192;
    float   s6430208;
    float   s6430224;
    float   s6430240;
    float   s6430256;
    float   s6430272;
    float   s6430288;
    float   s6430304;
    float   s6430320;
    float   s6430336;
    float   s6430352;
    float   s6430368;
    float   s6430384;
    float   s6430400;
    float   s6430416;
    float   s6430432;
    float   s6430448;
    float   s6496512;
    float   s6496528;
    float   s6496532;
    float   s6496536;
    float   s6496544;
    float   s6496560;
    float   s6496564;
    float   s6496568;
    int32_t s6463712;
    int32_t s6496496;
    int32_t s11022348;
    float  *ring0;
    float  *ring1;
} eb_dly_t4_state;

void eb_dly_t4_tick(eb_dly_t4_state *s, const eb_dly_t4_coef *c,
                 float in36, float in38, float k5, float *o176, float *o177, float *o56, float *o58);

#endif
