/* eb_delay_t1.h -- GENERATED by tools/engineb/arm_xform.py */
#ifndef ENGINEB_EB_DELAY_T1_H
#define ENGINEB_EB_DELAY_T1_H
#include <stdint.h>

typedef struct {
    float   k101744;
    float   k4297584;
    float   k4297600;
    float   k4297616;
    float   k4297632;
    float   k4297648;
    float   k4297664;
    float   k4297680;
    float   k4297696;
    float   k4297712;
    float   k4297728;
    float   k4297744;
    float   k4297760;
    float   k4297792;
    float   k4297808;
    float   k4297824;
    float   k4297840;
    float   k4297856;
    float   k4297872;
    float   k4297888;
    float   k4297904;
    float   k4297920;
    float   k4297936;
    float   k4297952;
    float   k4297968;
    float   k4297984;
    float   k4298000;
    float   k4298016;
    float   k4298032;
    float   k4298048;
    float   k4298064;
    float   k4298080;
    int32_t k6395252;
} eb_dly1_coef;

typedef struct {
    float   s4297200;
    float   s4297216;
    float   s4297232;
    float   s4297248;
    float   s4297264;
    float   s4297280;
    float   s4297296;
    float   s4297312;
    float   s4297328;
    float   s4297344;
    float   s4297360;
    float   s4297376;
    float   s4297392;
    float   s4297408;
    float   s4297424;
    float   s4297440;
    float   s4297456;
    float   s4297472;
    float   s4297488;
    float   s4297504;
    float   s4297520;
    float   s4297536;
    float   s4297552;
    float   s4297568;
    float   s6395264;
    float   s6395280;
    float   s6395284;
    float   s6395288;
    float   s6395296;
    float   s6395300;
    float   s6395304;
    int32_t s6395248;
    int32_t s11022348;
    float  *ring;   /* port 4298096 */
} eb_dly1_state;

void eb_dly1_tick(eb_dly1_state *s, const eb_dly1_coef *c,
                  float in36, float in38, float k5,
                  float *o176, float *o177);

#endif
