/* eb_fx_e5.h -- GENERATED by tools/engineb/arm_xform.py */
#ifndef ENGINEB_EB_FX_E5_H
#define ENGINEB_EB_FX_E5_H
#include <stdint.h>

typedef struct {
    float   k96336;
    float   k96352;
    float   k96368;
    float   k96384;
    float   k96400;
    float   k96416;
    float   k96432;
    float   k96448;
    float   k96464;
    float   k96480;
    float   k96496;
    float   k96512;
    float   k96528;
    float   k96544;
    float   k96560;
    float   k96576;
    float   k96592;
    float   k96608;
    float   k96624;
    float   k96640;
    float   k96656;
    float   k96672;
    float   k96688;
    float   k96704;
    float   k96720;
    float   k96736;
    float   k96752;
    float   k96768;
    float   k96784;
    float   k96800;
    float   k96816;
    float   k96832;
    float   k96848;
    float   k96864;
    float   k96880;
    float   k96896;
    float   k96912;
    int32_t k101028;
} eb_fx_e5_coef;

typedef struct {
    float   s84672;
    float   s95888;
    float   s95904;
    float   s95920;
    float   s95936;
    float   s95952;
    float   s95968;
    float   s95984;
    float   s96000;
    float   s96016;
    float   s96032;
    float   s96048;
    float   s96064;
    float   s96080;
    float   s96096;
    float   s96112;
    float   s96128;
    float   s96144;
    float   s96160;
    float   s96176;
    float   s96192;
    float   s96208;
    float   s96224;
    float   s96240;
    float   s96256;
    float   s96272;
    float   s96288;
    float   s96304;
    float   s96320;
    float   s101040;
    float   s101056;
    float   s101060;
    float   s101064;
    int32_t s101024;
    float  *ring;
} eb_fx_e5_state;

/* `in84624` is the master input stage's one-pole output, written EARLIER
 * in the same sample by another block -- an argument, never a cached
 * coefficient. `o593` carries FLOAT BITS through an int-declared local in
 * the port, so the caller must bit-copy it, not assign it. */
/* v56 and v58 are IN-OUT. The port assigns both CONDITIONALLY inside
 * this arm -- `if (x >= -1.0) v58 = ...` -- so on the other branch they
 * keep the value the DELAY stage left, which is a genuine live-in that a
 * live-variable check calls `assigned in block`. MEASURED: taking them as
 * pure outputs left them uninitialised, and the EFFECT-0 arm produced
 * -0.9845 where the port had exactly -1. The e1 and e5 arms passed their
 * gates that way only because the conditions happened to hold in every
 * scenario that reaches them. */
void eb_fx_e5_tick(eb_fx_e5_state *s, const eb_fx_e5_coef *c,
                   float in84624, float in56, float in58,
                   float *o56, float *o58, float *o593);

#endif
