/* eb_fx_e1.h -- GENERATED by tools/engineb/arm_xform.py */
#ifndef ENGINEB_EB_FX_E1_H
#define ENGINEB_EB_FX_E1_H
#include <stdint.h>

typedef struct {
    float   k86288;
    float   k86304;
    float   k86320;
    float   k86352;
    float   k86368;
    float   k86384;
    float   k86400;
    float   k86416;
    float   k86432;
    float   k86448;
    float   k86464;
    float   k86480;
    float   k86496;
    float   k86512;
    float   k86528;
    float   k86544;
    float   k86560;
    float   k86576;
    float   k86592;
    float   k86608;
    float   k86624;
    float   k86640;
    float   k86816;
    float   k86832;
    float   k86848;
    float   k86864;
    float   k86880;
    float   k86896;
    float   k86912;
    float   k86928;
    float   k86944;
    float   k86960;
    float   k87056;
    float   k87072;
    float   k87088;
    float   k87104;
    float   k87120;
    float   k87136;
    float   k87152;
} eb_fx_e1_coef;

typedef struct {
    float   s84672;
    float   s86096;
    float   s86112;
    float   s86128;
    float   s86144;
    float   s86160;
    float   s86176;
    float   s86192;
    float   s86208;
    float   s86224;
    float   s86240;
    float   s86256;
    float   s86272;
    float   s86656;
    float   s86672;
    float   s86688;
    float   s86704;
    float   s86720;
    float   s86736;
    float   s86752;
    float   s86768;
    float   s86784;
    float   s86800;
    float   s86976;
    float   s86992;
    float   s87008;
    float   s87024;
    float   s87040;
} eb_fx_e1_state;

/* `in84624` is the master input stage's one-pole output, written EARLIER
 * in the same sample by another block -- an argument, never a cached
 * coefficient. `o593` carries FLOAT BITS through an int-declared local in
 * the port, so the caller must bit-copy it, not assign it. */
/* v56 and v58 are IN-OUT. The port assigns both CONDITIONALLY inside
 * this arm -- `if (x >= -1.0) v58 = ...` -- so on the other branch they
 * keep the value the DELAY stage left, which is a genuine live-in that a
 * live-variable check calls `assigned in block`. MEASURED: taking them as
 * pure outputs left them uninitialised, and the EFFECT-0 arm produced
 * -0.9845 where the port had exactly -1. The e1 and e5 arms passed their
 * gates that way only because the conditions happened to hold in every
 * scenario that reaches them. */
void eb_fx_e1_tick(eb_fx_e1_state *s, const eb_fx_e1_coef *c,
                   float in84624, float in56, float in58,
                   float *o56, float *o58, float *o593);

#endif
