/* eb_fx_e0.h -- GENERATED by tools/engineb/arm_xform.py */
#ifndef ENGINEB_EB_FX_E0_H
#define ENGINEB_EB_FX_E0_H
#include <stdint.h>

/* The EFFECT LABEL_164 core: EFFECT TYPE 0 and >= 6. No factory patch
 * selects it; reached only by the DOCTORED-bank scenario (task 1b-3). */

typedef struct {
    float   k85136;
    float   k85152;
    float   k85168;
    float   k85184;
    float   k85200;
    float   k85216;
    float   k85232;
    float   k85248;
    float   k85264;
    float   k85280;
    float   k85296;
    float   k85312;
    float   k85328;
    float   k85344;
    float   k85360;
    float   k85376;
    float   k85392;
    float   k85408;
    float   k85424;
    float   k85440;
    float   k85456;
    float   k85472;
    float   k85488;
    float   k85504;
    float   k85520;
    float   k85536;
    float   k85552;
    float   k85568;
    float   k85744;
    float   k85760;
    float   k85776;
    float   k85792;
    float   k85808;
    float   k85824;
    float   k85840;
    float   k85856;
    float   k85872;
    float   k85888;
    float   k85984;
    float   k86000;
    float   k86016;
    float   k86032;
    float   k86048;
    float   k86064;
    float   k86080;
} eb_fx_e0_coef;

typedef struct {
    float   s84672;
    float   s84896;
    float   s84912;
    float   s84928;
    float   s84944;
    float   s84960;
    float   s84976;
    float   s84992;
    float   s85008;
    float   s85024;
    float   s85040;
    float   s85056;
    float   s85072;
    float   s85088;
    float   s85104;
    float   s85120;
    float   s85584;
    float   s85600;
    float   s85616;
    float   s85632;
    float   s85648;
    float   s85664;
    float   s85680;
    float   s85696;
    float   s85712;
    float   s85728;
    float   s85904;
    float   s85920;
    float   s85936;
    float   s85952;
    float   s85968;
} eb_fx_e0_state;

void eb_fx_e0_tick(eb_fx_e0_state *s, const eb_fx_e0_coef *c,
                 float in84624, float in56, float in58, float *o56, float *o58, float *o593);

#endif
