/* eb_halfos_fir.h -- GENERATED by tools/engineb/gen_halfos_fir.py.
 * The 2x decimator for EB_HALF_OS. DESIGNED, not borrowed: its
 * in-band magnitude matches the port's own 4x FIR (measured by
 * executing eb_decim_tick) to 0.0783 dB over 20 Hz..18 kHz, so the
 * cascade with the unchanged biquad matches too. Stopband -54.4 dB.
 */
#define EB_HALFOS_FIR_TAPS 24
static const float eb_halfos_fir[EB_HALFOS_FIR_TAPS] = {
    0x1.58a6e00000000p-10f,
    0x1.f5b3260000000p-11f,
    -0x1.c9a1800000000p-9f,
    -0x1.405dd40000000p-8f,
    0x1.2895200000000p-8f,
    0x1.9770ca0000000p-7f,
    -0x1.e7ec740000000p-10f,
    -0x1.a6c7e80000000p-6f,
    -0x1.600c7a0000000p-7f,
    0x1.2495b00000000p-4f,
    0x1.7f88b00000000p-3f,
    0x1.13a3040000000p-2f,
    0x1.13a3040000000p-2f,
    0x1.7f88b00000000p-3f,
    0x1.2495b00000000p-4f,
    -0x1.600c7a0000000p-7f,
    -0x1.a6c7e80000000p-6f,
    -0x1.e7ec740000000p-10f,
    0x1.9770ca0000000p-7f,
    0x1.2895200000000p-8f,
    -0x1.405dd40000000p-8f,
    -0x1.c9a1800000000p-9f,
    0x1.f5b3260000000p-11f,
    0x1.58a6e00000000p-10f,
};
