/* eb_reverb_halfband.h -- GENERATED by tools/engineb/gen_reverb_halfband.py.
 * The 44.1k<->22.05k anti-alias / anti-image FIR for the half-rate reverb.
 * 41-tap linear-phase Kaiser-windowed sinc, cutoff 8000 Hz, beta 11.
 * MEASURED: passband ripple <= 0.344 dB to 6 kHz; fold band (>=11025 Hz)
 * >= 53.2 dB down, so the worst decimation alias is ~ -53 dBFS.
 * Used both ways (symmetric): filter-then-decimate in, upsample-then-
 * filter out. The interpolation phases carry an implicit x2 for the
 * zero-stuffing; the caller applies it. */
#ifndef ENGINEB_EB_REVERB_HALFBAND_H
#define ENGINEB_EB_REVERB_HALFBAND_H
#define EB_REV_HB_TAPS 41
static const float eb_rev_hb[EB_REV_HB_TAPS] = {
    -0x1.a686560000000p-20f,
    0x1.620da40000000p-18f,
    0x1.cba55a0000000p-15f,
    0x1.2e49440000000p-14f,
    -0x1.7f9a820000000p-13f,
    -0x1.46de760000000p-11f,
    -0x1.2d88360000000p-12f,
    0x1.99d25c0000000p-10f,
    0x1.8346040000000p-9f,
    -0x1.356b780000000p-13f,
    -0x1.d963d00000000p-8f,
    -0x1.18518a0000000p-7f,
    0x1.48413a0000000p-8f,
    0x1.7d3aba0000000p-6f,
    0x1.1b02e20000000p-6f,
    -0x1.9c69060000000p-6f,
    -0x1.04a7200000000p-4f,
    -0x1.a774ae0000000p-6f,
    0x1.d589dc0000000p-4f,
    0x1.2448aa0000000p-2f,
    0x1.7385320000000p-2f,
    0x1.2448aa0000000p-2f,
    0x1.d589dc0000000p-4f,
    -0x1.a774ae0000000p-6f,
    -0x1.04a7200000000p-4f,
    -0x1.9c69060000000p-6f,
    0x1.1b02e20000000p-6f,
    0x1.7d3aba0000000p-6f,
    0x1.48413a0000000p-8f,
    -0x1.18518a0000000p-7f,
    -0x1.d963d00000000p-8f,
    -0x1.356b780000000p-13f,
    0x1.8346040000000p-9f,
    0x1.99d25c0000000p-10f,
    -0x1.2d88360000000p-12f,
    -0x1.46de760000000p-11f,
    -0x1.7f9a820000000p-13f,
    0x1.2e49440000000p-14f,
    0x1.cba55a0000000p-15f,
    0x1.620da40000000p-18f,
    -0x1.a686560000000p-20f,
};
#endif /* ENGINEB_EB_REVERB_HALFBAND_H */
