/* eb_vcf_halfos_fir.h -- the 2x->1x decimator for the HALF-RATE LADDER.
 *
 * GENERATED by a least-squares linear-phase fit to the PORT'S OWN 4x
 * decimator response, restricted to the 2x band. Do not hand-edit.
 *
 * WHY IT EXISTS. The first half-rate ladder reused eb_halfos_fir -- 24 taps,
 * designed for the DCO path -- on the strength of a note saying the VCF's
 * sixteen decimator cells and the DCO decimator's hold the same MULTISET.
 * That note is about the 4x filters and says nothing about a 2x substitute.
 * Swapping one anti-imaging filter for another changes the transfer function
 * of the whole ladder output, and the sonic gate measured the result at
 * 24.80 dB against a 1.0 dB bound.
 *
 * TARGET, MEASURED from the port's own 32-tap coefficients:
 *     1 kHz  0.00 dB · 10 kHz  0.03 · 15 kHz -0.28 · 20 kHz -3.23
 *     22.05 kHz -6.02 · 30 kHz -34.99 · 44.1 kHz -65.24
 * THIS FILTER matches that to 0.003 dB worst case over 0-20 kHz and lands
 * -5.99 dB at 22.05 kHz against the port's -6.02.
 *
 * Symmetric and even length, so it folds into 8 coefficients exactly as the
 * 4x path folds its 32 into 16.
 */
#ifndef ENGINEB_EB_VCF_HALFOS_FIR_H
#define ENGINEB_EB_VCF_HALFOS_FIR_H

#define EB_VCF_HALFOS_TAPS 16
static const float eb_vcf_halfos_fir[EB_VCF_HALFOS_TAPS] = {
    -2.004076238e-03f,
    -5.243304734e-03f,
    1.089367282e-02f,
    2.130934830e-02f,
    -3.962509526e-02f,
    -7.024621697e-02f,
    1.376458436e-01f,
    4.473364357e-01f,
    4.473364357e-01f,
    1.376458436e-01f,
    -7.024621697e-02f,
    -3.962509526e-02f,
    2.130934830e-02f,
    1.089367282e-02f,
    -5.243304734e-03f,
    -2.004076238e-03f,
};

#endif
