/* jx_srate.h -- GENERATED by jx3p/tools/jx_conv_tables.py from the booted JX-3P; do not edit.
 * The engine-rate setting table (rva 0x981B58): the setting listener (rva 0x3221D0) indexes it
 * with vm.vs.sampleRate & 0x7F; 0..4 the engine rates, 5 the automatic setting (never read),
 * 6..127 the bytes that follow it in the image (they differ from the JUNO-60's from index 6).
 * The render-object table and its vectors are the JUNO-60's (src/conv_tables.h, the same
 * bytes: jx3p/docs/HOST_LAYER.md). */
#ifndef JX_SRATE_H
#define JX_SRATE_H
#include <stdint.h>
#define JX_SRATE_SHA256 "8ccfb6e62eab81839ec0072054224e351621a397f3d98c279c29acf1501f5478"
static const int32_t JX_SRATE[128] = {
    96000, 88200, 48000, 44100, 32000, 989855744, 31, 31,
    31, 31, 989855744, 989855744, 989855744, 989855744, 1132462080, 1132462080,
    1132462080, 1132462080, 0, 0, 429065506, 1, 12291500, 0,
    0, 2, 12291512, 32, 0, 1, 429065506, 1,
    12291556, 0, 0, 2, 12291568, 32, 0, 1,
    429065506, 1, 12291604, 0, 0, 2, 12291616, 32,
    0, 1, 429065506, 1, 12291652, 0, 0, 2,
    12291664, 32, 0, 1, 429065506, 2, 12291704, 1,
    12291720, 3, 12291760, 32, 0, 1, 429065506, 1,
    12291844, 0, 0, 4, 12291856, 32, 0, 1,
    429065506, 5, 12291928, 0, 0, 10, 12291968, 120,
    0, 1, 429065506, 5, 12292124, 0, 0, 12,
    12292176, 80, 0, 1, 429065506, 15, 12292332, 0,
    0, 37, 12292464, 320, 0, 1, 429065506, 1,
    12292796, 0, 0, 1, 12292808, 40, 0, 1,
    429065506, 2, 12292852, 1, 12292868, 4, 12292912, 32,
};
#endif
