//
// juno_probe.cpp — the bit-exact gate ON THE METAL (all scenarios).
//
// Renders the ORIGINAL JUNO port (src/, no levers, no compromises) on the
// bare-metal kernel at 48000 Hz and compares every scenario's sample hash to
// the x86 reference in juno_ref.h. That reference IS the plugin's output (the
// x86 engine nulls EXACTLY 0 vs the plugin). So each "MATCH" is proof the synth
// is bit-identical to the plugin on real ARM.
//
//   PATCH_REF — all 64 factory patches, one sustained note.
//   STORM_REF — seeded note-on/off + patch-change sequences. The metal renders
//               them at the I2S DMA chunk; the reference is the CONTINUOUS
//               render, so a match proves the real-time block callback adds no
//               boundary tick (the S3 failure class) AND that metal == plugin.
//
#include <circle/logger.h>
#include <circle/alloc.h>

extern "C" {
#include "../probe/juno_probe_core.h"
#include "juno_ref.h"                 // generated by pi/probe/host_ref.c
extern const unsigned char juno_bank_blob[];
extern const unsigned char juno_bank_blob_end[];
}

static const int NPATCH = sizeof(PATCH_REF) / sizeof(PATCH_REF[0]);
static const int NSTORM = sizeof(STORM_REF) / sizeof(STORM_REF[0]);

void run_juno_bitexact (void)
{
	CLogger *log = CLogger::Get ();
	int banklen = (int) (juno_bank_blob_end - juno_bank_blob);

	log->Write ("juno", LogNotice,
		    "ENGINE bit-exact gate @ %d Hz: original port, 8 voices, no levers",
		    (int) JUNO_SR);
	log->Write ("juno", LogNotice,
		    "scenarios: %d patches + %d seeded storms (DMA chunk %d)",
		    NPATCH, NSTORM, JUNO_DMA_CHUNK);

	int cap = JUNO_STORM_NFR > JUNO_PATCH_NFR ? JUNO_STORM_NFR : JUNO_PATCH_NFR;
	float *buf = (float *) malloc (sizeof (float) * 2 * cap);
	if (buf == 0) { log->Write ("juno", LogPanic, "probe: out of memory"); return; }

	// 1) all 64 factory patches, sustained note
	int pass = 0;
	for (int i = 0; i < NPATCH; ++i) {
		float pk = 0.0f;
		unsigned long long h = juno_probe_render_hash (
			juno_bank_blob, banklen, PATCH_REF[i].patch,
			JUNO_SR, JUNO_NOTE, JUNO_VEL, JUNO_PATCH_NFR, buf, &pk);
		bool ok = (h == PATCH_REF[i].hash);
		if (ok) ++pass;
		else log->Write ("juno", LogNotice,
			"patch %2d  hash %016llx  !! DIFF (want %016llx)",
			PATCH_REF[i].patch, h, PATCH_REF[i].hash);
	}
	log->Write ("juno", LogNotice, "PATCHES: %d/%d identical to the plugin",
		    pass, NPATCH);

	// 2) seeded storms, rendered at the I2S DMA chunk vs the continuous plugin
	int spass = 0;
	for (int i = 0; i < NSTORM; ++i) {
		float pk = 0.0f;
		unsigned long long h = juno_probe_timeline_hash (
			juno_bank_blob, banklen, JUNO_SR, STORM_REF[i].seed,
			STORM_REF[i].frames, JUNO_DMA_CHUNK, buf, &pk);
		bool ok = (h == STORM_REF[i].hash);
		if (ok) ++spass;
		log->Write ("juno", LogNotice,
			"storm %08x  hash %016llx  pk %.4f  %s",
			STORM_REF[i].seed, h, pk,
			ok ? "== MATCH (chunk-invariant, bit-exact)" : "!! DIFF");
	}
	log->Write ("juno", LogNotice, "STORMS: %d/%d identical to the plugin", spass, NSTORM);

	free (buf);

	bool all = (pass == NPATCH) && (spass == NSTORM);
	log->Write ("juno", LogNotice, "BIT-EXACT RESULT: %d/%d scenarios",
		    pass + spass, NPATCH + NSTORM);
	if (all)
		log->Write ("juno", LogNotice,
			"FULL SYNTH BIT-EXACT ON BARE METAL — ALL SCENARIOS — EXACT WAVEFORM MATCH");
	else
		log->Write ("juno", LogNotice,
			"DIVERGENCE — the metal render is NOT bit-exact (see DIFF rows)");
}
