/* Writes main/gen/msq_wave_check.h: the host's msq_wave_crc(), which the
 * firmware prints its own against at boot (WAVES: line). */
#include <stdio.h>
#include "msq_core.h"
int main(int argc, char **argv)
{
    FILE *f = fopen(argv[1], "w");
    if (!f) return 1;
    uint32_t c = msq_wave_crc();
    fprintf(f, "/* GENERATED by test/wave_crc.c (sh test/run.sh) -- DO NOT EDIT. */\n#define MSQ_WAVE_CRC 0x%08xu\n", c);
    fclose(f);
    printf("WAVE CRC host %08x -> %s\n", c, argv[1]);
    return 0;
}
