#!/usr/bin/env python3
"""gen_ir.py -- bake engine-sim's exhaust impulse responses into gen/es_ir.h.

Source: engine-sim es/sound-library (MIT, Ange Yaghi). Upstream's own rule is
applied (Synthesizer::initializeImpulseResponse): keep samples up to the last
one with |v| > 100, at most 10,000, scale = volume / INT16_MAX. The volumes
are es/sound-library/impulse_responses.mr's.

  python3 carsynth/tools/gen_ir.py <engine-sim checkout>
"""
import os, struct, sys, wave

IRS = [  # (C name, file, volume, label)  -- impulse_responses.mr
    ("ES_IR_DEFAULT", "smooth/smooth_39.wav", 0.001, "Smooth"),
    ("ES_IR_MILD", "new/mild_exhaust.wav", 0.01, "Mild"),
    ("ES_IR_MILD_REV", "new/mild_exhaust_reverb.wav", 0.01, "Mild + garage"),
    ("ES_IR_MINIMAL1", "new/minimal_muffling_01.wav", 0.01, "Straight pipe"),
    ("ES_IR_MINIMAL2", "new/minimal_muffling_02.wav", 0.01, "Straight pipe 2"),
    ("ES_IR_SHARP", "sharp/sharp_01.wav", 0.001, "Sharp"),
    ("ES_IR_REAL", "archive/test_engine_14_eq_adjusted_16.wav", 0.001, "Recorded"),
]


def main():
    root = sys.argv[1]
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "gen", "es_ir.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("/* es_ir.h -- GENERATED by carsynth/tools/gen_ir.py from engine-sim\n"
                " * es/sound-library (MIT, Ange Yaghi). int16 samples; tap = volume*s/32767. */\n"
                "#ifndef ES_IR_H\n#define ES_IR_H\n#include <stdint.h>\n")
        for name, fn, vol, label in IRS:
            w = wave.open(os.path.join(root, "es", "sound-library", fn))
            assert w.getframerate() == 44100 and w.getsampwidth() == 2
            n = w.getnframes()
            ch = w.getnchannels()
            d = struct.unpack("<%dh" % (n * ch), w.readframes(n))[::ch]
            last = 0
            for i, v in enumerate(d):
                if abs(v) > 100:
                    last = i + 1
            m = min(10000, last)
            f.write("static const int16_t %s[%d] = {%s};\n" % (name, m, ",".join(str(x) for x in d[:m])))
        f.write("typedef struct { const int16_t *s; int n; float volume; const char *label; } es_ir_t;\n")
        f.write("#define ES_N_IR %d\n" % len(IRS))
        f.write("static const es_ir_t ES_IRS[ES_N_IR] = {\n")
        for name, fn, vol, label in IRS:
            f.write("    {%s, (int)(sizeof %s / sizeof %s[0]), %.6gf, \"%s\"},\n" % (name, name, name, vol, label))
        f.write("};\n#endif\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
