/* GENERATED by tools/engineb/gen_devcells.py -- DO NOT EDIT. */
/* union of docs/engineb/data/devrecall/
 *   touched.txt static_extra.txt cells_gate.txt cells_legacy.txt */
#ifndef EBDEV_SEG_H
#define EBDEV_SEG_H
#define EBDEV_VTILE   10688u
#define EBDEV_VSTRIDE 10512u
#define EBDEV_VLO     176u
#define EBDEV_VHI     84272u
#define EBDEV_NSEG 31
#define EBDEV_SEGBYTES 16296u
#define EBDEV_NSCAT 12
typedef struct { unsigned lo, hi, at; } ebdev_seg;
/* The TABLE is the reference form. ebdev.c uses the literal chain in
 * ebdev_map.h for the real lookup and, under -DEBDEV_INSTRUMENT, checks
 * the chain against this table on every access. A generator that emits
 * a chain disagreeing with its own table is the failure this catches. */
static const ebdev_seg EBDEV_SEGTAB[EBDEV_NSEG] = {
  { 88200u, 88204u, 0u },
  { 90400u, 96916u, 4u },
  { 101024u, 102788u, 6520u },
  { 131072u, 131076u, 8284u },
  { 154360u, 154364u, 8288u },
  { 192000u, 192004u, 8292u },
  { 262144u, 262148u, 8296u },
  { 524288u, 524292u, 8300u },
  { 588912u, 588916u, 8304u },
  { 600000u, 600004u, 8308u },
  { 842520u, 842524u, 8312u },
  { 1048576u, 1048580u, 8316u },
  { 1499996u, 1500000u, 8320u },
  { 2097152u, 2097156u, 8324u },
  { 2199952u, 2199960u, 8328u },
  { 2418432u, 2418436u, 8336u },
  { 2509804u, 2509808u, 8340u },
  { 4194304u, 4194308u, 8344u },
  { 4195232u, 4195300u, 8348u },
  { 4297120u, 4298084u, 8416u },
  { 6395248u, 6396628u, 9380u },
  { 6429408u, 6430932u, 10760u },
  { 6463712u, 6463720u, 12284u },
  { 6496496u, 6497604u, 12292u },
  { 8388608u, 8388612u, 13400u },
  { 8594768u, 8594776u, 13404u },
  { 8999996u, 9000000u, 13412u },
  { 10691936u, 10693476u, 13416u },
  { 10726256u, 10726264u, 14956u },
  { 10758864u, 10759876u, 14964u },
  { 11022032u, 11022352u, 15976u },
};
static const unsigned EBDEV_SCATTAB[EBDEV_NSCAT] = {
  304u, 320u, 592u, 1072u, 1856u, 3968u, 5520u, 6864u, 7600u, 9680u, 9824u, 10320u
};
#endif
