/* test_pitch_tab.c — the generated pre-split pitch table must equal the
 * arithmetic it replaces, bit for bit.
 *
 * WHY. EB_PITCH_FAST's whole saving on the ESP32-S3 comes from moving the
 * double->(float,float) coefficient split off the per-sample path into
 * engine_b/eb_pitch_tab.h at build time. A generated constant table that
 * silently drifts from the split it stands for would change the pitch of the
 * instrument while every scenario still looked plausible. So the table is
 * CHECKED against df_coef(), not trusted because a generator wrote it.
 *
 * This is also the regression guard for regenerating: if juno_pitch_table ever
 * changes and eb_pitch_tab.h is not regenerated (or is regenerated by a
 * different rule), this goes red.
 */
#include <stdio.h>
#include "eb_pitch.h"

int main(void)
{
    int bad = eb_pitch_tab_selfcheck();
    printf("pre-split pitch table vs df_coef: %d of %d pairs differ\n",
           bad, 29 * 13);
    printf("PITCH TABLE SPLIT: %s\n", bad ? "FAIL" : "PASS");
    return bad ? 1 : 0;
}
