#!/usr/bin/env python3
"""Emit src/juno_param_map.h: the patch-INDEPENDENT panel param map
{db_index, engine_offset, tableId} for the exposed JUNO-60 voice params, so the
C preset loader can decode ANY factory bank record (not just SQ ARPG).
Sources: refs/script_param_map.json (DB->offset via Script.xml) +
refs/param_table_full.json (offset->tableId). Capture-free."""
import json, os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sm=json.load(open(os.path.join(ROOT,'refs/script_param_map.json')))['params']
pt=json.load(open(os.path.join(ROOT,'refs/param_table_full.json')))
off2tid={}
for e in pt.values():
    if isinstance(e,dict) and e.get('offset') is not None and e.get('tableId') is not None:
        off2tid.setdefault(e['offset'],e['tableId'])
rows=[]
for e in sm:
    if not e.get('panel_exposed') or e.get('engine_offset') is None: continue
    off=e['engine_offset']; tid=off2tid.get(off)
    if tid is None: continue
    rows.append((e['db_index'],off,tid,(e.get('name') or '').strip()))
# de-dup by offset, lowest db
seen=set(); uniq=[]
for r in sorted(rows,key=lambda x:x[0]):
    if r[1] in seen: continue
    seen.add(r[1]); uniq.append(r)
with open(os.path.join(ROOT,'src/juno_param_map.h'),'w') as f:
    f.write("/* juno_param_map.h - GENERATED by tools/build_param_map.py.\n")
    f.write(" * Patch-independent panel param map: {db_index, engine_offset, tableId}\n")
    f.write(" * for the JUNO-60 exposed voice params. Lets the C loader decode any\n")
    f.write(" * factory bank record. DB->offset from Script.xml; offset->tableId from\n")
    f.write(" * the vtable oracle (refs/param_table_full.json). Capture-free. */\n")
    f.write("#ifndef JUNO_PARAM_MAP_H\n#define JUNO_PARAM_MAP_H\n")
    f.write("typedef struct { int db; int off; int tid; const char* name; } juno_param_map_ent;\n")
    f.write("static const juno_param_map_ent JUNO_PARAM_MAP[] = {\n")
    for db,off,tid,nm in uniq:
        f.write(f'  {{{db:4}, {off:6}, {tid:3}, "{nm}"}},\n')
    f.write("};\n")
    f.write(f"#define JUNO_PARAM_MAP_N {len(uniq)}\n")
    # FX selector DB indices (stride-4 region)
    f.write("/* FX/global selectors (stride-4 region; k=309+(db-871)*4 on the bank stream) */\n")
    f.write("#define JUNO_DB_MODEL 871\n#define JUNO_DB_FILTER 872\n#define JUNO_DB_CHORUS 873\n")
    f.write("#define JUNO_DB_FXA 875\n#define JUNO_DB_REVERB 876\n")
    f.write("#endif\n")
print(f"wrote src/juno_param_map.h: {len(uniq)} exposed voice params")
