#!/usr/bin/env python3
"""build_sqarpg_apply.py — produce the FAITHFUL SQ Dynamic ARPG coefficient apply set,
replacing the hand-tuned overlay in tests/play_preset.c.

Chain (all capture-free / from plugin data):
  bank record 1 (SQ ARPG)  --nibble decode-->  per-DB step
  DB-index  --refs/script_param_map.json-->    engine offset (Script.xml alignment)
  engine offset --refs/param_table_full.json--> tableId
  => {offset, tableId, step}  applied via juno_param_apply_lut(state,offset,tableId,step,1)

Writes refs/sqarpg_apply.json and tests/sqarpg_apply.h (a C array for the renderer).
"""
import json, os, struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BANK = os.path.join(ROOT, 'refs/preset_banks/bank1.bin')
HDR, REC = 23, 20223

def decode_record(idx):
    d = open(BANK, 'rb').read()
    body = d[HDR + idx * REC: HDR + (idx + 1) * REC]
    # nibble stream over the full record body; value[k] = body[2k]*16 + body[2k+1]
    return [body[2 * k] * 16 + body[2 * k + 1] for k in range(len(body) // 2)]

def main():
    dec = decode_record(1)                      # record 1 = SQ Dynamic ARPG
    # calibration: name "SQ Dynamic ARPG" sits at decoded k=78; DB d -> k = (d-755)+19
    name = ''.join(chr(dec[78 + j]) if 32 <= dec[78 + j] < 127 else '?' for j in range(16))
    assert 'SQ Dynamic' in name, f"calibration check failed: name={name!r}"
    def step_for_db(db):
        k = (db - 755) + 19
        return dec[k] if 0 <= k < len(dec) else None

    smap = json.load(open(os.path.join(ROOT, 'refs/script_param_map.json')))['params']
    ptab = json.load(open(os.path.join(ROOT, 'refs/param_table_full.json')))
    off2tid = {}
    for pid, e in ptab.items():
        if isinstance(e, dict) and e.get('offset') is not None and e.get('tableId') is not None:
            off2tid.setdefault(e['offset'], e['tableId'])

    apply = []
    for e in smap:
        if not e['panel_exposed'] or e['engine_offset'] is None:
            continue
        off = e['engine_offset']
        tid = off2tid.get(off)
        if tid is None:
            continue
        step = step_for_db(e['db_index'])
        if step is None or not (0 <= step <= 255):
            continue
        apply.append({"offset": off, "tableId": tid, "step": step,
                      "name": e['name'], "db_index": e['db_index']})
    # de-dup by offset (keep first / lowest db)
    seen, uniq = set(), []
    for a in sorted(apply, key=lambda x: x['db_index']):
        if a['offset'] in seen:
            continue
        seen.add(a['offset']); uniq.append(a)

    json.dump({"_meta": {"preset": "SQ Dynamic ARPG (bank record 1)",
               "source": "Script.xml DB->offset alignment + bank nibble decode + param_table_full tableId",
               "name_anchor": name},
               "apply": uniq},
              open(os.path.join(ROOT, 'refs/sqarpg_apply.json'), 'w'), indent=1)

    with open(os.path.join(ROOT, 'tests/sqarpg_apply.h'), 'w') as f:
        f.write("/* generated by tools/build_sqarpg_apply.py — SQ Dynamic ARPG faithful apply set.\n")
        f.write(" * {engine_offset, tableId, step} from Script.xml binding + bank decode. */\n")
        f.write("static const struct { int off; int tid; int step; } SQARPG_APPLY[] = {\n")
        for a in uniq:
            f.write(f"  {{{a['offset']:6}, {a['tableId']:3}, {a['step']:3}}},  /* DB{a['db_index']} {a['name']} */\n")
        f.write("};\n")
        f.write(f"#define SQARPG_APPLY_N {len(uniq)}\n")

    print(f"name anchor: {name!r}")
    print(f"wrote refs/sqarpg_apply.json + tests/sqarpg_apply.h: {len(uniq)} params")
    for a in uniq:
        print(f"  off {a['offset']:6} tid {a['tableId']:3} step {a['step']:3}  DB{a['db_index']} {a['name']}")

if __name__ == '__main__':
    main()
