#!/usr/bin/env python3
"""Generate carp_patterns.h : the JU-06A arp SCATTER pattern table as a C byte
array, extracted programmatically from the PE .rdata (RVA 0x9C4480). NOT hand-typed.
Emits the reachable slab0..9 x sub0..14 region (82500 bytes) verbatim + a sha256
checksum the C code can assert against at build time, and the arp controller's
apply table (RVA 0x9D86D0, 1500 int32).
Usage: python3 gen_carp_patterns.py > carp_patterns.h
"""
import pefile, hashlib, sys
import os as _o, sys as _s; _s.path.insert(0, _o.path.join(_o.path.dirname(_o.path.abspath(__file__)), "verify"))
import truth
BIN = truth.VST3  # ground truth via truth/ (single source)
pe=pefile.PE(BIN); IMG=pe.get_memory_mapped_image()
TABLE_RVA=0x9C4480; SLAB_STRIDE=8250; SUB_STRIDE=550; NSLABS=10; NSUBS=15
LEN=SLAB_STRIDE*NSLABS   # 82500 covers slabs 0..9 (each 8250 = 15 subs)
data=IMG[TABLE_RVA:TABLE_RVA+LEN]
sha=hashlib.sha256(data).hexdigest()
out=[]
out.append("/* carp_patterns.h - GENERATED by gen_carp_patterns.py from the JU-06A PE")
out.append(" * .rdata SCATTER pattern table (RVA 0x%X). Do not edit by hand." % TABLE_RVA)
out.append(" * slab(SCATTER TYPE 0..9) stride %d, sub(SCATTER DEPTH+7) stride %d." % (SLAB_STRIDE,SUB_STRIDE))
out.append(" */")
out.append("#ifndef CARP_PATTERNS_H")
out.append("#define CARP_PATTERNS_H")
out.append("#include <stdint.h>")
out.append("#define CARP_PAT_SLAB_STRIDE %d" % SLAB_STRIDE)
out.append("#define CARP_PAT_SUB_STRIDE  %d" % SUB_STRIDE)
out.append("#define CARP_PAT_NSLABS      %d" % NSLABS)
out.append("#define CARP_PAT_LEN         %d" % LEN)
out.append('#define CARP_PAT_SHA256 "%s"' % sha)
out.append("static const uint8_t carp_pattern_table[CARP_PAT_LEN] = {")
line=""
for i,b in enumerate(data):
    tok="%d," % b
    if len(line)+len(tok) > 96:
        out.append(line); line=""
    line += tok
if line: out.append(line)
out.append("};")
# The arp controller's apply table (rva 0x9D86D0, int32, read by rva 0x3C0EC0 as
# [150 * SCATTER TYPE + 15 * k + (SCATTER DEPTH + 7)]): k 0..6 the values the apply
# sends to dispatch 312..318, k 7 the rate delta, k 8 an argument the pattern
# request does not read, k 9 the range delta.
APPLY_RVA = 0x9D86D0
apply_tab = IMG[APPLY_RVA:APPLY_RVA + 1500 * 4]
out.append("#define CARP_APPLY_SHA256 \"%s\"" % hashlib.sha256(apply_tab).hexdigest())
out.append("static const int32_t carp_apply_table[1500] = {")
vals = [int.from_bytes(apply_tab[4 * i:4 * i + 4], 'little', signed=True) for i in range(1500)]
for r in range(0, 1500, 15):
    out.append(" " + ",".join("%d" % v for v in vals[r:r + 15]) + ",")
out.append("};")
out.append("#endif")
sys.stdout.write("\n".join(out)+"\n")
sys.stderr.write("sha256=%s  bytes=%d\n" % (sha, LEN))
