#!/usr/bin/env python3
"""parse_state.py — turn a captured engine-state dump (from tools/capture_state.js)
into the port's coefficient state.

The dump is the plugin's live engine memory (state base .. +N). Our port uses the
SAME offset layout, so the captured coefficient region IS a drop-in correct state for
that patch. This extracts the audible coefficient region and emits a C data file the
port loads wholesale (then renders with fresh note-ons).

    python3 tools/parse_state.py juno_state_0x7ff....bin [--name sqarpg]

Emits src/captured_state_<name>.c with juno_load_captured_<name>(state): it writes the
captured float at every nonzero offset in the voice+aux region. Combined with a fresh
engine_init/chorus_init, this gives the plugin's true coefficient state — the complete,
consistent base the static path cannot derive.
"""
import sys, os, struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Region that holds the per-voice + aux coefficients/state the DSP reads. 0..131072
# covers all 8 voices (main stride 10512, ends ~84432) + aux (101504+). The chorus
# coefficients live deeper (~6.4M/10.7M); pass --full to include the whole dump.
VOICE_REGION = 0x20000  # 131072

def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    path = sys.argv[1]
    name = 'capture'
    if '--name' in sys.argv:
        name = sys.argv[sys.argv.index('--name') + 1]
    full = '--full' in sys.argv
    data = open(path, 'rb').read()
    end = len(data) if full else min(VOICE_REGION, len(data))
    # Extract every 4-byte float slot whose bits are nonzero (a written coefficient/state).
    entries = []
    for off in range(0, end - 3, 4):
        bits = struct.unpack_from('<I', data, off)[0]
        if bits != 0:
            f = struct.unpack('<f', struct.pack('<I', bits))[0]
            if f == f and abs(f) < 1e30:           # finite, sane
                entries.append((off, bits))
    out = os.path.join(ROOT, f'src/captured_state_{name}.c')
    with open(out, 'w') as fh:
        fh.write(f'/* generated by tools/parse_state.py from {os.path.basename(path)}\n')
        fh.write(' * The plugin\'s OWN runtime coefficient state for this patch (ground truth).\n')
        fh.write(' * Load over a fresh engine_init/chorus_init, then render fresh note-ons. */\n')
        fh.write('#include <string.h>\n')
        fh.write(f'static const struct {{ unsigned int off; unsigned int bits; }} CAP_{name.upper()}[] = {{\n')
        for off, bits in entries:
            fh.write(f'  {{{off},0x{bits:08x}u}},\n')
        fh.write('};\n')
        fh.write(f'#define CAP_{name.upper()}_N {len(entries)}\n\n')
        fh.write(f'void juno_load_captured_{name}(unsigned char *st){{\n')
        fh.write(f'  for(int i=0;i<CAP_{name.upper()}_N;i++)\n')
        fh.write(f'    *(unsigned int*)(st+CAP_{name.upper()}[i].off)=CAP_{name.upper()}[i].bits;\n')
        fh.write('}\n')
    print(f'wrote {out}: {len(entries)} nonzero slots from {path} '
          f'({"full workspace" if full else "voice+aux region"})')
    # quick sanity on the smoking-gun offsets
    for off in (4208, 7600, 7616, 4064, 4080, 6832):
        if off + 4 <= len(data):
            b = struct.unpack_from('<I', data, off)[0]
            f = struct.unpack('<f', struct.pack('<I', b))[0]
            print(f'  offset {off}: {f:.6g}')

if __name__ == '__main__':
    main()
