#!/usr/bin/env python3
# translate_chorus_init.py — transcription of sub_1803A1300, the chorus/master
# STATE CONSTRUCTOR. It zeroes the BBD delay buffers + chorus state and writes the
# integer control fields (delay-line lengths 0x80000/0x2000/1024, ring indices).
# These are the fields the master (sub_180363380) indexes its circular buffers
# with as `(len-1) & idx`; without them len==0 -> mask -1 -> out-of-bounds.
#
# Source: chorus_coeffs/zeroinit_sub_1803A1300_1803A1300.c (Hex-Rays, clean —
# no helper calls, no SIMD, no floats). Kept VERBATIM with IDA typedefs and
# `a1` as unsigned char*. Output: src/chorus_init.c.
SRC = "chorus_coeffs/zeroinit_sub_1803A1300_1803A1300.c"
OUT = "src/chorus_init.c"

FIXUPS = {
 "_QWORD *__fastcall sub_1803A1300(__int64 a1)":
   "void *juno_chorus_init(unsigned char *a1)",
}

HEADER = '''/* chorus_init.c — exact C99 transcription of sub_1803A1300, the chorus/master
 * state constructor: zeroes the BBD delay buffers + chorus state and sets the
 * integer control fields (delay-line lengths and ring indices) the master
 * indexes its circular buffers with. Generated by tools/translate_chorus_init.py
 * from chorus_coeffs/zeroinit_sub_1803A1300_*.c, kept verbatim.
 *
 * Call this BEFORE juno_engine_init (the voice-coefficient init): the constructor
 * zeroes broadly, then the coefficient inits fill their fields. The state buffer
 * is normally calloc'd so the zero-stores are redundant, but they are part of the
 * algorithm and reproduced faithfully. Build with -fno-strict-aliasing.
 */
#include "juno_engine.h"

typedef uint32_t _DWORD;
typedef uint64_t _QWORD;
typedef int64_t  __int64;

'''

def main():
    lines = open(SRC).read().splitlines()
    start = next(i for i, l in enumerate(lines)
                 if l.startswith("_QWORD *__fastcall sub_1803A1300"))
    body = lines[start:]
    out = []
    for l in body:
        out.append(FIXUPS.get(l.strip(), l) if l.strip() in FIXUPS else l)
    open(OUT, "w").write(HEADER + "\n".join(out) + "\n")
    print("wrote", OUT)

if __name__ == "__main__":
    main()
