/* juno_param_map.h - GENERATED by tools/build_param_map.py.
 * Patch-independent panel param map: {db_index, engine_offset, tableId}
 * for the JUNO-60 exposed voice params. Lets the C loader decode any
 * factory bank record. DB->offset from Script.xml; offset->tableId from
 * the vtable oracle (refs/param_table_full.json). Capture-free. */
#ifndef JUNO_PARAM_MAP_H
#define JUNO_PARAM_MAP_H
typedef struct { int db; int off; int tid; const char* name; } juno_param_map_ent;
static const juno_param_map_ent JUNO_PARAM_MAP[] = {
  { 751,   1920,  44, "LFO DELAY TIME"},
  { 752,   1088,  22, "LFO RATE"},
  { 753,   4032,   0, "DCO LFO MOD"},
  { 758,   4144,  45, "DCO PWM DEPTH"},
  { 760,   3840,   5, "DCO RANGE"},
  { 770,   4208,  54, "DCO PWM LEVEL"},
  { 771,   4192,  54, "DCO SAW LEVEL"},
  { 772,   4224,  54, "DCO SUB LEVEL"},
  { 773,   6528,  12, "DCO NOISE LEVEL"},
  { 779,   6736,  22, "VCF CUTOFF FREQ"},
  { 781,   6832,  22, "VCF RESONANCE"},
  { 782,  10240,  41, "HPF CUTOFF FREQ"},
  { 783,   7392,  46, "VCF ENV MOD"},
  { 784,   2784,  35, "ENV1 ATTACK"},
  { 785,   2816,  38, "ENV1 DECAY"},
  { 786,   2800,  50, "ENV1 SUSTAIN"},
  { 787,   2832,  38, "ENV1 RELEASE"},
  { 788,   7408,  24, "VCF KEY FOLLOW"},
  { 789,   3264,  35, "ENV2 ATTACK"},
  { 790,   3296,  38, "ENV2 DECAY"},
  { 791,   3280,  50, "ENV2 SUSTAIN"},
  { 792,   3312,  38, "ENV2 RELEASE"},
  { 793,   9584,  21, "VCA TONE"},
};
#define JUNO_PARAM_MAP_N 23
/* FX/global selectors (stride-4 region; k=309+(db-871)*4 on the bank stream) */
#define JUNO_DB_MODEL 871
#define JUNO_DB_FILTER 872
#define JUNO_DB_CHORUS 873
#define JUNO_DB_FXA 875
#define JUNO_DB_REVERB 876
#endif
