/* GENERATED by tools/engineb/gen_s3_vectors.py -- DO NOT EDIT.
 * Host-evaluated expected values for the fork evaluators; the
 * firmware halts on any mismatch. NaN inputs are written as
 * (0.0f/0.0f) upstream; the NaN row's expected value is what
 * the host produced for it. */
{ -0x1.9p+6f, 0x1.bp-145f },
{ -0x1.5ep+6f, 0x1.b2cafp-127f },
{ -0x1.4p+4f, 0x1.1b4866p-29f },
{ -0x1p+0f, 0x1.78b564p-2f },
{ 0x0p+0f, 0x1p+0f },
{ 0x1p-1f, 0x1.a61298p+0f },
{ 0x1.75f118p+1f, 0x1.29150ap+4f },
{ 0x1.4p+3f, 0x1.5829dcp+14f },
{ 0x1.5f999ap+6f, 0x1.c1b95cp+126f },
{ 0x1.7cp+6f, inff },
