/* GENERATED by tools/engineb/gen_listen_coefs.py -- the
 * layout of s3_listen.bin. Patch 0, notes [1, 2, 3, 4, 5, 6, 7, 8]. */
#define S3L_MAGIC 0x4A554E4Fu
#define S3L_NNOTE 8
#define S3L_COEF_SZ 10436u
#define S3L_MCOEF_SZ 1704u
#define S3L_RSTATE_SZ 735236u
#define S3L_MSTATE_SZ 729824u
#define S3L_VOICE_SZ 6808u
/* The hold/release lengths the OFF snapshot was captured
 * at. The firmware MUST use these: the release copies a
 * voice state in, and a state captured at a different
 * instant is a jump -- measured as a 4,716-count step and
 * heard as a pluck at the end of every note. */
#define S3L_HOLD_FRAMES 66151u
#define S3L_REL_FRAMES 30871u
/* chord size of each step */
static const int S3L_NVOICE[S3L_NNOTE] = {1,2,3,4,5,6,7,8};
static const int S3L_RING_LEN[9] = {524288,8192,524288,524288,8192,8192,1024,8192,8192};
/* MEASURED by tools/engineb/listen_mask_probe.c: which
 * voices actually sound in each chord. The allocator fills
 * from voice 7 downward. */
static const unsigned S3L_MASK[S3L_NNOTE] = {0x80u,0xc0u,0xe0u,0xf0u,0xf8u,0xfcu,0xfeu,0xffu};
