/* GENERATED by tools/engineb/gen_s3_vectors.py -- DO NOT EDIT.
 * Host-evaluated expected values for the fork evaluators; the
 * firmware halts on any mismatch. NaN inputs are written as
 * (0.0f/0.0f) upstream; the NaN row's expected value is what
 * the host produced for it. */
{ -0x1.9p+4f, 0x1.fffff6p-21f },
{ -0x1.4p+4f, 0x1.fffff6p-21f },
{ -0x1.3ffffep+4f, 0x1.000012p-20f },
{ -0x1.68p+3f, 0x1.ae89fp-12f },
{ -0x1p-1f, 0x1.6a09eep-1f },
{ 0x0p+0f, 0x1p+0f },
{ 0x1p-1f, 0x1.6a09aap+0f },
{ 0x1.ep+1f, 0x1.ae8988p+3f },
{ 0x1p+3f, 0x1.000008p+8f },
{ 0x1.1cccccp+3f, 0x1.ddb66ap+8f },
{ 0x1.9p+6f, 0x1.ddb66ap+8f },
{ (0.0f/0.0f), 0x1.fffff6p-21f },
